### ISSUE TITLE
Geoip lookup plugin

### ISSUE THREAD

**Issue by runningman84** [Graylog2/graylog2-web-interface#1001]
I would like to lookup ip addresses and store geo data (lat, long, country).

Furthermore we need a map widget. This would allow us to replace logstash/kibana with graylog2.

**Comment by nomoresecrets** [comment]
+1 for a map view

**Comment by PeteFox** [comment]
+1

**Comment by oba11** [comment]
looking forward to this as well instead of pushing geoip formatted logs from logstash

**Comment by zachsis** [comment]
+1

**Comment by voodoodrul** [comment]
+1 .. Asking for the moon here, but related features could include geographic distance covered by a given query, stream alerts based on geographic distance, and hit bubbles on a map similar to the histogram views of log counts when performing a query

**Comment by TheSerapher** [comment]
+1

**Comment by joschi** [comment]
I'm locking (not closing) this issue now. If you absolutely feel you need to upvote something, please do so at https://graylog.ideas.aha.io/ideas/GL2E-I-364.

**Comment by bernd** [comment]
A map and geoip lookup plugin is available in 2.0.0-alpha.4. Rejoice! :smile: 

https://graylog.org/blog/47-fourth-alpha-of-graylog-v2-0-released-with-map-widget-plugin
