### ISSUE TITLE
Default startpage reachable by clicking the logo

### ISSUE THREAD

**Issue by razvanphp** [Graylog2/graylog2-web-interface#1004]
As an improvement, as I user I expect that when I click the logo I will end up on my default dashboard.

We use graylog daily, and logging off just to reach my team's dashboard, or make more clicks to reach it is not productive.

Currently, the logo links to / root which is equal to the seach link in the menu. I suggest changing this one to /search and the logo to point to the default dashboard.

Thank you!

**Comment by edmundoa** [comment]
Closing, as it's the same issue as #1315
