### ISSUE TITLE
Easier permissions management needed

### ISSUE THREAD

**Issue by plista-ld** [Graylog2/graylog2-web-interface#1008]
Currently, adding a new stream or dashboard requires to update every relevant user permissions.

Some ideas to improve it:
- add user roles (members inherit all permissions)
- add edit feature directly in the stream/dashboard interface

Is there a roadmap for this ?

Thanks !

**Comment by slimm609** [comment]
+1

**Comment by edmundoa** [comment]
Related to #629

**Comment by bernd** [comment]
We are working on this. Please use issue Graylog2/graylog2-server#1321 to track progress on this. Thank you!
