### ISSUE TITLE
Allow widget to include sum of values

### ISSUE THREAD

**Issue by nathaniel-auvil** [Graylog2/graylog2-web-interface#1014]
in the latest version one can only put a count of messages in a "total" widget.  Should be able to include any of the measures (sum, mean, total, etc...) in a widget.

**Comment by reggin** [comment]
@lennartkoopmann 
Could you say, when will be release. This feature is very need for us.

**Comment by lennartkoopmann** [comment]
@reggin It will be released in v1.0 of Graylog. The first beta versions are out already if you want to try it out.
