### ISSUE TITLE
Resize Charts

### ISSUE THREAD

**Issue by nathaniel-auvil** [Graylog2/graylog2-web-interface#1015]
Chart widgets all have a set size, in particular height.  Would be nice to increase the size, especially the height to make a chart more readable

**Comment by lennartkoopmann** [comment]
This is partly working in current `master`. Moved this ticket to 1.1.0 milestone to make sure that we either release it fully working or remove the icon until the following release.

**Comment by edmundoa** [comment]
This is done on master now!
