### ISSUE TITLE
Context Search Filtering

### ISSUE THREAD

**Issue by calmdev** [Graylog2/graylog2-web-interface#1016]
Hello,

When using graylog2 I log additional context data with the log messages sent as JSON. I'm trying to determine if it's possible to search against a partial context match. For example, given a user context that's associated with a message:

```
ctxt_user: {"username":"levilewis","role":"admin"}
```

I'm wondering if you can search the given context like so:
```
ctxt_user: {"username":"levilewis"}
```

From what I can tell the filter only matches against the **exact** context. Please let me know if additional details are needed to clarify this. Here is a screenshot (this doesn't return results, but demonstrates how I am trying to search):

![screen shot 2014-12-22 at 4 18 31 pm](https://cloud.githubusercontent.com/assets/461249/5531132/36655292-89f6-11e4-904e-459b3c7998ce.png)

**Comment by edmundoa** [comment]
Hi,

It looks like you are using a really old Graylog version, so I don't think we can help with that. I'd recommend you to upgrade to Graylog 1.0, because everything is so much better, including search :)

**Comment by calmdev** [comment]
No worries, we've deploy a newer version. I'll let you know how it goes — soon as I'm able to start using it. Thanks for your time.

**Comment by edmundoa** [comment]
Great! Let us know if we can help you with something! :+1:
