### ISSUE TITLE
Newlines in message property values not displayed as pre on message detail page. 

### ISSUE THREAD

**Issue by Bouwdie** [Graylog2/graylog2-web-interface#1018]
In the stream view newlines are shown as pre for message property values in the message detail panel in the sidebar. When navigating to a message detail page the newlines are not handled as pre. The div in the sidebar message detail with class `message-detail` gives the nested detail dl -> dd the following css properties.

`.detail-message .description {
word-wrap: break-word;
white-space: pre-wrap;
}`

A similar fix should be applied on the message detail page.

**Comment by edmundoa** [comment]
This was fixed here: https://github.com/Graylog2/graylog2-web-interface/commit/ccfcab200ff283c02c730eb5795d6710e664e36b
