### ISSUE TITLE
Really useful feature required to examine related log messages

### ISSUE THREAD

**Issue by rumatoest** [Graylog2/graylog2-web-interface#1020]
Hello.

In many cases one log message means nothing. Almost every time I need to examine all logs 5min before and after event. To do it I will
 - open log message
 - copy timestamp to clipboard
 - activate absolute search
 - manually paste and edit timestamps in form
 - press search

The problem is, that to many click and actions should be performed.

**Suggested solution** is pretty simple. You should add UI widget to log details near timestamp:
 - It can be drop down list with several intervals (+/- 1min, +/- 2min, +/- 5min, +/- 10min) 
 - Or it can be some spinner to chose +/- interval in minutes and submit button

After submitting interval I should get search result for all logs occured N minutes before and after event. All other search conditions should be cleared.

I wonder how it is not implemented yet, becouse for me it looks obvious and really necessary.

**Comment by edmundoa** [comment]
Hi,
I'm closing the issue, as this was already described in #150. I agree this is something we really need :+1:
