### ISSUE TITLE
Dashboard: values clickable in widget created by "Quick values"

### ISSUE THREAD

**Issue by jyaime** [Graylog2/graylog2-web-interface#1024]
When a widget is created from a stream with the "Quick values" feature, it would be useful to click on a value in the widget to zoom on this value :
=> When a value is clicked on widget, the stream is opened with "field: value" added in the search query
For example, "source: myhostname" to get all messages from a specific server.

This issue extends the request made in #824

**Comment by doshinirav** [comment]
How can I help implement this feature faster.  Any pointers will help.  Which files to look at to get started quickly.

**Comment by edmundoa** [comment]
Hi,

I think this is exactly what was proposed in #824, just applied to a stream widget, so I'm closing it as duplicated. Please reopen if you think is needed.
