### ISSUE TITLE
Regex search in fields do not work.

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-web-interface#1025]
Hi,

According to search syntax help page (https://www.graylog2.org/resources/documentation/general/queries) i can use regex'es within fields. 
But it's not working as stated.

What i've noticed. If field has all lowercase characters or numbers (ip address in my case), then regex search works as it should.
ips_device:xxx??0201p500* - OK
ips_ipt:1??.??.10.10 - OK

When you have mixed case data in field, then regex search is not showing any results.
ips_attack_type:Pd22* - do not work.
ips_attack_type:Pd2223 - works (since full field data is used)

p.s. i'm running latest 0.93.0-SNAPSHOT.

What do you think of that?

**Comment by kroepke** [comment]
I don't think this ever worked because it is directly translated into a elasticsearch query string.
One of the many drawbacks of pretending you can simply index data and having it work...

**Comment by StephanErb** [comment]
Is there any known workaround besides using the full field data?

**Comment by bernd** [comment]
Closing this as we cannot do anything about it currently. Sorry.
