### ISSUE TITLE
Metric list overflows outside of the content column

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-web-interface#1028]
In the current master, this is how the metric list looks like when a metric name is too long:

![screen shot 2015-01-12 at 15 30 55](https://cloud.githubusercontent.com/assets/716185/5704260/1bcc6620-9a70-11e4-81da-1a553a71fedf.png)

**Comment by lennartkoopmann** [comment]
ugh, that needs some CSS `word-wrap: whatever;` love
