### ISSUE TITLE
Dashboard having null pointer exception

### ISSUE THREAD

**Issue by AssadQ** [Graylog2/graylog2-web-interface#1034]
I'm trying to access the dashboard and I'm thrown a null pointer exception. Whenever I try to add things to a dashboard it says that I should create a new one. But my direct links to a dashboard are working.

Been happening for 2 days.
On Chrome.

![1-14-2015 3-38-03 pm](https://cloud.githubusercontent.com/assets/5114461/5747104/676aa012-9c03-11e4-85b7-d0bf915a488f.png)

**Comment by joschi** [comment]
Which version of graylog2-server and graylog2-web-interface are you using?

**Comment by ray65536** [comment]
Hi! I have the same problem, exactly.

Fresh Graylog2 installation, Ubuntu 14.04 + latest updates, latest mongo, elasticsearch and graylog from they official apt repositories.

+ mongodb v2.6.7
+ elasticsearch 1.4.0
+ graylog 0.92.0-1.beta.1

(and it's very strange, that the beta version is in official repo)

[logfile fragment](http://pastebin.com/raw.php?i=2waF9rBs)

**Comment by edmundoa** [comment]
@ray65536 could you please upgrade to 0.92.4 and see if the problem is still there? The upgrade process should be really simple from the beta.

**Comment by AssadQ** [comment]
This particular issue was caused by a dashboard widget based on an abolsute time range search.

The issue is reported by @traviscosgrave in [graylog2-server issue #884](https://github.com/Graylog2/graylog2-server/issues/884) and @edmundoa reports it as resolved in 1.0.0.

**Comment by edmundoa** [comment]
Thank you for updating the issuse @AssadQ :+1:
