### ISSUE TITLE
Better visible replay feature

### ISSUE THREAD

**Issue by Mowee** [Graylog2/graylog2-web-interface#1038]
The Dashboard is really great. But what I'm missing is a more visible Replay Button. Right now I have to do an extra click to replay the widget search. My guess is, if it's more prominent then more people would use it.

**Comment by lennartkoopmann** [comment]
:+1:

**Comment by kroepke** [comment]
@edmundoa isn't this already in for the updated dashboard?

**Comment by edmundoa** [comment]
@kroepke It is, but let's leave the ticket open until we have a more refined design.

**Comment by edmundoa** [comment]
This is already in 1.1-beta, closing the issue.
