### ISSUE TITLE
/system/metrics/node/<nodeid> overflows on 1.0 beta2

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-web-interface#1043]
See screenshot ....

![screen shot 2015-01-17 at 22 28 50](https://cloud.githubusercontent.com/assets/1473308/5790434/4e5236c0-9e98-11e4-94da-17ab369b0a30.png)

**Comment by edmundoa** [comment]
Thank you for reporting the issue. We are aware of it, as you can see in #1043.

**Comment by henrikjohansen** [comment]
Sorry for the noise - I must have missed #1028 ....
