### ISSUE TITLE
Modal dialogs should be closable using escape key

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-web-interface#1045]
It happens pretty often to me that I accidentally open a modal dialog (like the one for creating an input) and I just want to quickly close it using the escape key. Unfortunately it does not listen to this kind of event, so my window manager is handling it and my Safari goes from full screen to windowed mode.

It would be very helpful if any modal dialog in the web interface could handle the escape key by treating it as if the "Cancel"/"Close" button was pressed.

**Comment by edmundoa** [comment]
Just to clarify: this works consistently in all browsers except Safari in full-screen mode. Unfortunately there's no nice way to fix this issue, as Safari binds the escape key to exit full-screen mode.

**Comment by bernd** [comment]
Closing this as we cannot do anything about it at the moment.
