### ISSUE TITLE
Stream throughput seems to be wrong

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-web-interface#1047]
The throughput display for a stream says **39 messages/second**, the overall message throughput is **81 msg/s across 2 nodes**. The stream rule for this stream has a presence check on the message field so the stream should have roughly the same throughput.

Both nodes have a random http message generator with the same settings. So both nodes emit around half of the overall messages. Since the stream throughput shows half of the overall throughput, I guess only one node is asked?

![stream-throughput](https://cloud.githubusercontent.com/assets/461/5806514/252ea3f4-a01a-11e4-9c99-0022012c8293.png)

**Comment by dennisoelkers** [comment]
Fixed in Graylog2/graylog2-web-interface@d04f0841c268b68cf485973b5ecb5f85d8aedbb5
