### ISSUE TITLE
Request-URI Too Long

### ISSUE THREAD

**Issue by andreasfranz** [Graylog2/graylog2-web-interface#1053]
I try add a widget my dashboard that show the number of errors occuring in our applications. For a better overview I want to filter out certain messages. When I do so the URI gets too long because the search is implemented as a GET-request. Wouldn't it be nice to switch to POST-requests to allow longer queries?

**Comment by joschi** [comment]
Wouldn't it be better to create a dedicated stream for those kinds of messages which only contains the relevant messages?

**Comment by andreasfranz** [comment]
As an example when I want to exclude log entries that contains either "String1" or "String2" that would mean I have to create two streams, right? Because there is no way to create a stream rule specifying 'messages matches "String1" OR "String2'

**Comment by joschi** [comment]
You can do this with a regular expression in your stream rules, e. g. `(String1|String2)`.

**Comment by bernd** [comment]
This will be fixed once #1463 is done. Closing this issue.
