### ISSUE TITLE
Improve error messages when an input can't start

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-web-interface#1056]
The text messages when an input can't be started should be a bit more human readable, at least remove the duplication. Here are a couple of examples:

- Graylog2 Radio AMQP input:

     > org.graylog2.plugin.inputs.MisfireException: Could not launch AMQP consumer., Could not launch AMQP consumer., foo 

- Syslog UDP: 

     > org.graylog2.plugin.inputs.MisfireException: org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:1514, org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:1514, Failed to bind to: /0.0.0.0:1514, Address already in use

**Comment by kroepke** [comment]
@edmundoa check if we already have a method like "getMostSpecificCause" for an exception.
Elasticsearch has a helper method like that, and I vaguely remember having implemented this for graylog at some point, too.
Usually the message of that is what you want to display (eg "Address already in use")

**Comment by edmundoa** [comment]
@kroepke Thank you for the hint! In the end I could only find that method on the rest client module, which is not a dependency of the shared module, so I created a utility class in shared to help doing some common things with exceptions.
