### ISSUE TITLE
Output configuration fields with IS_PASSWORD attribute are not obfuscated in stream output list

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1066]
The global output list in `/system` does this, but the output list of a stream does not

**Comment by lennartkoopmann** [comment]
The global output list is built like this:

    List<Output> outputs = outputService.list();

... and the stream output list is built like this:

    List<Output> outputs = streamService.getOutputs(streamId);

I guess the global list is applying the obfuscation and the second one is not. Cannot fix myself right now because my local IDE setup for the web interface is not loading the rest module plugins or wherever the services are coming from nowadays. :) `E_NOCOREDEVELOPER`

**Comment by dennisoelkers** [comment]
Fixed in Graylog2/graylog2-server@360fec613c2201f5414bc8824c17c7bc9d72a004
