### ISSUE TITLE
CSV export saves wrong data.

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-web-interface#1067]
Hi,

I'm running graylog v1.0.0-beta.3.

Export to CSV saves data at click of the export button, not the data being displayed.
E.g. i search for "from last 10 seconds" i get events with "2015-01-26 11:39:19" timestamp.
After 15 seconds on viewing displayed data i decide to export it and click "download as CSV".
Now CSV data in file is not same i've viewed. It's 15 seconds newer.

I do not see the logics here.
My logic is to export what i get for search results.
Ideas?

**Comment by kroepke** [comment]
It runs the same search as displayed, it behaves as if you reloaded the page.
However, the CSV export results are both unsorted and limited quite severely. The former is an artifact of how we use Elasticsearch to get the data, and the second one is a limitation of the web interface itself.
The REST api supports chunked the responses, the web interface does not yet.

**Comment by kroepke** [comment]
IOW if you used a relative time search (last 10 seconds) then you will not get repeatable results.

**Comment by kroepke** [comment]
There has been no feedback on this, so I'll close this issue.
If there's additional information, please reopen it.

Thanks!
