### ISSUE TITLE
Details view improvements

### ISSUE THREAD

**Issue by suff** [Graylog2/graylog2-web-interface#1068]
It would be super awesome if detailed view would be placed under the search view and not on the right. (or it would be possible to move the views the same way as in dashboard) Our stack traces tend to be quite wide and long and it's a pain to read them in Graylog when they are reformatted because of the width of the details view . 

the other thing  is that full_message and message could be monospace formated.

**Comment by bernd** [comment]
The details view is placed in the search result table since 1.1.
