### ISSUE TITLE
Sorting messages table does not restore selected fields

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-web-interface#1071]
If extra fields are selected and a sort on the table is executed, the field selection is not restored.

If the sort is done on an extra field that got selected, this field appears but the others are gone again.

**Comment by kroepke** [comment]
Maybe postpone this until we overhaul the entire search result page. The current implementation is somewhat of a mess (sorry)

**Comment by kroepke** [comment]
This is working as expected in the new search result implementation.
