### ISSUE TITLE
Grok pattern list should show a "No patterns" message

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1082]
Right now there is an empty table when no patterns exist, but it should show a message like: "No patterns found."

![screen shot 2015-01-26 at 13 25 40](https://cloud.githubusercontent.com/assets/35022/5906646/f8301744-a55e-11e4-91f7-ab41b9dbde71.png)

**Comment by edmundoa** [comment]
Fixed on 893f36639e0f72857247c23d53587ad21b0b067e.
