### ISSUE TITLE
Nodes overview page is not showing message journal usage

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1083]
Was there a reason not to show the message journal usage on the nodes overview page? It was showing the cache utilization in earlier versions to indicate quickly if messages were queuing up or not and I think this was helpful to people.

![screen shot 2015-01-26 at 14 03 33](https://cloud.githubusercontent.com/assets/35022/5907413/6007112e-a564-11e4-91df-ac28f8eed4a4.png)

**Comment by kroepke** [comment]
The only reason was that the Chief UX Officer (me) did it over Christmas.
Let's add in 1.0.1?

**Comment by lennartkoopmann** [comment]
Makes sense! Set milestone to 1.0.1.

**Comment by bernd** [comment]
Fixed by #1146

**Comment by edmundoa** [comment]
The changes we made to fix this issue broke the journal information on the node page. Working on a fix for it.

**Comment by edmundoa** [comment]
The problem was that we were using the same CSS class for the DOM elements in the nodes overview page and node page, so the Javascript code was applying to both.

**Comment by bernd** [comment]
Ugh, thanks. Bad me for not testing this. :disappointed:

**Comment by edmundoa** [comment]
Was hard to catch, I was also reviewing it and didn't see it :confused:
