### ISSUE TITLE
Show maximum disk journal size

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1084]
We are showing the disk journal utilization but not the absolute maximum limit of it, which is an interesting metric/setting IMO.

**Comment by kroepke** [comment]
We are, in the text columns on the right. Might not be readable enough but
let's iterate on that in 1.0.1?

**Comment by lennartkoopmann** [comment]
Ah, there it is! I was playing around with it and can propose something in a second.

Thanks!

**Comment by lennartkoopmann** [comment]
Moved it all around a bit and added delimiters for easier reading.

![Uploading Screen Shot 2015-01-26 at 14.28.53.png . . .]()

**Comment by lennartkoopmann** [comment]
Re-open if you don't agree. :) Committed code and closing issue to avoid an open ticket and a dirty index on my machine.

**Comment by kroepke** [comment]
lgtm thanks!

**Comment by lennartkoopmann** [comment]
:+1: thx
