### ISSUE TITLE
Normalize non-primary indice data.

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-web-interface#1086]
Hi,

I'm using 1.0.0-beta.3.
Primary indice numbers are nice, but other indice numbers are not very well readable (no comma separation, no time units).

![indices](https://cloud.githubusercontent.com/assets/1915618/5916284/3bbf4674-a618-11e4-839d-9942d713e339.png)

**Comment by bernd** [comment]
Thanks for the report!
