### ISSUE TITLE
Selecting the current page in the pagination list results in "invalid range type" error

### ISSUE THREAD

**Issue by alias454** [Graylog2/graylog2-web-interface#1092]
After performing a search for anything that results in more than one page being returned, selecting the current page in the pagination list results in "invalid range type" error. It doesn't matter what page is selected, it only has to be the current page you are on 1,2,3....etc. 

graylog2-web: v0.92.4

**Comment by edmundoa** [comment]
Duplicated of #834, the issue will be fixed in 1.0.
