### ISSUE TITLE
Enlarge the input field for grok patterns

### ISSUE THREAD

**Issue by cmock** [Graylog2/graylog2-web-interface#1098]
The "Pattern:" field for grok patterns is short and therefore cumbersome to use for complex patterns. It should be a textarea.

**Comment by edmundoa** [comment]
After this change the create grok pattern text area is not cleared when the data is saved.

**Comment by edmundoa** [comment]
888b2a3505fae043b3f53756670add81fbcb267e fixes the latter problem.
