### ISSUE TITLE
Repeated editing of grok pattern requires page reload

### ISSUE THREAD

**Issue by cmock** [Graylog2/graylog2-web-interface#1099]
To reproduce:

1. go to the "Grok Patterns" page
2. edit a pattern, save
3. edit the same pattern again

What happens is that the "Edit Grok Pattern" dialog is now empty, both the "Name" and "Pattern" fields. After reloading the page, editing works again as expected.

**Comment by edmundoa** [comment]
Hi,

Thank you for reporting this.

Which Graylog version are you using?

**Comment by kroepke** [comment]
Must be a 1.0 version, it could be a reload problem or my perfect
JavaScript style.

**Comment by edmundoa** [comment]
This was actually me trying to be smart, will take care of it.

**Comment by cmock** [comment]
I'm running 1.0.0-8.rc.1from the Debian packages. 

Sorry, don't know how I managed to forget that info.

**Comment by edmundoa** [comment]
Thank you for the information @cmock! The issue should be fixed on RC2.
