### ISSUE TITLE
/system/indicies We expected HTTP 200, but got a HTTP 200

### ISSUE THREAD

**Issue by reighnman** [Graylog2/graylog2-web-interface#1100]
Upgraded from 0.92.4-1 to 1.0.0-9.rc.2 via repo (CentOS).  Everything went smooth except when I try to view /system/indicies

 (You caused a org.graylog2.restclient.lib.APIException. API call failed GET http://@10.244.95.121:12900/system/deflector/config returned 200 OK body: {"type":"size","max_number_of_indices":25,"max_size_per_index":17179869184})

Reason: Could not get indices. We expected HTTP 200, but got a HTTP 200.

Stacktrace: http://pastebin.com/mU9FdyE6

server.conf: http://pastebin.com/aFwqAVSF

**Comment by edmundoa** [comment]
Hello,

Thank you for reporting this issue!

The problem here is that we are using an int to store `max_size_per_index`, but the value you use is too big to fit there. As a workaround until we fix it, you may want to reduce the maximum size to a number below 2147483647.

**Comment by edmundoa** [comment]
This issue was fixed on https://github.com/Graylog2/graylog2-server/commit/0300c7769438375aa9f8a8692d18226623171dd9
