### ISSUE TITLE
Some metrics for inputs are missing

### ISSUE THREAD

**Issue by cmock** [Graylog2/graylog2-web-interface#1106]
Running 1.0.0-10.rc.3 from the Debian packages.

On the metrics page for the Syslog and GELF/UDP inputs (those are all that I use), some metrics that were correctly reported in 0.92 are now at zero:

* parseTime
* processedMessages

In addition, "rawSize" has the wrong units ("events" instead of "bytes")

"written_bytes_1sec" and "written_bytes" are also at zero, but I'm not sure what they mean on an input anyways...

**Comment by kroepke** [comment]
Some metrics have not been broken down to a codec level, that is true, we'll see if we can fix this easily.

The "events" vs "bytes" is simply because the underlying library has no idea about units, it simply counts things.

**Comment by kroepke** [comment]
let's try to get a quick fix in for 1.0.1

**Comment by kroepke** [comment]
we'll need to reorganize the metric names/hierarchy going forward, it's a pain right now to find related metrics easily
