### ISSUE TITLE
/system/nodes wording issue ?

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-web-interface#1112]
/system/nodes contains the following statement : 

" ... It is important to keep in mind that incoming messages (except those from inputs that support rejecting messages, like AMQP) are buffered in memory. This means that they will be lost if you stop or restart the server until they are processed or you run out of memory ... "

This is no longer true in 1.0 and thus should be corrected.

**Comment by kroepke** [comment]
Makes sense, thanks!
