### ISSUE TITLE
Allow formatting characters like tab or /n etc.

### ISSUE THREAD

**Issue by cybermedi** [Graylog2/graylog2-web-interface#1121]
Hi,
I use graylog2 as final logging system. We also log very long messages from Java applications. Because of lack support of multiline messages we escape the formatting characters. When the message is received by graylog2 we do change back by drools. 
Message is correctly displayed in right column when you drill in to each line. But is is not correctly formatted in main "column/stream". We do patch of appropriate JAR but it is not very nice solution :-)
1) I would like to ask you to if there is way how to respect the formatting characters?
2) I would like to have possibility to change order of columns,their size and possibility to store it like view. When you work with very long messages and you also switch on another two columns all of them have same size even they display very short message (like application name...)

**Comment by giko** [comment]
+1

**Comment by DFM86** [comment]
+1

**Comment by konsoletyper** [comment]
Agree. Also, messages displayed as links (which apply pattern to the filter), which may be not very comfortable. Messages often contain useful data which I used to copy-paste. Quick application to the filter is quite comfortable for fields like `logger`, `level`, etc, but there is absolutely no use in this feature for `message` and `full_message` fields.

**Comment by rumatoest** [comment]
Agree. In Graylog 1.1 full_message visualization is awful - no tabs, no newlines, no proper wraps. It was much better in graylog-web 1.0

**Comment by edmundoa** [comment]
We have been working on multi-line messages wrap for 1.1.2, so hopefully this will be much better really soon.

I'm closing this issue, as it looks the same as #612. Please reopen if you think I'm wrong.
