### ISSUE TITLE
Input stats are not updated after being paused

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-web-interface#1122]
When an input running on a radio node is paused and started again, the traffic statistics are not updated anymore. Still not sure if it's an issue on the web-interface or server, so I'm adding it here. 

![input_stats](https://cloud.githubusercontent.com/assets/716185/6173715/27369b7e-b2ea-11e4-927c-dcd035d023d9.gif)

**Comment by bernd** [comment]
Fixed by Graylog2/graylog2-server#1045

**Comment by edmundoa** [comment]
![qpngu](https://cloud.githubusercontent.com/assets/716185/6527903/b661d7b0-c41e-11e4-983f-496f131b7c1d.gif)
