### ISSUE TITLE
Graylog2 UI is not rendering properly in Internet Explorer.

### ISSUE THREAD

**Issue by shivakhuba** [Graylog2/graylog2-web-interface#1130]
Hi All,

Graylog2 UI is not rendering properly in internet explorer.

please find the below screen shot.

![image](https://cloud.githubusercontent.com/assets/10917913/6242681/de7a3d72-b759-11e4-83fc-f5b953aa8580.png)

kindly request you to tell me solution ASAP.

Regards,
Shiva

**Comment by edmundoa** [comment]
Hi,

Which IE and Windows version do you use? The web interface should work with IE9 or higher.

**Comment by edmundoa** [comment]
Please also ensure that Graylog is not added into IE's Compatibility View.

**Comment by shivakhuba** [comment]
I am using IE 11.0.15 and windows 8.1.
I have not added it in IE's Compatibility view.
When I change Document mode emulated to 9 or 10, then it will work. But, its very slow.

**Comment by edmundoa** [comment]
That is really weird. We usually test the site on Windows 7, also using IE 11 (testing with different document modes as well). I am going to try to reproduce the issue on Windows 8.1, but I would be really surprised that so many things break just for that reason.

By the way, which Graylog version are you using?

**Comment by shivakhuba** [comment]
I am using version graylog-web-interface-1.0.0-rc.2.

**Comment by edmundoa** [comment]
I just tried to reproduce this on a VM running Windows 8.1, IE 11, and all available updates installed, but Graylog web interface loads and seems to work fine. I have seen a couple of settings that may be causing the issue.

#### Security options
Please ensure that your security options are not set in "high" level. These are the settings I used while testing:
![security_options](https://cloud.githubusercontent.com/assets/716185/6248563/3864c15a-b781-11e4-9be0-c914a395c44c.png)

#### Compatibility view
There is a check-box on the compatibility view preferences that makes IE to load all intranet sites in compatibility mode. It didn't make any difference in my case, but it could be activating the compatibility mode in your case, which could be producing the issue.

**Comment by edmundoa** [comment]
Hi @shivakhuba, any news on this?

**Comment by edmundoa** [comment]
Closing the issue, as there are no news about it. Please reopen if needed.
