### ISSUE TITLE
Editing a paused input restarts it

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1131]
Version 1.0.0
Steps to reproduce:
- create random input
- pause input
- edit input/ change title

Paused input is running again but should not.

**Comment by joschi** [comment]
Related to Graylog2/graylog2-server#967

**Comment by kroepke** [comment]
This needs too much change for a bugfix release.

**Comment by kroepke** [comment]
duplicated by https://github.com/Graylog2/graylog2-server/issues/1070

**Comment by kroepke** [comment]
Leaving out of 1.1.0 for now.

**Comment by bernd** [comment]
Same problem as in https://github.com/Graylog2/graylog2-server/issues/967.

Closing this one.
