### ISSUE TITLE
Displayed field order of plugin does not match added order in ConfigurationRequest object

### ISSUE THREAD

**Issue by dfch** [Graylog2/graylog2-web-interface#1135]
When defining fields in for plugin via the  ```getRequestedConfiguration()``` method, the field order on the ```ConfigurationRequest``` is not preserved whrn shown on the UI.

Example: while in this [ConfigurationRequest](https://github.com/dfch/biz.dfch.j.graylog.plugin.alarm.clickatell/blob/7c623213ea6c0f27d9516a3fc22c4cf6e7b65346/src/main/java/biz/dfch/j/graylog/plugin/alarm/dfchBizClickatellAlarm.java#L133) the first field added is the ```CONFIG_AUTH_TOKEN```, the first field displayed on the UI is actually ```CONFIG_FIELDS``` as you can see in the screenshot below.

This is somehow annoying as the available fields on s plugin can not visually grouped together for logically corresponding settings.

![Installed Plugin](https://dfch.files.wordpress.com/2015/02/graylogclickatellalarm2.png)

**Comment by bernd** [comment]
This has been fixed in #1285. Closing this issue. Please re-open if you still have issues. Thank you!

**Comment by dfch** [comment]
thanks for fixing that!
