### ISSUE TITLE
Error messages for non-existing nodes

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1137]
Version 1.0.0

System/ Overview:

Node detail site for none existing nodes needs prettier error message.

**Comment by edmundoa** [comment]
I was doing some work on this in the morning, but I didn't assign the ticket to me for some reason :confused:. Anyway, I made a small change in the web interface to redirect to the node overview page when a node is not found, and show a flash message to the user.

**Comment by kroepke** [comment]
sounds good to me. my change merely changes the error code to something decent in the rest api.
