### ISSUE TITLE
Ldap test login always give Check ok!

### ISSUE THREAD

**Issue by andreaconsadori** [Graylog2/graylog2-web-interface#1138]
i try to insert in username and password fake users (not existent) and the test button always say "User check" and "login check" with green flag

**Comment by edmundoa** [comment]
Hi,

Thank you for reporting this issue. Which Graylog version are you using?

**Comment by andreaconsadori** [comment]
ver 1.0.0 (stable) - manual installation on debian 7 64bit



 


Date: Fri, 20 Feb 2015 08:33:45 -0800
