### ISSUE TITLE
More than 2 columns on Dasboards

### ISSUE THREAD

**Issue by mrfreezer** [Graylog2/graylog2-web-interface#1139]
Hi!

Call me blind but i can not find any way to put a third or even fourth column on a dashboard. Because on a full-hd screen 4 columns would fit the screen quite easy.

i think i somewhere saw a screenshot from lennartkoopman oder kroepke which showed  3 colums but i am not sure. 

any ideas on this?

ingo

**Comment by razvanphp** [comment]
Click on the lock icon in the right upper corner "Unlock widget position" and then you can drag them.

**Comment by mrfreezer** [comment]
yes, thanks for the advice. i can drag them as much as i like but that does not give me a third or fourth column. :(

**Comment by razvanphp** [comment]
Well, it works for me, at least in Firefox. I'm using the latest 1.0 stable version.

**Comment by edmundoa** [comment]
Closing the issue, as it seems to be fixed.
