### ISSUE TITLE
Dashboard does not save widget positions after repositioning

### ISSUE THREAD

**Issue by mrfreezer** [Graylog2/graylog2-web-interface#1141]
i suppose its because of the number of widgets i got on that dashboard.

i put 1 graph on top which shows the 7 day totals plus 10 numerical widgets which show the usage per client (9 + 1 for the test-environment, which in fact is another machine and therefore uses a slightly different search string)

first, i think it was when i had around 8 numerical display, it was fine and i was able to toss 'em around like i wanted and they stayed that way. then i got word about 2 other clients which i obviously missed while creating the widgets (ok, not missed them, they just werent clients back then ^^) 

so i added them and from then on i am not able to save the layout anymore (or rather graylog does not remember it anymore) - i am still able to sort them like i want but it gets a little annoying to rearrange them every time you restart the dashboard after some time.

if any developer wants to take a look into this and needs more input, dumps of any kind or whatever needed, i would be more than happy to provide. 

and if anybody could reproduce this i (and them too, i am sure) would like to hear about it.

ingo

**Comment by edmundoa** [comment]
Closing the issue, as it duplicates #873

**Comment by mrfreezer** [comment]
ok, that one must have slipped my recognition :( guess i got to quit and head for bed
