### ISSUE TITLE
Need to be able to include information from message in email alert

### ISSUE THREAD

**Issue by tpedaste** [Graylog2/graylog2-web-interface#1142]
I find that alters aren't that usefull if can can't include information from the message(s) that cause the alter in the email altert

**Comment by edmundoa** [comment]
Hi,

What kind of information do you miss? You can customize the alert condition and email template to add some extra information, but it's hard to tell if you don't say what you want to achieve.

**Comment by tpedaste** [comment]
Basically I want to use information from the message that triggered the 
alert in the alert.

Being able to include the message in the body of the email would help,  
being able to include fields the were extracted from message would be 
even better.


On 03/03/15 18:24, Edmundo Alvarez wrote:
>
> Hi,
>
> What kind of information do you miss? You can customize the alert 
> condition and email template to add some extra information, but it's 
> hard to tell if you don't say what you want to achieve.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Graylog2/graylog2-web-interface/issues/1142#issuecomment-76920803>.
>

-- 
*Toivo Pedaste │ Network Team (Infrastructure & Applications)*
Business Information & Technology Services, M463
The University of Western Australia
35 Stirling Highway, CRAWLEY WA 6009
Tel +61 8 6488 2605 l e-mailtoivo.pedaste@uwa.edu.au 
<mailto:goran.mitrovic@uwa.edu.au>
UWA CRICOS Provider No. 00126G

**Comment by edmundoa** [comment]
In the alert condition, you can specify a certain number of messages to be included in the alert callback. You can do it by setting the amount of messages you want in "When sending an alert, include the last X messages of the stream evaluated for this alert condition".

The string representation used in the default email template already shows almost all message fields, but you can play around with the message in the email template to show a single field that you may be interested in.

If you need more help with the email template or configuring the alert condition, please write to our mailing list or IRC (https://www.graylog.org/community-support/), as Github issues are mainly used for bugs and feature requests.
