### ISSUE TITLE
Stream Alerts with custom conditions

### ISSUE THREAD

**Issue by razvanphp** [Graylog2/graylog2-web-interface#1144]
Hi,

This might be a feature request, so I'm not sure if it belongs to the web interface or the server, feel free to move it if necessary.

In our graylog v1.0 setup we use email alerts, and something really useful for us is missing or we don't know how to do, and that is, alerts based on conditions.

To explain the environment, we have multiple teams (about 8) and each team has more or less few streams, divided in environments: live, staging, dev. In the live stream, we collect for example both HTTP logs and PHP info and errors, since they are strongly connected. 

Setting up an alert for live stream does not work out of the box, because increased number of messages would not necessarily mean an error, just increased traffic. Our current workaround is to have a separate error stream that triggers the error. This cannot be used practically, because if each team creates so many streams, we will be lost in finding the one we need on the page.

For example, I would like to have something like message count condition only for response_code:500 OR level:<4.

Thank you for your great work!

Cheers from Hamburg

**Comment by edmundoa** [comment]
Hi,

Thank you for the feature request. I think this is basically the same as #939, so I'm closing the issue. Please reopen if you think otherwise.
