### ISSUE TITLE
Handle update notifications differently

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-web-interface#1147]
It is important to let current users know there is an update on Graylog, but at the moment we display it in the same way as other "more important" notifications, which sometimes may be confusing and annoying.

We should find some balance on it, maybe not showing the notification badge for the update notification, or do it with a different frequency.

**Comment by adnan-panalytics** [comment]
Till the time this issue is resolved, is there any way to disable notifications? (Especially the graylog is outdated notification, as it is quite annoying every day to deal with it when there are more important notifications which need attention)

**Comment by joschi** [comment]
@adnan-panalytics No, notifications cannot be disabled.

**Comment by cygnusb** [comment]
This is really annoying. In production we do not want to update to every new version. In other software a config option is quite common to disable such notifications. It would be nice to have such an option in graylog.

**Comment by joschi** [comment]
@cygnusb You can disable the version check itself by adding the following setting to your Graylog server configuration:
```
versionchecks = false
```

**Comment by florianpopp** [comment]
Closing this, as the version check can be disabled in the configuration, as @joschi pointed out.

**Comment by flottefar** [comment]
Hi @joschi ,

Is it enough to just add:

versionchecks = false

in the "server.conf" file and restart the server service?

**Comment by joschi** [comment]
@techallan If you want to disable the version checks completely (not recommended), that's the way to go.

**Comment by Henriquezla** [comment]
Hello guys.  I know this is an old topic but didn't get info elsewhere.  I tried what @joschi suggested above but it doesn't work.  I still getting new version notifications.  Any clues?

**Comment by joschi** [comment]
@Henriquezla 
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
