### ISSUE TITLE
Any way we can add a robots.txt to avoid Graylog instances getting indexed on Google?

### ISSUE THREAD

**Issue by neilferreira** [Graylog2/graylog2-web-interface#1151]
As the title suggests, is there any way we can do this?  I'm running Graylog on port 80 on my server.  I guess I could switch to using another port or putting it behind a reverse proxy that serves up a robots.txt, but that seems like overkill!

**Comment by joschi** [comment]
It's not possible to add a `robots.txt` retroactively in an existing graylog-web-interface release, but a default will be included in the next releases.

**Comment by joschi** [comment]
By the way, you probably shouldn't expose your Graylog web interface to the Internet at all or without an encrypted transport (HTTPS).
