### ISSUE TITLE
Cannot save search if result is empty

### ISSUE THREAD

**Issue by sleske** [Graylog2/graylog2-web-interface#1158]
On the search result page for a stream, the button "Save search" is only shown if results were found.

However, it sometimes makes sense to save a search even if it has no results - it might receive results later.
"Save search" should always be available, no matter whether there are results or not.

**Comment by sleske** [comment]
And incidentally:

The other buttons above the search probably also should not disappear when search results are empty.

Normally, the search result page for a stream shows four buttons at the top:
The "bug" (show query), "Export", "Stream", "Save search".

However, if a search shows no results, only the "bug" is shown, and only as a small symbol instead of a button. This is rather confusing (I initially mixed up the tiny bug icon with the "dashboard" icons used in the next line). I see no reason to hide the buttons, and for UI consistency it would be better to always show them.

The only button that is not useful for an empty result is "Export". Still, it would probably make more sense to disable it instead of hiding it, to maintain the UI layout and positions of buttons.

Should I file this as a separate issue?

**Comment by kroepke** [comment]
Thanks for the report, no need to file it as a separate issue, we'll notice
when addressing the first problem.

Best,
Kay

**Comment by manishjhawar** [comment]
+1 for both the save-search and other buttons

**Comment by sheavner** [comment]
+1 for save empty search

**Comment by evitorbarros** [comment]
+1 for save empty search

**Comment by edmundoa** [comment]
Related to #1639

**Comment by edmundoa** [comment]
Fixed in https://github.com/Graylog2/graylog2-server/pull/2253
