### ISSUE TITLE
no lock/unlock new dashboard

### ISSUE THREAD

**Issue by marcmoennikes** [Graylog2/graylog2-web-interface#1162]
![graylog - te_2015-03-11_23-11-09](https://cloud.githubusercontent.com/assets/11431454/6608044/240cd98a-c844-11e4-9001-e75cd5654103.jpg)
Hello,

i can not find the "lock symbol on the top right" on a new dashboard (installed ova virtual machine today). Created a new dashboard. See screenshot.

Regards

**Comment by edmundoa** [comment]
Hi,

In order to see the lock/unlock dashboard button you need to add some widgets first. Please reopen the issue if you still find the problem after adding some widgets.

Regards.
