### ISSUE TITLE
Input state does not change from "starting" to "running"

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1163]
When launching a syslog udp input with `graylog-web-interface-1.0.2-SNAPSHOT-20150313113959.tgz`the input state is "starting" even though the throughput counter is already working. After reloading the site the state is "running" It would make more sense that the state updates automatically.

**Comment by florianvolle** [comment]
Also when being in the "started" state and using the start button the input fails but when refreshing the site it is in the "running" state. A users expectation would be to press the start button to start the input and not refresh the site

**Comment by kroepke** [comment]
The badge is not being updated automatically, I think we won't address this in 1.1, so I'll leave it outside this milestone.

**Comment by bernd** [comment]
Fixed in Graylog 2.0.
