### ISSUE TITLE
Make "Hide sidebar" functionality work again

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1167]
During the restructuring of the sidebar the "Hide sidebar" functionality broke and has not been re-implemented yet.

Now that the sidebar no longer needs to scroll down with the rest of the page this has even more value because after scrolling down you have a lot of space on the left that is not used.

**Comment by kroepke** [comment]
The sidebar is scrolling now, and we will not add the option of hiding for now.

The menu is always accessible via the menubar now.
