### ISSUE TITLE
"Show message terms" in a search is broken

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1168]
I am using `graylog-web-interface-1.0.2-SNAPSHOT-20150313113959.tgz`

When opening a message detail view in a search and going to the action dropdown menu "show message terms" is not working correctly. Instead of highlighting the message terms and darkening the background, everything darkens.

![bildschirmfoto 2015-03-16 um 14 49 27](https://cloud.githubusercontent.com/assets/6331205/6667416/198a14e0-cbec-11e4-9929-03da6641f0c1.png)

**Comment by florianvolle** [comment]
also see https://github.com/Graylog2/graylog2-web-interface/issues/1211

**Comment by edmundoa** [comment]
Fixed on 94acdc7
