### ISSUE TITLE
Stream Alert creation form allows negative values

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-web-interface#1169]
![minusminusminus](https://cloud.githubusercontent.com/assets/41929/6684355/bc1bccc2-cc90-11e4-96fb-f0d72dabc5ad.gif)

**Comment by kroepke** [comment]
my last commit referenced the wrong issue

**Comment by edmundoa** [comment]
It looks like you are using Safari, and it doesn't check HTML5 form constrains by default. This issue relies on this to be fixed: https://github.com/Graylog2/graylog2-web-interface/issues/1248
