### ISSUE TITLE
Graylog- not able to see client server name and logs inside graylog web interface.

### ISSUE THREAD

**Issue by nrdate** [Graylog2/graylog2-web-interface#1170]
Hi ,

I have configured graylog with 4 local server as client .
Everything is fine but I am not able to see system list in graylog web interface.
Please assist.

**Comment by joschi** [comment]
What exactly do you mean with "system list"?

**Comment by nrdate** [comment]
It means when I configure rsyslog in local server , I should see this server name and logs in "Sources" tab in graylog web interface.

**Comment by joschi** [comment]
Kindly use our [mailing list](https://groups.google.com/forum/#!forum/graylog2) or our IRC channel [#graylog2 on Freenode](https://webchat.freenode.net/?channels=%23graylog2) for general support questions.

The GitHub issues should only be used for bug reports and feature requests.
