### ISSUE TITLE
Dashboards should have unique names

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-web-interface#1172]
On the current master it is possible to create several dashboards with the same name. Those dashboards work just fine, but it's confusing.

**Comment by reighnman** [comment]
+1

**Comment by pdepaepe** [comment]
Please don't. This is an "admin" problem, should not be a user one.

**Comment by florianvolle** [comment]
It also happens for streams.

**Comment by florianpopp** [comment]
Closing because we are not planing to adress this.
