### ISSUE TITLE
Make journal usage update automatically on nodes overview page

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1173]
The count in *34 unprocessed messages are currently in the journal* is not automatically and periodically updating, while other numbers are. This is confusing because you really expect it to do so and now it looks like the number is not changing.

**Comment by kroepke** [comment]
This also applies to the node detail page.

**Comment by kroepke** [comment]
@florianvolle the System/Nodes detail page, showing the information for a single node, can already be tested.
The journal section now updates in real time alongside with the JVM heap information.
You need both server and web interface snapshots from today around/after lunch time.

Still working on the throughput numbers on that page, as well as the overview pages, will update here once those are done.

**Comment by kroepke** [comment]
@florianvolle please verify and reopen if necessary

**Comment by florianvolle** [comment]
Works as well in overview as in details.
