### ISSUE TITLE
Dashboards not loading metrics

### ISSUE THREAD

**Issue by csm** [Graylog2/graylog2-web-interface#1174]
We currently have a fairly large firehose (probably around 6 or 7 million messages per hour) of messages going into graylog in AWS; our setup is:

* 6 elasticsearch nodes, m3.large.
* 2 graylog server nodes (version 1.0.0), c3.xlarge.
* 1 graylog web node (version 1.0.0), m3.large.

Our dashboards don't load well any more:

![graylog-dash](https://cloud.githubusercontent.com/assets/39441/6743463/6beee8b0-ce57-11e4-9abd-410a11341a59.png)

According to metrics for the widgets, computations are taking upwards of 25 seconds to complete.

Is there any way to improve this? Which axis would we need to grow? Elasticsearch nodes? Elasticsearch shards? Graylog nodes?

**Comment by edmundoa** [comment]
Hi,

Without more information it is hard to tell, but most likely the bottleneck is in Elasticsearch, specially if the queries you use on the widgets are a bit complex.

I don't see any obvious bug on our side here, so I kindly ask you to write this question to our [mailing list](https://groups.google.com/forum/#!forum/graylog2) or [IRC channel](https://webchat.freenode.net/?channels=%23graylog2), as they are better channels for support.
