### ISSUE TITLE
Empty dashboards no longer show lock/unlock buttons

### ISSUE THREAD

**Issue by serenabiodec** [Graylog2/graylog2-web-interface#1176]
I am experiencing an (apparently) old issue: the lock/unlock widgets are hidden in empty dashboards.

I am running graylog2 version 1.0 on wheezy.
(https://packages.graylog2.org/repo/packages/graylog-1.0-repository-debian7_latest.deb)

**Comment by edmundoa** [comment]
Hi,

It is not an old issue, the lock/unlock widget doesn't make sense when the dashboard is empty, as you can only add widgets by doing searches. That's why it is not visible until you add some widgets to the dashboard.

**Comment by edmundoa** [comment]
Please refer to the [mailing list](https://groups.google.com/forum/#!forum/graylog2) or the [IRC channel](https://webchat.freenode.net/?channels=%23graylog2) if you still have questions about it.
