### ISSUE TITLE
User permission is broken

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1180]
Using `graylog-web-interface-1.1.0-SNAPSHOT-20150323175628.tgz`changes in user permission do not get stored. Hence, any User is able to see all streams, dashboards etc.

**Comment by florianvolle** [comment]
Seems to work now, but please verify that all permissions work.

**Comment by edmundoa** [comment]
This was fixed on https://github.com/Graylog2/graylog2-web-interface/commit/97d7976e1a20062d52f4d75dcac909c9f34efa8c
