### ISSUE TITLE
Nodes page is broken

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1182]
Using `graylog-web-interface-1.1.0-SNAPSHOT-20150323175628.tgz` the Nodes page is not working correctly. 

* totally processed messages are only updating in overview, not when clicking on the node
* heap space information is only updating in overview, not when clicking on the node
* messages in journal are only updated in overview, not when clicking on the node
* processed messages per node are only updated in overview, not when clicking on the node
* message processing can not be paused and resumed in overview, but when clicking on the node
* shutdown from node actions menu is not working

**Comment by kroepke** [comment]
@florianvolle please retest this one, i think all of the issues should be adressed in latest snapshots.

**Comment by florianvolle** [comment]
works!
