### ISSUE TITLE
Missing output plugin breaks Output listing

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-web-interface#1185]
Steps to reproduce:
1. Load external plugin supplying output type
2. Create output using this output type
3. Unload plugin
4. Go to System/Outputs in Web Interface

Expected Result:
Listing of configured outputs

Actual Result:
500 due to NPE

What is happening here is that displaying the configuration of an output requires the requested configuration of that output type to be requested from the server. This returns a list of required configurations which lacks that of the configured output type.

**Comment by dennisoelkers** [comment]
With the current version the output listing does not break anymore, but there is no indication the plugin is not loaded.

**Comment by joschi** [comment]
This behavior is now at least consistent with inputs or alarm callbacks being contributed by plugins.

We should decide how we want to handle these cases (hide components with non-existing backend or simply hide them and print a warning in the Graylog server logs) and implement that in a later version.

**Comment by dennisoelkers** [comment]
I think hiding is the worst option. We should display them in the web if with a hint that the plugin is not loading and the entity's functionality is limited, but give the option to delete them.
