### ISSUE TITLE
UI for disconnected page

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1189]
The page you see when the web interface could not reach any graylog-server node is not really styled yet after the Bootstrap 3 migration. This is a reminder ticket because that functionality can easily be forgotten.

@florianvolle Can you make sure that testing the "disconnected" page is part of the QA checks before a release?

**Comment by kroepke** [comment]
@florianvolle This is the page you get when you stop the graylog server. If the test plan doesn't have it yet, there are two modes to be tested:
1) start web interface without a server running
2) stop the server after the web interface has connected (e.g. a user logged in before)

The difference is in the right hand column about the "discovered nodes". First case: it should display a warning, second case it should display a list of nodes and some times.

**Comment by kroepke** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/52014/7202331/a7a820b2-e511-11e4-811a-05e1ed5fc219.png)

**Comment by florianvolle** [comment]
Added it to the pre-release checklist
