### ISSUE TITLE
Regular expression test fails when example message is a JSON document

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-web-interface#1190]
On 1.0.1, testing a regular expression condition in the extractor form fails when the example message is a JSON document. The thrown exception in the log file is `Illegal character in query`.

**Comment by astral303** [comment]
Hitting this right now. Makes it difficult to diagnose extractors in MongoDB that involve slow queries, since these include JSON snippets of queries.

**Comment by astral303** [comment]
Is there a short-term workaround?

**Comment by edmundoa** [comment]
The problem also occurs when trying to test almost any extractor, as we are not escaping the example properly.
