### ISSUE TITLE
Graylog web interface time incorrect

### ISSUE THREAD

**Issue by shaman478** [Graylog2/graylog2-web-interface#1197]
Hello, 

we are using Graylog server and web interface 1.01 version, we found the timestamp was incorrect on web interface,following is  our configuration, we want to change the web interface timezone to UTC+8,  only change the timezone to "PRC" is ok or not?

Web interface timestamp:
![1](https://cloud.githubusercontent.com/assets/9427526/7020752/23f21e14-dd4e-11e4-9265-c948b968c406.jpg)

![2](https://cloud.githubusercontent.com/assets/9427526/7020771/48d58630-dd4e-11e4-8449-2964bdba4d67.jpg)

![3](https://cloud.githubusercontent.com/assets/9427526/7020775/53b8ef24-dd4e-11e4-816c-cb8dd5c9664d.jpg)

**Comment by joschi** [comment]
You can change the timezone for a user on the System -> Users page in the web interface.

Also kindly use our [mailing list](https://groups.google.com/forum/#!forum/graylog2) or the [#graylog IRC channel on Freenode](https://webchat.freenode.net/?channels=%23graylog) for general support questions.

**Comment by ajpen** [comment]
How do you change the timezone for the web interface configuration?

**Comment by joschi** [comment]
@ajpen Take a look at the `timezone` configuration setting in the configuration file of the Graylog web interface: https://github.com/Graylog2/graylog2-web-interface/blob/1.3.3/misc/graylog-web-interface.conf.example#L14-L17

**Comment by slitmengheang** [comment]
Hi Joschi,

Could you guide me a bit how to change timezone in graylog server via command?

i am not sure to do it clear

Thanks
