### ISSUE TITLE
Dashboard Kiosk

### ISSUE THREAD

**Issue by dennusb** [Graylog2/graylog2-web-interface#1199]
Hi,

We want to run a Graylog Dashboard on a Raspberry PI in Kiosk mode. But how can i get pass the login screen? Can i add a filter for certain IP's or something?

**Comment by edmundoa** [comment]
Hi,

The easiest way to achieve something like that, would be to use a reader user with access to the dashboard you want. You could set the default startpage to that user to the dashboard and also change the session timeout to something that fits to that use.

As this is not a bug, I kindly ask you to refer your questions to the [mailing list](https://groups.google.com/forum/#!forum/graylog2) or the [IRC channel](https://webchat.freenode.net/?channels=%23graylog2).
