### ISSUE TITLE
Feature Request - Leading/Trailing Messages

### ISSUE THREAD

**Issue by fwdchrisull** [Graylog2/graylog2-web-interface#1202]
Often times it is useful to see X number of messages before and/or after the message you have searched for.  Something similar appears to be implemented on the alert functionality but not for searching within streams.  I'm looking for something to similar to performing a "grep -B" when searching. 

I would suggest adding a search parameter that allows for returning X number of entries before and/or after a matching entry.  That might be too resource intensive with this architecture, so another way to implement this might be to perform a normal search and then add a button the user could click to return surrounding entries for that one message they are interested in.

Thanks.

**Comment by edmundoa** [comment]
Hi,

This is already requested, so I'm closing the issue. Please take a look at this issue: https://github.com/Graylog2/graylog2-web-interface/issues/150
