### ISSUE TITLE
Message throughput is not working

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1207]
I am using `graylog-web-interface-1.1.0-SNAPSHOT-20150410081637.tgz`

When starting an input the message throughput is not working and just shows the message "loading througput"

**Comment by kroepke** [comment]
Yep, also seeing problems with it right now :/

**Comment by kroepke** [comment]
This seems to be happening when a user session has timed out.
Fixing https://github.com/Graylog2/graylog2-web-interface/issues/1205 should also fix this one.

**Comment by florianvolle** [comment]
@kroepke I guess this can be closed then?

**Comment by kroepke** [comment]
fixed by #1205
