### ISSUE TITLE
Make error messages consistent 

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1210]
Using `graylog-web-interface-1.0.2-SNAPSHOT-20150402161036.tgz`

When applying `Statistics` or `Generate Charts` to on a non-numerical field the error messages are not consistent. 

![statistics](https://cloud.githubusercontent.com/assets/6331205/7137783/59efb0c6-e2bc-11e4-92ed-ab6008ef83b6.png)

![generate chart](https://cloud.githubusercontent.com/assets/6331205/7137788/6065835e-e2bc-11e4-9e0b-fd88cfe9c89c.png)

**Comment by edmundoa** [comment]
Fixed on eda865c
