### ISSUE TITLE
Indices in search are broken

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1211]
Using `graylog-web-interface-1.0.2-SNAPSHOT-20150402161036.tgz`

When opening an index in a searchs sidebar it does not open correctly. Instead of highlighting the used indices and darkening the background, everything darkens.

![indices](https://cloud.githubusercontent.com/assets/6331205/7137974/9477b6c0-e2bd-11e4-8621-6b7922faf852.png)

**Comment by florianvolle** [comment]
Also see https://github.com/Graylog2/graylog2-web-interface/issues/1168

**Comment by edmundoa** [comment]
Fixed on 94acdc7
