### ISSUE TITLE
Histogram does not show with saved searches

### ISSUE THREAD

**Issue by val123456** [Graylog2/graylog2-web-interface#1216]
Using Chrome/Firefox on OS X 10.10, or IE 11/Chrome on Windows 7:

Selecting a saved search leaves the histogram blank.  Reloading on Chrome (CMD/CTRL-R) does not change the behavior, but clicking the search button after loading the saved search will result in histogram being populated.  

It works as expected in Safari. 

Config details:

1.  Installed using setup wizard on 17 April (Ubuntu 14.04)
2.  graylog-web-interface v1.0.0 (Oracle Corporation 1.8.0_45 / Linux 3.16.0-34-generic)

**Comment by edmundoa** [comment]
Hi,

We have reworked the search results page on 1.1 (currently in RC) and hopefully this is fixed now. Could you please give it a try? Please reopen if this is still an issue.
