### ISSUE TITLE
Time range selection for search is broken 

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1219]
Just a reminder ;)

![bildschirmfoto 2015-04-23 um 12 14 27](https://cloud.githubusercontent.com/assets/6331205/7295038/cf05925c-e9b2-11e4-9437-3cbf934ffd9c.png)

![bildschirmfoto 2015-04-23 um 12 14 16](https://cloud.githubusercontent.com/assets/6331205/7295045/d748ea5e-e9b2-11e4-91e6-5ca222621012.png)

**Comment by kroepke** [comment]
work in progress on v2 search

**Comment by bernd** [comment]
Looks fixed to me now. Closing.
