### ISSUE TITLE
Unable to create extractor on input

### ISSUE THREAD

**Issue by mattwilmott** [Graylog2/graylog2-web-interface#1223]
We've tried POSTing the following JSON inputs for `/system/inputs/<input_id>/extractors`
```
{
      "target_field": "ssh_fail_username",
      "source_field": "message",
      "converters": {"type":"lowercase", 
                     "config":{}
      },
      "extractor_type": "regex",
      "condition_value": "Failed password for .+ from .+",
      "title": "sshd failed password username",
      "order": 0,
      "extractor_config": {"regex_value":"Failed password for (.+) from"},
      "condition_type": "regex",
      "cut_or_copy": "copy"
    }
```
AND
```
{
      "target_field": "ssh_fail_username",
      "source_field": "message",
      "converters": [{"type":"lowercase", 
                     "config":{}
      }],
      "extractor_type": "regex",
      "condition_value": "Failed password for .+ from .+",
      "title": "sshd failed password username",
      "order": 0,
      "extractor_config": {"regex_value":"Failed password for (.+) from"},
      "condition_type": "regex",
      "cut_or_copy": "copy"
    }
```
each time we get something similar to either

"message": "Can not instantiate value of type [map type; class java.util.LinkedHashMap, [simple type, class java.lang.String] -> [simple type, class java.lang.Object]] from String value ('lowercase'); no single-String constructor/factory method\n at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@48d69ad7; line: 4, column: 22] (through reference chain: java.util.LinkedHashMap[\"type\"])"

or 

"message": "Can not deserialize instance of java.util.LinkedHashMap out of START_ARRAY token\n at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@6da85caa; line: 3, column: 32]"

Similarly if we create an extractor without a converters field we get the following error irrespective of the fact it appears as an optional param in the API doc

"message": "Instantiation of [simple type, class org.graylog2.rest.resources.system.inputs.requests.CreateExtractorRequest] value failed: Null converters"

Can someone provide direction where we are going wrong or validate that this is an error?
Can the API documentation be updated to reflect the fact converters is required?
Can the API doco provide a sample config that should work?

**Comment by mattwilmott** [comment]
RPM versions:
graylog-server-1.0.1-1.noarch
graylog-web-1.0.1-1.noarch

**Comment by joschi** [comment]
@mattwilmott The `converters` attribute is an object (`Map<String, Map<String, Object>>` in Java).

Your extractor definition has to look like the following JSON:
```json
{
    "title": "sshd failed password username",
    "cut_or_copy": "copy",
    "source_field": "message",
    "target_field": "ssh_fail_username",
    "extractor_type": "regex",
    "extractor_config": {"regex_value":"Failed password for (.+) from"},
    "converters": {
        "lowercase":{}
    },
    "condition_type": "regex",
    "condition_value": "Failed password for .+ from .+",
    "order": 0
}
```

Kindly also post general support requests to our [mailing list](https://groups.google.com/forum/#!forum/graylog2) or to our IRC channel [#graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog).
