### ISSUE TITLE
PUT /system/grok/<id> returns success but fails to update

### ISSUE THREAD

**Issue by mattwilmott** [Graylog2/graylog2-web-interface#1224]
Calling with JSON,
{
      "name": "NONNEGINT",
      "pattern": "\b(?:[0-9]+)\b"
}

both via the API browser and a separate curl, returns 200 and flashes success but doesn't update the value in mongo. Editing the value via the web view results in an update. Appears to be localized to just the API.

**Comment by mattwilmott** [comment]
RPM versions:
graylog-server-1.0.1-1.noarch
graylog-web-1.0.1-1.noarch

**Comment by joschi** [comment]
There are two resources in the Graylog REST API for updating Grok patterns, one for updating a single pattern (`PUT http://localhost:12900/system/grok/<ID>`) and one for bulk-updating multiple patterns (`PUT http://localhost:12900/system/grok`). Which one are you using and what's the exact request you're sending?

Also kindly post general support requests to our [mailing list](https://groups.google.com/forum/#!forum/graylog2) or to our IRC channel [#graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog).

**Comment by edmundoa** [comment]
We didn't hear about this in a while, so I'm closing the issue. Please reopen if this is still relevant.
