### ISSUE TITLE
Feature Request: Additional values for field statistics

### ISSUE THREAD

**Issue by rockaut** [Graylog2/graylog2-web-interface#1229]
There are two values i miss in the field statistics list: first and last. They would be a great addition to do searches and dashboards like "Last Value was ..."

**Comment by kroepke** [comment]
I don't quite understand the request :)

"Last value" compared to what point in time?

**Comment by rockaut** [comment]
Sorry for not being precise here.
- With last value i meant to show the value of the last received message.
- and with first value i meant the oposite of last so the first ever received message.

So for instance:
Currently we can get the statistics for the field "level" with that values:

![image](https://cloud.githubusercontent.com/assets/453368/7835850/2ada94fe-047c-11e5-85d3-0fa7bf940d2c.png)

 Total messages: 66
 Mean: 6
 Std. deviation: 0
 Minimum: 6
 Maximum: 6
 Sum: 396
 Variance: 0
 Sum of squares: 2.376

What i want is two more statistics that would show me:
First: 6
Last: 6

That would be great to show, for instance, an widget on a dashboard with the last received Error-Level state.

Hmm... a easy request, quite complicated explained but i currently missing a better description here :D

**Comment by kroepke** [comment]
Unfortunately this is extremely expense to do for both ends of a search result, because you need to look at the entire result set.
Additionally it's not really a "statistic" because these values cannot be computed as aggregates (meaning that the input has to be sorted first).
I don't see a way of implementing this in an efficient way.

**Comment by rockaut** [comment]
Realy? It's heavier than minimum/maximum and mean?
Isn't only to take the first and last message of the resultset? I don't see any computing or looping through.

**Comment by kroepke** [comment]
For a result set with 100 million messages you need to sort and load the first and last value. There's no automatic way to get that value out of elasticsearch, so we would need to loop, yes.
The min and max you can get by only looking at values, not at (timestamp, value).

**Comment by rockaut** [comment]
Oh ok i see. Crap.

**Comment by rockaut** [comment]
Are you sure that can't be done?
see #1228

**Comment by kroepke** [comment]
Well, if our code loops or does two additional queries, which are expensive is basically the same…
