### ISSUE TITLE
Page design on "Indexer failures" page is broken

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1232]
`graylog-web-interface-1.1.0-SNAPSHOT-20150427075811.tgz`

![bildschirmfoto 2015-04-27 um 17 17 49](https://cloud.githubusercontent.com/assets/6331205/7350851/fd2a4b94-ed01-11e4-93ac-4b57c31b8a39.png)

**Comment by kroepke** [comment]
this has been fixed in the meantime.
![screenshot](https://cloud.githubusercontent.com/assets/52014/7472298/56a1483c-f331-11e4-9c7f-d00d4ddb8906.png)
