### ISSUE TITLE
Page design on "metrics of a node" page is broken

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1233]
`graylog-web-interface-1.1.0-SNAPSHOT-20150427075811.tgz``

![bildschirmfoto 2015-04-27 um 17 32 14](https://cloud.githubusercontent.com/assets/6331205/7351107/7eebc3dc-ed03-11e4-8db9-0051ce6b0661.png)

**Comment by kroepke** [comment]
There has been some unlogged progress on this:
![screenshot](https://cloud.githubusercontent.com/assets/52014/7453184/e457138a-f266-11e4-99bc-f9e3da91366b.png)
