### ISSUE TITLE
Page design on "Inputs of a node" page is broken

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1234]
`graylog-web-interface-1.1.0-SNAPSHOT-20150427075811.tgz`

![bildschirmfoto 2015-04-27 um 17 34 20](https://cloud.githubusercontent.com/assets/6331205/7351148/bfdc445c-ed03-11e4-89fe-2ad1d1f9fdc5.png)

**Comment by kroepke** [comment]
probably already outdated, but it still has issues

**Comment by kroepke** [comment]
Global and local inputs are styled differently, and the newer styling needs more work, it really looks out of place.

![screenshot](https://cloud.githubusercontent.com/assets/52014/7472214/56b56e3a-f330-11e4-8e17-be22f2e342a7.png)

**Comment by bernd** [comment]
The static fields are also missing from the local inputs.

**Comment by bernd** [comment]
Looks better now. (with #1273)
![7ihmwmhnjmyqlg1etjarutj57zc098agcccawlechf8mkgws llp72yyoc0iiiaaaggggaacjyda hvyluwjaqqqqaabbbbaaaeeeeaaaqqqqaabbbbaaaeeeedgbqsqfr3gdudwcccaaaiiiiaaaggggaaccccaaaiiiiaaaggggaacjyda hvyluwjaqqqqaabbbbaaaeeeeaaaqqqqaabbbbaaaeeeedgbqsqfr3gdudwcccaaaiiii](https://cloud.githubusercontent.com/assets/461/7684239/d81c9d78-fd84-11e4-83ea-e4ff3f8be8fa.png)
