### ISSUE TITLE
Pagedesign on outputs page needs improvement 

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1236]
`graylog-web-interface-1.1.0-SNAPSHOT-20150427181837.tgz`

![bildschirmfoto 2015-04-28 um 11 29 53](https://cloud.githubusercontent.com/assets/6331205/7366813/078b031e-ed9b-11e4-9ab7-6f8fdc243bd6.png)

**Comment by florianvolle** [comment]
Also the outputs page is still using the old design.

**Comment by bernd** [comment]
Giving this to @dennisoelkers.
