### ISSUE TITLE
Stream search result page design needs improvement 

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1239]
`graylog-web-interface-1.1.0-SNAPSHOT-20150427181837.tgz`

![bildschirmfoto 2015-04-28 um 15 37 37](https://cloud.githubusercontent.com/assets/6331205/7370827/fbbe6702-edbc-11e4-9281-1f040e420dbe.png)

**Comment by kroepke** [comment]
fixed in the meantime
