### ISSUE TITLE
No Lock Icon on Dashboard

### ISSUE THREAD

**Issue by ztech0** [Graylog2/graylog2-web-interface#1241]
We are not seeing the unlock icon on our test dashboard, either on 1.0.1 or after upgrading to 1.0.2. We have tried both Firefox and Chrome. 

Is there something I am overlooking?

![image](https://cloud.githubusercontent.com/assets/12161647/7383001/7ed07734-edcc-11e4-8da4-9595fa820b52.png)

**Comment by joschi** [comment]
The lock/unlock icon will be displayed once there is at least one widget on the dashboard.
