### ISSUE TITLE
Make new web interface UI work with graylog-radio nodes

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1242]
Make sure that the new UI works with `graylog-radio` nodes.

* Messages received through an radio input should show this in the message detail view and the expanded message view in the search result table
* The nodes detail page must work with radio nodes
* The list of nodes must have a second section for radios

I might be missing something but these are the first and most important things that come to my mind.

**Comment by kroepke** [comment]
Radio detail page still broken
![screenshot](https://cloud.githubusercontent.com/assets/52014/7471321/e46f5584-f325-11e4-884e-97801084203d.png)
