### ISSUE TITLE
Confusing description in nodes overview page

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1244]
It says:

> You can pause message processing at any time. The process buffers will not accept any new messages until you resume it. If the message journal is enabled for a node, which it is by default, incoming messages will be persisted to disk, even when processing is disabled. If it is disabled, you might lose messages sent to inputs that do not support buffering, such as TCP and UDP-based inputs.

Why would TCP or UPD-based inputs cause message loss?

**Comment by kroepke** [comment]
This is old. It refers to non-AQMP or Kafka messages.
I would like to review all texts to be honest.

**Comment by lennartkoopmann** [comment]
Just removed it. Follow up ticket: #1245
