### ISSUE TITLE
Review all description texts

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1245]
We might have more outdated description texts like in #1244. Review to make sure that it is all up to date.

**Comment by kroepke** [comment]
Moving this to 1.2.0 as 1.1.x should only receive actual bug fixes at this point.

**Comment by edmundoa** [comment]
@lennartkoopmann do you want to take a look at this for 1.2.0? Please close the issue otherwise :)

**Comment by bernd** [comment]
Closing this. Please re-open if still relevant.
