### ISSUE TITLE
cannot import exported Content packs

### ISSUE THREAD

**Issue by andreaconsadori** [Graylog2/graylog2-web-interface#1250]
i create a content pack, i delete the dashboard referred to this content pack and i try to import the exported content pack.

i click import, select previously exported content pack and click update

i see "Success! ×Bundle added successfully" and then i click on Dashboard.... but no dashboard has been imported from content pack.

if i open the file with notepad++ i can see
"dashboards" : [ {
    "title" : "WindowsUpdate",
    "description" : "watch the windows update agent activity",
    "dashboard_widgets" : [ {
      "description" : "Ready",
      "type" : "SEARCH_RESULT_CHART",
      "configuration" : {
        "interval" : "week",
        "query" : "EventID:18",
        "timerange" : {
          "range" : 2592000,
          "type" : "relative"

where is the issue?

**Comment by edmundoa** [comment]
Hi,

I assume what you added to your comment is only part of the content pack file exported by Graylog, as it doesn't seem to be a complete JSON document, please correct me if I'm wrong.

Which Graylog version do you use? It would be really helpful if you could include the log output from your Graylog server and web interface during the content pack export and import are done, or at least specify any errors that appear there.

**Comment by andreaconsadori** [comment]
Yrs. It's only a part,  i'll take some times to clone the server and test import-export.

Graylog deb 1.0.1

--- Messaggio originale ---

Da: "Edmundo Alvarez" <notifications@github.com>
Inviata: 29 aprile 2015 16:23
A: "Graylog2/graylog2-web-interface" <graylog2-web-interface@noreply.github.com>
Cc: "andreaconsadori" <andrea.consadori@hotmail.it>
Oggetto: Re: [graylog2-web-interface] cannot import exported Content packs (#1250)

Hi,

I assume what you added to your comment is only part of the content pack file exported by Graylog, as it doesn't seem to be a complete JSON document, please correct me if I'm wrong.

Which Graylog version do you use? It would be really helpful if you could include the log output from your Graylog server and web interface during the content pack export and import are done, or at least specify any errors that appear there.

---

**Comment by andreaconsadori** [comment]
hi, today i try onfresh install and i've no log during import.
i've no more the original server so cannot past export log.

**Comment by andreaconsadori** [comment]
closed, my fault, i notice now that you0ve to selsect the package after import....

**Comment by edmundoa** [comment]
Good to know, thank you for your feedback!
