### ISSUE TITLE
Feature Request: adjustable widget sizes

### ISSUE THREAD

**Issue by rockaut** [Graylog2/graylog2-web-interface#1251]
The current view for widgets on dashboard is nice for remote displays but a little bold if you are using the dashboard just for short glimpses. It would be nice to modify the widget size at least in a way small-medium-big style or, at best, with drag-n-drop.
In this way the crippled display of dashboard histograms would also be solved.

**Comment by florianvolle** [comment]
Thanks for you request. This will become available in 1.1
