### ISSUE TITLE
Page design on "Manage extractors" page is broken

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1252]
`graylog-web-interface-1.1.0-SNAPSHOT-20150429210129.tgz`

![bildschirmfoto 2015-04-30 um 15 15 33](https://cloud.githubusercontent.com/assets/6331205/7413408/d5e15cfc-ef4b-11e4-816c-617f7deb07be.png)

![bildschirmfoto 2015-04-30 um 15 16 19](https://cloud.githubusercontent.com/assets/6331205/7413410/e398a972-ef4b-11e4-8624-dd727939a345.png)

**Comment by florianvolle** [comment]
Overview is working now. But going to import/ export extractors shows the same broken page design.

![bildschirmfoto 2015-05-07 um 14 31 05](https://cloud.githubusercontent.com/assets/6331205/7515255/ca7856ac-f4c5-11e4-80ba-5d70c7bdb62a.png)

![bildschirmfoto 2015-05-07 um 14 30 57](https://cloud.githubusercontent.com/assets/6331205/7515258/cfc1c396-f4c5-11e4-8fc0-b236b78dc964.png)

**Comment by bernd** [comment]
Good catch, thank you!

**Comment by bernd** [comment]
Extractor import/export should be fine now. Please check.

**Comment by florianvolle** [comment]
Tip Top!! :)
