### ISSUE TITLE
Edit inputs functionality is broken in new UI

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1253]
Does not open the modal at all.

**Comment by lennartkoopmann** [comment]
Like all other modals this must probably just be moved to the new modal DOM structure of Bootstrap 3.

**Comment by kroepke** [comment]
Yup modals all changed.

**Comment by lennartkoopmann** [comment]
My fault. Commented out modal.

It works, but is ugly - like the create input modal. This is handled in another ticket.
