### ISSUE TITLE
Don't show all messages from input

### ISSUE THREAD

**Issue by odessky** [Graylog2/graylog2-web-interface#1254]
Search string "gl2_source_input:55434064e4b01853083751f8" show me Nothing found
If I use elastic query - it show me records

**Comment by edmundoa** [comment]
Hi,

I guess you already did it, but just in case: did you try changing the default time range? Do you see any messages coming from that input if you remove the search query?

**Comment by edmundoa** [comment]
We didn't hear from you for a while, so I'm closing this. Please reopen if this is still an issue.

**Comment by gurramnag** [comment]
Hi Edmundoa,

Search string "gl2_source_input:56fb7408848e632a9f27b84c" show me Nothing found. I didn't get any records/messages here.Please suggest what's going wrong in it.

Thanks.

**Comment by joschi** [comment]
@gurramnag Please use one of the designated community support channels for these kind of questions: https://www.graylog.org/community-support
