### ISSUE TITLE
Ubuntu now uses systemd so the old startup scripts no longer work

### ISSUE THREAD

**Issue by tpedaste** [Graylog2/graylog2-web-interface#1256]
The .deb packages for should have systemd startup scripts so they work on the latest Ubuntu

**Comment by joschi** [comment]
We currently only offer DEB packages for LTS releases of Ubuntu (which are Ubuntu 12.04 LTS and Ubuntu 14.04 LTS at the moment).

This being said, there's a related issue for this at Graylog2/fpm-recipes#13, so I'm closing this issue as a duplicate.
