### ISSUE TITLE
Page design on "Indices" page is weird

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1260]
There is some strange line crossing the "index"

![bildschirmfoto 2015-05-07 um 15 14 03](https://cloud.githubusercontent.com/assets/6331205/7516036/8b4a60b8-f4cc-11e4-8420-917b8f95221f.png)

**Comment by bernd** [comment]
Already fixed 45 minutes ago.

**Comment by bernd** [comment]
Fixed by commit ed26e842a0cd869cf71335bbaff32620545cfa0c.

**Comment by florianvolle** [comment]
Not weird anymore ;)
