### ISSUE TITLE
Allow including full_message in CSV export

### ISSUE THREAD

**Issue by sleske** [Graylog2/graylog2-web-interface#1262]
Currently (with graylog 1.0.0) there is no way to include the "full_message" field in the CSV export.
However, for analysing messages, the full_message field can be critically important - for example, in our system, it contains the full stack trace of an error.

Since the full_message is also not visible on the man screen (#516), this makes it very difficult to work with the full_message. It would be very helpful to be able to export the full_message along with the other fields.

**Comment by sleske** [comment]
This question on stackoverflow:

[Graylog2 -> Is it possible to export the full_message (raw data) of an especific source? I mean the full_message, without any parsing?](http://stackoverflow.com/questions/21913977/graylog2-is-it-possible-to-export-the-full-message-raw-data-of-an-especific)
is asking for the same feature.

**Comment by sleske** [comment]
Some ideas for a solution:

* Allow selecting the full_message as a field to be displayd, like the other fields. Show its value in the result list like other fields, and accept that it may break layout (that would also solve #516).
* Allow selecting the full_message as a field, but don't show its value, just export it. Maybe add a note to the field name in the selection list, like "full message (not displayed, only for export)".
* Add an entry to the export menu: "Download as CSV, with full_message", or just "Download as CSV - all fields" (which would be useful for the other fields as well). The existing CVS export entry should then probably be called "Download as CSV - selected fields".

**Comment by sleske** [comment]
I'd be willing to provide a patch, if I can get some hint as to how and where to implement this.
Currently, to me the option of adding another export menu entry looks best.
Any hints as to how to implement this without breaking something else or causing problems?

**Comment by kroepke** [comment]
The upcoming version 1.1.0 will allow exporting the full_message. :)

**Comment by kroepke** [comment]
fixed by resolving #765 and #1265

**Comment by drewmmiranda** [comment]
I'm running 1.1.1 and do not see a way to complete this. Am I missing something?

**Comment by sleske** [comment]
Testing this with Graylog v1.1.4, it seems everything is implemented, _except the UI_  :confused:.

If I open the "More actions" menu for a search and copy the URL for "Export as CSV", I get an URL which produces the CSV download (if opened in another tab). That URL includes a parameter "fields" with the names of fields to export; if I add "full_message" to the list, I do indeed get an CSV export with "full message".

However, I cannot find a way to select "full_message" in the UI. The whole backend work seems rather pointless if the feature is not exposed in the UI. Or am I missing something?

**Comment by kroepke** [comment]
@sleske Can you please try again with the "all fields" option selected in the side bar (see screenshot).

For me that exports the full_message if selected.

![screenshot](https://cloud.githubusercontent.com/assets/52014/9550092/959bfbea-4da9-11e5-9793-cfc5fa5b1f1c.png)

**Comment by sleske** [comment]
Oops, sorry, my mistake.

Yes, if I select "full_message" in the list of fields to show, everything works as expected. The full_message is shown in the message list, and is included in the CSV export.

This is with graylog-web-interface v1.1.6 (2e264c2).

**Comment by kroepke** [comment]
@sleske Great to hear, I'll keep this open for now so we can update the documentation accordingly.

**Comment by sleske** [comment]
@kroepke Actually, I don't think there's much to document. "full_message" can now be used like the other fields, which is what most people would expect anyway, I suppose. Maybe mention in the release notes that full_message has now grown up and become a real field :-).

However, I noticed a different problem:
"full_message" is not included in the list of fields shown by "List fields of current page" (link at the bottom). This makes it hard to discover that it can be selected - I think that's why I missed it originally.
Should I open a new ticket about that?

**Comment by kroepke** [comment]
Nah we can use this one :)

**Comment by edmundoa** [comment]
Closing the issue, I wrote some documentation for this in https://github.com/Graylog2/documentation/commit/e53e768a0795730081b85b9dd803e2489837edad

**Comment by kaiserboss** [comment]
Hello,

I am using graylog 1.3.3 and I don't see the field full_message even when I click on all fields.
Is there some configuration to do so that to activate this field?

regards.

**Comment by joschi** [comment]
@kaiserboss You have to click on "all fields" below the list of fields to show all fields of all messages instead of just the available fields of the messages in the result of your current search query.

(Related mailing list post: https://groups.google.com/forum/#!topic/graylog2/tflEagSvHz0)
