### ISSUE TITLE
Smart search not working with new search page

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1268]
The smart search is not working even if it is enabled for my user.

**Comment by edmundoa** [comment]
Fixed in https://github.com/Graylog2/graylog2-web-interface/commit/647b1e254d5cd9bebfaf30e600f0fa6505f04c7b :)

**Comment by lennartkoopmann** [comment]
![](http://i.imgur.com/C0lPbLL.gif)
