### ISSUE TITLE
User profile page needs styling

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1269]
Easy to forget: The user profile page is not styled yet.

**Comment by bernd** [comment]
Maybe we should just remove the user profile page? You can only reach it from the input/outputs page at the moment and those links will probably disappear soon.

And there is no information that you do not have in the users overview table.

**Comment by edmundoa** [comment]
I'd also vote for removing all the links to user "profiles" and the user profile page. In the end they don't give much information.

**Comment by lennartkoopmann** [comment]
:+1:

**Comment by florianvolle** [comment]
Page design still needs improvment

**Comment by edmundoa** [comment]
I think @florianvolle meant the user list, as the user profile is not there any-more, so I created issue #1359 for it.
