### ISSUE TITLE
Notification count in overview page is not updated automatically

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-web-interface#1271]
In the current master, removing a notification doesn't update the notification count in the overview page automatically.

![screen shot 2015-05-18 at 11 56 25](https://cloud.githubusercontent.com/assets/716185/7678502/f3390518-fd54-11e4-9cea-f4eeca1564a4.png)

**Comment by kroepke** [comment]
I don't think this was ever the case, actually. Not sure if we really need to do this, because its still all jquery code. I'd rather throw that code out in 1.2

**Comment by edmundoa** [comment]
I leave it in 1.1.0 for now in case we have time or we want to do it, otherwise we move it to 1.2.

**Comment by bernd** [comment]
Overview page is dynamic in Graylog 2.0. Closing this one.
