### ISSUE TITLE
Web Interface is logging into Graylog by default

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1274]
It seems like the web interface is logging into Graylog by default on GELF TCP port 12201. This is very confusing because the collector also suggests to write to that port and then everything get's mixed up.

I'd suggest to:

- [ ] Disable logging to GELF by default
- [ ] Change suggested port of web interface GELF logging to some other port

**Comment by kroepke** [comment]
Closing because we already had a ticket for this.
