### ISSUE TITLE
Indication when expanding all messages

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-web-interface#1283]
When the user clicks on the expand all messages button, we should display a spinner or indication that we are doing it, as it may take some time.

**Comment by kroepke** [comment]
Turns out that this is slightly tricky, because the state is already being updated, so even rendering the spinner is slow because we need to render the entire table at the same time.

We'd need to wait until expanding the messages somehow, but every option I came up with is awkward.

**Comment by pkoraca** [comment]
Hello,

I have similar issue when I click Expand all messages - browser (tried Chrome and Firefox) is unresponsive. Firefox says there is issue with app-a151c8f7.js:18.

Also, CPU utilization on my laptop goes to 100%.

Cheers

**Comment by kroepke** [comment]
Well there's tons of javascript that needs to be executed when rendering the 100 messages.
We'll investigate whether we can do something about it. Worst case, we have to remove that button, I guess.

**Comment by edmundoa** [comment]
This was fixed in https://github.com/Graylog2/graylog2-web-interface/issues/1329
