### ISSUE TITLE
Scroll on actions

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-web-interface#1284]
When clicking on the "add to search" button, adding statistics, adding field graphs, or adding quick values, we should show some indication that we added some elements into de page, and maybe scroll to them.

**Comment by edmundoa** [comment]
Fixed with cb57495, 2ced1d7, 0136e8b, 71559b8, and e053fd0.

**Comment by kroepke** [comment]
![](http://www.reactiongifs.com/wp-content/uploads/2012/11/thank-you.gif)
