### ISSUE TITLE
Collector search/filter form can be submitted

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1287]
The collector search/filter form can be submitted and then reloads the page while it is meant to filter while you type.

Overall we should think about using Dynatable here like in other parts of the web interface instead of  homegrown table filtering.

**Comment by kroepke** [comment]
Dynatable does not fit into react very well, and seems unmaintainted (last commit in sep 14).
We are actually actively removing it, for these reasons.
