### ISSUE TITLE
Collector list active/inactive filtering not working

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1289]
The button to filter active/inactive collectors does not work.

**Comment by kroepke** [comment]
Cannot reproduce this, could you please elaborate what you are seeing and what does not work?

**Comment by lennartkoopmann** [comment]
The button is supposed to hide/show inactive collectors. Inactive collectors are collectors that did not send heartbeats in a while, e.g. are not running.

When I click the button to show inactive collectors, they are not appearing.

**Comment by kroepke** [comment]
Maybe a timing issue?
I think the default threshold is one minute.

**Comment by kroepke** [comment]
@dennisoelkers could you take a look, please?

**Comment by lennartkoopmann** [comment]
Dennis just talked to me and we were still not able to reproduce it. I am looking into it again to make sure that I did not use it wrong. Will report back!

**Comment by lennartkoopmann** [comment]
It is indeed working. I think I know what happened: I was expecting it to switch between active/inactive instead of adding the inactive collectors to the list. (which makes sense I think) Let me think about if we can make this more obvious UX-wise.

I also created this related follow up ticket: #1302

Sorry for the confusion. Thanks! :)

**Comment by lennartkoopmann** [comment]
5307b0b made it more obvious for me
