### ISSUE TITLE
Expand / Collapse all buttons on search results page have confusing icons

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1291]
The icons look like you add or remove something. I would not have expected them to expand/collapse the message details.

**Comment by kroepke** [comment]
I did not find them confusing, but here you go ;)

![screenshot](https://cloud.githubusercontent.com/assets/52014/7696790/fa91a7b4-fe00-11e4-963f-1504bca09fba.png)
