### ISSUE TITLE
Sidebar does not work when there are too many fields

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1292]
By making the sidebar scrolling with the content it can now grow outside the window size. The old sidebar had inner scrolling to solve this problem.

![screen shot 2015-05-18 at 2 54 18 pm](https://cloud.githubusercontent.com/assets/35022/7688875/e2b86076-fd6d-11e4-9b1f-dae9c2d74cdc.png)

**Comment by edmundoa** [comment]
I wrote an issue for that a few hours ago https://github.com/Graylog2/graylog2-web-interface/issues/1282 :smile:

**Comment by lennartkoopmann** [comment]
:)
