### ISSUE TITLE
Editing alert conditions does not work

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1304]
I cannot edit alert conditions. The modal is just not opening.

**Comment by kroepke** [comment]
The form should open inline, not in a modal, iirc.
But I might be confused :)

**Comment by kroepke** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/52014/7721302/ce632bbe-fed6-11e4-9466-5f9ab3dcf181.png)

**Comment by edmundoa** [comment]
Also works for me, so I'm closing this, please reopen if needed :)
