### ISSUE TITLE
Stream list has no loading spinner

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1309]
The stream list shows the "No streams configured" message while it is loading. This is confusing and should instead show a spinner.

**Comment by florianvolle** [comment]
Works for me on `graylog-web-interface-1.1.0-SNAPSHOT-20150520133756.tgz`

**Comment by lennartkoopmann** [comment]
Not working for me on latest `master`. Are we talking about the same thing? See recording:

![streamsspinner](https://cloud.githubusercontent.com/assets/35022/7730317/36915ba4-fedf-11e4-8656-1a2ab0f5ff93.gif)

**Comment by florianvolle** [comment]
Ups, I am not getting to that page at all but directly to the streams page.

**Comment by lennartkoopmann** [comment]
I delayed the loading by 1000ms in the code to show it. You are probably not seeing the loading at all because it is so fast on your local machine.

Production setups under load or accessed via a slower connection can easily take a short moment to load the streams. Long enough to see the "No streams configured" message and be confused. :)
