### ISSUE TITLE
Feature Request: Few Suggestions

### ISSUE THREAD

**Issue by HSVK** [Graylog2/graylog2-web-interface#1311]
Hi, 
   Just making my suggestions, i felt like these helps better. 

  - Can you please have an option to show the current users logged into graylog along with the memory they consume. This helps when we are running high on memory and to alert the user to narrow the search or whatever tasks that leads to high consumption

- In the search results, can we have the option to control the fields. So that we can customize the fields to display in the order we like. Helps to understand the message better and the saved view would help for faster work from next time.

- Can we also have the option to view the drool rules in the UI. 

- Inside the Nodes, the buffers and the utilization shows only in %, can they show the amount of memory allocated/consumed please. 

- Can we have option to create user groups, so it would be useful in giving permissions.  

Once again Thank you for the great tool. 

Thanks, Hema

**Comment by edmundoa** [comment]
Hi,

Sorry it took so long to reply to your suggestions. See the in-line comments.

> Can you please have an option to show the current users logged into graylog along with the memory they consume. This helps when we are running high on memory and to alert the user to narrow the search or whatever tasks that leads to high consumption

Not sure what you mean by "memory they consume". I think the closer we can get to this is to implement something like #754, where you could limit the timeframe users can use for searches. If that wouldn't help in your case, please feel free to add any ideas you have on this regard into our [product ideas portal](https://www.graylog.org/product-ideas/).

> In the search results, can we have the option to control the fields. So that we can customize the fields to display in the order we like. Helps to understand the message better and the saved view would help for faster work from next time.

Many people asked for it, you can track the progress in #595.

> Can we also have the option to view the drool rules in the UI.

There will be some drool UI support eventually, but still don't know any details.

> Inside the Nodes, the buffers and the utilization shows only in %, can they show the amount of memory allocated/consumed please. 

The main problem is that adding all values makes the UI really confusing. On 1.1, you can click on the "metrics" button next to any buffer to see the size it uses.

> Can we have option to create user groups, so it would be useful in giving permissions.

We are working on this at the moment, you can track the progress on #629.

**Comment by HSVK** [comment]
Thank you for the update.. 

My first request was to show the user names who are currently logged into the graylog GUI and how much memory is each user consuming inside the graylog. The ticket 54 is different from what i request. 

Rest all, will follow on the mentioned tickets.

**Comment by edmundoa** [comment]
Closing this issue. Since 2.1 we display active sessions in the UI, which was the only missing thing here.
