### ISSUE TITLE
Page design on edit rules of stream page needs improvment

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1314]
`graylog-web-interface-1.1.0-SNAPSHOT-20150520183755.tgz`

Page design is to dense. 

![bildschirmfoto 2015-05-21 um 14 26 48](https://cloud.githubusercontent.com/assets/6331205/7748514/9195d048-ffc5-11e4-8715-c74555ed9ede.png)

**Comment by florianvolle** [comment]
![bildschirmfoto 2015-05-21 um 14 35 27](https://cloud.githubusercontent.com/assets/6331205/7748628/b0489178-ffc6-11e4-977a-03df9b42a268.png)

**Comment by lennartkoopmann** [comment]
Thanks! Fixed in #1363
