### ISSUE TITLE
Setting a stream as startpage does not work properly 

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1315]
`graylog-web-interface-1.1.0-SNAPSHOT-20150520183755.tgz`	

Steps to reproduce

- create new user and login 
- create a stream
- go to actions dropdown "set as startpage"

After login in again you are indeed redirected to this stream but not when clicking the upper left Graylog icon. As a user I would expect to get to the startpage by clicking this icon.

**Comment by edmundoa** [comment]
This was already like that before, but something we should fix, good catch! :+1:
