### ISSUE TITLE
Wrong timestamp on stream rule editor

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-web-interface#1328]
When a message is loaded with `MessageStore.loadMessage`, the timestamp is not included in the result neither as a property of the message nor included in the fields, but we try to use it to show the message details. The end result is that we show the current time instead of the message timestamp.

**Comment by dennisoelkers** [comment]
Good catch! Will investigate.

**Comment by dennisoelkers** [comment]
Fixed in https://github.com/Graylog2/graylog2-web-interface/pull/1342
