### ISSUE TITLE
Keyword search broken

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1332]
`graylog-web-interface-1.1.0-beta.3-SNAPSHOT-20150526103631.tgz`

When doing a keyword search for `today` I do not get any results. When searching for `yesterday`I get todays results. Timestamps also show that the messages have been received today.

![bildschirmfoto 2015-05-26 um 14 54 37](https://cloud.githubusercontent.com/assets/6331205/7812976/30eb9b60-03b7-11e5-8341-40f28686b784.png)

**Comment by joschi** [comment]
Duplicate of Graylog2/graylog2-server#1047.
