### ISSUE TITLE
"Show messages from this collector view" displays no messages

### ISSUE THREAD

**Issue by zexxon** [Graylog2/graylog2-web-interface#1334]
"Show messages from this collector view" displays no messages when there are several messages present. 

On the internal Graylog instance
Search query: gl2_source_collector:394350c8-ba74-4a7c-8ffa-bf2472a5dadd

The gl2_source_collector field doesn't appear to exist.

**Comment by lennartkoopmann** [comment]
That field used to be there when I added that feature. Was it removed?

![](http://i.ytimg.com/vi/1h7f9LTq-90/maxresdefault.jpg)

**Comment by kroepke** [comment]
I cannot reproduce this. Is it still valid?

**Comment by bernd** [comment]
Another user is also seeing that problem.

https://groups.google.com/forum/#!topic/graylog2/DQNtp9kwnNI

**Comment by bernd** [comment]
Also does not work for me either. Will investigate.

**Comment by bernd** [comment]
I found the problem. See Graylog2/graylog2-server#1190 for a fix.
