### ISSUE TITLE
Sources tab does not show spinner when loading.

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-web-interface#1336]
Instead of showing a spinner, the sources tab is displaying "No message sources found for this time range. Did you try using a different one" when it is loading. In case of longer loading times this might be confusing for the user as it is not clear if it is still loading or there are really no results.

**Comment by kroepke** [comment]
It shows a spinner for me when loading data. Am I missing anything?
Do you have a screentshot?

**Comment by edmundoa** [comment]
I can also see the spinner while loading in the current 1.1. I remember we added a check when there is only one or two datapoints, as it makes no sense to display a histogram with a dot or a line, could that be the case here?

**Comment by dennisoelkers** [comment]
This is what I am seeing when SourcesStore.loadSources() takes a bit longer:

![screen shot 2015-05-28 at 10 38 01](https://cloud.githubusercontent.com/assets/41929/7855959/bcefbea6-0525-11e5-942a-6e1bfd109bf2.png)
