### ISSUE TITLE
WebSockets error

### ISSUE THREAD

**Issue by dennusb** [Graylog2/graylog2-web-interface#1338]
Hi,

We are trying the new 1.1.0-beta2 version, and it is using websockets to gather throughput information. Because we want to load balance things in our cluster we have a Squid 3 in front, and now it's dropping the websocket connections. So the througput thing is not working anymore.. we did you guys switch to websockets? Because this is going to cause a lot of trouble with load balancers i think!

**Comment by edmundoa** [comment]
Hi,

We added an option to disable websockets in here: https://github.com/Graylog2/graylog2-web-interface/issues/1322, please take a look at the upcoming 1.1-beta-3.
