### ISSUE TITLE
Generate Chart shows only one Message by resolution minute

### ISSUE THREAD

**Issue by Knechtruprecht81** [Graylog2/graylog2-web-interface#1339]
![generatechart](https://cloud.githubusercontent.com/assets/12628820/7839658/cf38e57a-0493-11e5-81e6-8f109d251674.PNG)

Graylog 1.0.2; Debian 7.8

The duration of search is one houre. The resolution for the generated chart ist minute.

**Comment by edmundoa** [comment]
Hi,

Could you please check in the developer tools of your browser if there is any errors?

**Comment by Knechtruprecht81** [comment]
Hi,
Firebug shows no errors
![generatechartkonsole](https://cloud.githubusercontent.com/assets/12628820/7956607/2e1c70f0-09e1-11e5-953f-751876698d5b.PNG)

**Comment by edmundoa** [comment]
Thank you for the information!

Okay, let's then try to take a look at the response the web interface sends to the browser. Could you please share with us the result of this request? You can execute it directly in the browser (where you are using Graylog) and paste here the returned JSON document.
```
http://<graylog-web-interface-host>:9000/a/search/fieldhistogram?rangetype=relative&q=&field=_Memory-Available&interval=minute&valueType=mean&streamId=&relative=300
```

Please don't forget to change the Graylog web interface host. You may also need to manually change the search parameters, that is the default relative search in the last 5 minutes.

**Comment by Knechtruprecht81** [comment]
The returned JSON:

{"to":"2015-06-03T10:34:11.743Z","time":268,"values":[{"y":0.0,"x":1433327340},{"y":0.0,"x":1433327400},{"y":5.407112192E9,"x":1433327460},{"y":0.0,"x":1433327520},{"y":0.0,"x":1433327580},{"y":0.0,"x":1433327640}],"interval":"minute","from":"2015-06-03T10:29:11.743Z"}

**Comment by edmundoa** [comment]
The data coming from the server only have one not-zero point of data, which is odd. Could you please check if this is still present on 1.1? There's a RC already available and the final version will be out soon :)

**Comment by Knechtruprecht81** [comment]
Ok. in version 1.1 is everything fine. Thank you.
![generatechart11](https://cloud.githubusercontent.com/assets/12628820/7963497/3cc5a91e-0a13-11e5-8774-56ed0eb7d37b.PNG)

**Comment by edmundoa** [comment]
Good to hear that! You're welcome :+1:
