### ISSUE TITLE
Not working with websockets off

### ISSUE THREAD

**Issue by dennusb** [Graylog2/graylog2-web-interface#1344]
Hi,

I turned the websockets off, because of issues with Squid3, but now i get cancelled HTTP requests to things like : http://bla.bla.nl/a/metrics/716/yssv5wtw/xhr_streaming?t=1432815428951.

So it still doesn't work :( Bug?

**Comment by kroepke** [comment]
I doubt that it is a "bug", we are using SockJS as an abstraction layer. It should work with Squid3, but I have absolutely no knowledge about the specifics.

That URL should simply do a long running ajax call (hence the streaming). If squid cancels those, then there's indeed a problem.
Not sure if we can force ajax polling on an interval.

**Comment by dennusb** [comment]
In the previous version of Graylog it was working fine, polling on a regular basis (every second or so). Why shouldn't it work now?

**Comment by kroepke** [comment]
Because it's completely different code. Previously we were doing regular Ajax calls from all over the place, the SockJS code bundles all of that in one connection.

We'll try to set up a test with squid3, although I see no reason why it shouldn't work with sockjs.

What exact error are you seeing?

**Comment by dennusb** [comment]
Cool. Thanks for setting up the test env.
I'm getting an connection cancelled message in my Chrome Dev tools.

**Comment by edmundoa** [comment]
Can you still see the metrics on your web interface or are they no loading at all?

**Comment by dennusb** [comment]
Nope, they will not load at all.

**Comment by kroepke** [comment]
Running squid 3.4.9 with more or less the default configuration (only adding a network allow rule) the xhr_streaming works fine for me, I don't even have to disable websockets in the project, because sockjs figures it out just fine.

Are you using a special configuration?

**Comment by kroepke** [comment]
As expected I get:
```websocket.js:32 WebSocket connection to 'ws://localhost:9000/a/metrics/002/gijmu10m/websocket' failed: Establishing a tunnel via proxy server failed.```

and then downgrade to xhr_streaming.

This is in the latest chrome on osx.

**Comment by kroepke** [comment]
also see #1353

**Comment by dennusb** [comment]
So, it happening more often! Okay, i'll wait. Maybe you guys can find something. In the mean time i will check our Squid version and see if in a more recent version they changed something regarding this!
