### ISSUE TITLE
Graylog v1.1.0-beta.2 - Unknown command omnibus-ctl: command (subcommand)

### ISSUE THREAD

**Issue by reivier77** [Graylog2/graylog2-web-interface#1347]
Since I upgraded the virtual appliance (1.0) to Graylog v1.1.0-beta.2 with the omnibus package, when I issue the "graylog-ctl" command it says there is an unknown command:

Here is the message:

ubuntu@graylog:/tmp$ graylog-ctl
I don't know that command.
/opt/graylog/embedded/bin/omnibus-ctl: command (subcommand)

**Comment by mariussturm** [comment]
Thanks for the report, since this is no web interface issue I have recreated this issue in the graylog2-images repo: https://github.com/Graylog2/graylog2-images/issues/64
