### ISSUE TITLE
Graylog v1.1.0-beta - Stuck on loading for metrics and such

### ISSUE THREAD

**Issue by reivier77** [Graylog2/graylog2-web-interface#1353]
Since the upgrade of Graylog 1.0 to 1.1.0-beta2 (and today 1.1.0-beta3), I'm unable for example to get the heap usage or to get the metrics of an input through the web interface. There are a few places where the display is stuck on "Loading...". Is that normal? Except this "display bug" (?), the system seems to work properly.

Top right corner, next to the username:
![image](https://cloud.githubusercontent.com/assets/12643327/7866143/759e0d4e-053b-11e5-8613-4f6b0dcfbb64.png)

System > Inputs:
![image](https://cloud.githubusercontent.com/assets/12643327/7866149/7d9fad72-053b-11e5-9255-907b621130b3.png)

Streams:
![image](https://cloud.githubusercontent.com/assets/12643327/7866175/b314f55c-053b-11e5-81a3-a3b66b05e4b8.png)

Heap usage:
![image](https://cloud.githubusercontent.com/assets/12643327/7866208/e82941c6-053b-11e5-95a0-785f8ccf2bd8.png)

**Comment by kroepke** [comment]
Are you using a proxy?
Are there any errors in the browser console?

**Comment by reivier77** [comment]
-I'm not using a proxy
-No error in the browser console

Is there any log to check for this issue?

**Comment by kroepke** [comment]
Can you check with the network tab in the developer tools (if you are using Chrome or Safari)?

There should be either a websocket connection or something that says "xhr_streaming".
What browser are you using?

**Comment by kroepke** [comment]
For the log: There's debug output in the web interface process if the metrics loading is successful.

**Comment by reivier77** [comment]
I'm using Chrome (version 43).

Here is a screenshot of what I have with the developer tools/network tab:

![image](https://cloud.githubusercontent.com/assets/12643327/7867568/dc1ef0c0-0544-11e5-9537-34cca9e64a72.png)

All the "xhr_streaming" have a status "canceled".

**Comment by reivier77** [comment]
app-d51815dc.js:23 WebSocket connection to 'ws://graylogserver/a/metrics/822/tc0io0m1/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
app-d51815dc.js:23 WebSocket connection to 'ws://graylogserver/a/metrics/691/fyiqwp5v/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
app-d51815dc.js:23 WebSocket connection to 'ws://graylogserver/a/metrics/909/lxud05l5/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
app-d51815dc.js:23 WebSocket connection to 'ws://graylogserver/a/metrics/630/5mw4ywds/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
app-d51815dc.js:23 WebSocket connection to 'ws://graylogserver/a/metrics/417/yeya1aet/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
app-d51815dc.js:23 WebSocket connection to 'ws://graylogserver/a/metrics/372/hzttjmn1/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
app-d51815dc.js:23 WebSocket connection to 'ws://graylogserver/a/metrics/171/f54ngwzh/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
app-d51815dc.js:23 WebSocket connection to 'ws://graylogserver/a/metrics/707/xftepybm/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
app-d51815dc.js:23 WebSocket connection to 'ws://graylogserver/a/metrics/873/14knng4f/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
app-d51815dc.js:23 WebSocket connection to 'ws://graylogserver/a/metrics/256/ht5yuyox/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
app-d51815dc.js:23 WebSocket connection to 'ws://graylogserver/a/metrics/411/zglmzuy3/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
app-d51815dc.js:23 WebSocket connection to 'ws://graylogserver/a/metrics/144/vgpnyhka/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
app-d51815dc.js:23 WebSocket connection to 'ws://graylogserver/a/metrics/710/p5o5odp2/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
app-d51815dc.js:23 WebSocket connection to 'ws://graylogserver/a/metrics/661/uuvzicm2/websocket' failed: WebSocket is closed before the connection is established.
app-d51815dc.js:23 WebSocket connection to 'ws://graylogserver/a/metrics/324/yjfrmydg/websocket' failed: WebSocket is closed before the connection is established.
app-d51815dc.js:23 WebSocket connection to 'ws://graylogserver/a/metrics/470/em3navyx/websocket' failed: WebSocket is closed before the connection is established.
app-d51815dc.js:23 WebSocket connection to 'ws://graylogserver/a/metrics/565/pwtg4wpu/websocket' failed: WebSocket is closed before the connection is established.
app-d51815dc.js:23 WebSocket connection to 'ws://graylogserver/a/metrics/324/rsvtjfk3/websocket' failed: WebSocket is closed before the connection is established.
app-d51815dc.js:23 WebSocket connection to 'ws://graylogserver/a/metrics/845/1ypedwd3/websocket' failed: WebSocket is closed before the connection is established.

**Comment by kroepke** [comment]
OK, we've seen this before (recent issue here I don't have the number right
now).
Can you attach the content of the request and response of the info resource
please?

The other issue used squid in between. It looks like it is trying to fall
back to xhr streaming but fails.

**Comment by reivier77** [comment]
"Can you attach the content of the request and response of the info resource
please?"

Sorry, can you explain me how to generate this?

**Comment by kroepke** [comment]
You can click on the request line and it will show you details about that
request. There should be a tab called response :)

Thanks!

**Comment by reivier77** [comment]
HEADERS 

Request URL:http://graylogserver/a/metrics/189/lwysbe0i/xhr_streaming?t=1432838380301
Request Headers
Provisional headers are shown
Origin:http://graylogserver
Referer:http://graylogserver/system/inputs
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36
Query String Parameters
view source
view URL encoded
t:1432838380301

RESPONSE

"Failed to load response data"

Let me known if there is all the requested details!

**Comment by kroepke** [comment]
That is the right data but I meant the request for the resource containing
"info", the request that works :)

**Comment by reivier77** [comment]
Here is the right data!

HEADERS

Remote Address:192.168.100.100:80
Request URL:http://graylogserver/a/metrics/info?t=1432838380264
Request Method:GET
Status Code:200 OK
Response Headers
view source
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:*
Cache-Control:no-store, no-cache, must-revalidate, max-age=0
Connection:keep-alive
Content-Length:78
Content-Type:application/json; charset=UTF-8
Date:Thu, 28 May 2015 18:40:48 GMT
Server:nginx/1.6.2
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4
Connection:keep-alive
Cookie:PLAY_SESSION=6476bbfc9af48b5337ab816983f0419748de1747-sessionid=1110594c8878b3f3005a7069cf29600172d476fd06660e3f7c646640ff53a79e740d377442d79ecfddcd3b07772ae8b8
Host:graylogserver
Referer:http://graylogserver/system/inputs
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36
Query String Parameters
view source
view URL encoded
t:1432838380264


RESPONSE

{"websocket":true,"cookie_needed":false,"origins":["*:*"],"entropy":199450434}

"Failed to load response data"

**Comment by kroepke** [comment]
Many thanks!
