### ISSUE TITLE
Filtering / drill-down using the 'quick values' feature

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-web-interface#1354]
In previous versions it was possible to use quick values for drill-down / modification of the query string by pressing the looking glas icon (inverting / negating the selection using shift-click, searching right way using alt-click, etc) - that does not seem possible in the 1.1 UI?

This is probably the thing that caused the most complaints after our upgrade to the 1.1-beta series :)

**Comment by kroepke** [comment]
This was addressed in https://github.com/Graylog2/graylog2-web-interface/commit/db839051505387ee7e3cc8b6da00dfbd457bbd6c and will be fixed in the next beta :)

Original issue was #1296, I'll close this one.

**Comment by henrikjohansen** [comment]
Thanks - I must have missed that commit message ...
