### ISSUE TITLE
Including arbitrary message fields in the email alarm callback template?

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-web-interface#1355]
Is it possible to include fields other than 'message' in the email alarm callback template?

We would really like to customise the email text to provide clear and concise alerts rather than dumping the entire message field into an email ....

**Comment by kroepke** [comment]
I think you should be able to use the ```${message.field}``` syntax to get specific fields.
If it contains ```${message}``` it will probably simply call the toString method of Message itself.

**Comment by kroepke** [comment]
We are using https://code.google.com/p/jmte/ for the template. Might be handy as a reference.

**Comment by henrikjohansen** [comment]
I cannot get that syntax to work ... 

${message} works
${message.source} works
${message.http_error_code} does not work

It seems that only certain (standard?) fields can be accessed using that method ?

${message.http_error_code} yields the following error : 

The Graylog server encountered an error while trying to send an email. This is the detailed error message: com.floreysoft.jmte.message.ParseException: Error while parsing 'message.http_error_code' at location (13:3): Property 'http_error_code' on object 'source: - | message: - 1,2015/05/29 13:50:30,00170 (...)

**Comment by kroepke** [comment]
I guess it tries to call a method on it.

**Comment by henrikjohansen** [comment]
Well, you can call ${message}, ${message.message} and ${message.source} but anything else fails so I'm guessing that arbitrary fields are not supported currently.

**Comment by edmundoa** [comment]
I think using `${message.fields.field}` will do the trick.

**Comment by henrikjohansen** [comment]
That was exactly what I needed - works like a charm! Thank you @edmundoa - you may enjoy an extra cookie today :)

Perhaps this should go into the official docs to avoid future confusion ?

**Comment by edmundoa** [comment]
Good to hear that! I think that would be a good idea :+1:

**Comment by bernd** [comment]
> Perhaps this should go into the official docs to avoid future confusion ?

I created a pull request to document this: https://github.com/Graylog2/documentation/pull/22
