### ISSUE TITLE
User list looks inconsistent

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-web-interface#1359]
I created this issue from #1269. User list feels inconsistent compared to inputs or outputs. Check if there's some work to do there for 1.1.

**Comment by lennartkoopmann** [comment]
I made a small change to the buttons in the top right. This makes me feel good enough with this page. The users list does indeed look different to the other list of entities in the web interface but the users list is also meant to hold dozens of users - compared to the nodes, outputs, inputs et al which are usually holding less and can display more useful information per entity.

Let me know if you feel differently about this and we can discuss. :)

**Comment by edmundoa** [comment]
Looks good to me, just wanted to clarify it :)

**Comment by florianvolle** [comment]
It still looks inconsistent to me to use the old design for edit and delete button. I get the point about having dozens of users in the list but it feels wrong to keep it like this when having an UI makeover.

**Comment by edmundoa** [comment]
As I discussed with @florianvolle, it would help if the user list (and also the grok pattern list), use the same colours for icons that other pages and remove those font-awesome icons. Will take care of that.

**Comment by edmundoa** [comment]
@lennartkoopmann I used the same colours as in the inputs and outputs for the buttons, feel free to do any changes if you feel like it's needed :+1:
