### ISSUE TITLE
There always is a field called "123" in the fields sidebar

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1360]
This looks like something left over from development:

![screen shot 2015-05-30 at 1 46 44 pm](https://cloud.githubusercontent.com/assets/35022/7898819/56ceaa7a-06d2-11e5-909e-d5fb3f31279a.png)

:katze:

**Comment by kroepke** [comment]
Are you sure this isn't a static field of yours? :)

I cannot find anything like this in the code.

**Comment by edmundoa** [comment]
I also haven't that field, so I guess is not in the code :)

**Comment by lennartkoopmann** [comment]
hahahaha, this is indeed a static field of mine. sorry for the confusion guys :)

![](http://www.reactiongifs.com/r/f.gif)
