### ISSUE TITLE
Content packs do not get removed

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1389]
`graylog-web-interface-1.1.0-rc.2-SNAPSHOT-20150531170302.tgz``

I added the nginx content pack. After removing it still appears in the list of streams. Also the nginx option is missing in the content packs section after doing this.

![bildschirmfoto 2015-06-01 um 14 34 15](https://cloud.githubusercontent.com/assets/6331205/7912967/322f02e6-086c-11e5-9ca8-27dac3e7b7b9.png)

![bildschirmfoto 2015-06-01 um 14 40 24](https://cloud.githubusercontent.com/assets/6331205/7912978/3ec4392c-086c-11e5-905e-8f325ab4522c.png)

**Comment by joschi** [comment]
There currently is no functionality to remove components generated by applying a content pack from Graylog. Removing the generated components might be difficult if the user modified them (e. g. added additional stream rules or dashboard widgets) or is using them somewhere else (e. g. a generated output in custom streams).

> Also the nginx option is missing in the content packs section after doing this.

You've removed the content pack, so it's been deleted from the database.

**Comment by florianvolle** [comment]
Maybe we should add this explanation to the documentation as the terminology used is rather confusing?! 
http://docs.graylog.org/en/latest/pages/sending_data.html?highlight=content

**Comment by florianvolle** [comment]
Closing this because of #1396
