### ISSUE TITLE
Use the stream message loader for extractors, too

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1399]
The message detail view in the stream message loader is pretty cool. We should use that for extractors in one of the following releases, too.

@dennisoelkers, want to give it a shot?

**Comment by edmundoa** [comment]
I think it makes sense to do this on another milestone, so I'm moving it out of 1.2.0.

**Comment by edmundoa** [comment]
This was already fixed.
