### ISSUE TITLE
Search results have no scrolling sidebar

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1402]
For some reason a search result does not always have a scrolling sidebar. It works after opening the developer tools which are making the visible part of the site smaller. Is there some trigger that enables scrolling?

The inner scrolling of the sidebar content works.

cc @edmundoa

**Comment by lennartkoopmann** [comment]
Safari 8.0.5 (10600.5.17)

**Comment by lennartkoopmann** [comment]
Edited title. It happens on normal search results, too.

**Comment by lennartkoopmann** [comment]
Correction: The scrolling is not always triggered when opening the developer tools. I now seem to never get it to scroll.

**Comment by lennartkoopmann** [comment]
![scroll](https://cloud.githubusercontent.com/assets/35022/7926928/9bc2ec5e-089e-11e5-80cd-3c5e7c49a7a3.gif)

**Comment by lennartkoopmann** [comment]
Okay, this is how I can reproduce it: Open the developer tools and reload the page. With the reduced height of the browser window, the sidebar will scroll. There seems to be some kind of `window.height` trigger. The same result if I just reduce the height of the browser window manually.

**Comment by kroepke** [comment]
The height update is done when one of several things happen:
 - window resize
 - toggling of per page/all fields
 - during resizing
 - on the initial rendering of the component

This seems like a Safari specific bug, the affix is not working at all for me.

**Comment by kroepke** [comment]
this might be related https://github.com/vert-x3/web-site/pull/30/files

**Comment by edmundoa** [comment]
Yesterday I made some changes in the sidebar to make it work on small screens and maybe something went wrong, will investigate.

**Comment by edmundoa** [comment]
The problem is with both affixes (the bottom pagination also doesn't update), so this has probably never worked. Reverting yesterday's changes also doesn't fix the issue.

@lennartkoopmann you should stay away from Safari, the new IE6™ :smile:
