### ISSUE TITLE
Start script fails silently if pid file exists.

### ISSUE THREAD

**Issue by gosub3000** [Graylog2/graylog2-web-interface#1405]
Graylog-web 1.0.2-1 is installed on Ubuntu 14.04.2 LTS.  Due to misconfiguration the service dies shortly after starting, leaving the pid file behind (/var/lib/graylog-web/application.pid).

Subsequent attempts to start the graylog-web service fail silently:
`initctl start graylog-web`

After some debugging I found it was because the pid file existed.

Update the startup script to warn that the pid file exists, or modify the startup scripts to verify that the pid in the pid file actually exists before aborting startup.

**Comment by edmundoa** [comment]
Hi,

I opened an issue on the right repository, please follow the progress here: https://github.com/Graylog2/fpm-recipes/issues/36.
