### ISSUE TITLE
Make "create stream" and "create dashboard" consistent 

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1406]
When creating a new stream you get some pop up opening, when creating a new dashboard a new site is loading. This should be consistent. I would prefer the pop up option.

![bildschirmfoto 2015-06-02 um 12 20 36](https://cloud.githubusercontent.com/assets/6331205/7933762/d23ff0be-0921-11e5-830a-9a09c75ddae9.png)

![bildschirmfoto 2015-06-02 um 12 20 45](https://cloud.githubusercontent.com/assets/6331205/7934886/fe1db428-092b-11e5-8f78-52c34d3439cd.png)

**Comment by edmundoa** [comment]
Thank you for writing this up! I forgot about it :(
