### ISSUE TITLE
Loading example message from input on Radio does not work

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-web-interface#1407]
Trying to create a stream rule, loading example message from input on radio does not work. Works for inputs on server node.

![random-input-stream-rule-bug](https://cloud.githubusercontent.com/assets/461/7936429/329a8cc8-0939-11e5-820c-f162a95a42a6.png)

**Comment by bernd** [comment]
Fixed in 5a1b274.

**Comment by edmundoa** [comment]
http://www.reactiongifs.com/r/dgbgb.gif
