### ISSUE TITLE
Web interface is unusuable on mobile

### ISSUE THREAD

**Issue by danros** [Graylog2/graylog2-web-interface#141]
The web interface on graylog (as of latest stable) is unusuable on mobile browsers, mostly because of some overcomplicated CSS around the menus, causing elements to overlap. 

Everything else works fine as far as I can tell. Unfortunately, without the menus, using graylog is quite difficult!

I have tested on firefox and chrome on my android phone.

**Comment by kroepke** [comment]
Version 1.1 has many improvements for smaller screens, so I'm closing this now.
