### ISSUE TITLE
Fields Sidebar Cutoff (1.1.RC3)

### ISSUE THREAD

**Issue by NickMeves** [Graylog2/graylog2-web-interface#1410]
For large lists of viewable fields, the bottom of the left fields sidebar is cutoff.  The lower entries are inaccessible and the sidebar is unscrollable.  Both with smaller window size (but larger than mobile responsive CSS) and with full screen.

First noticed in 1.1.RC1.  Still persistent in 1.1.RC3.

OS: Windows.  Browser: Firefox

**Comment by kroepke** [comment]
@edmundoa can you please do a quick check and if easy to fix we'll see if we can pull this into 1.1.0?

**Comment by edmundoa** [comment]
Hi,

I'm looking into it using the latest Firefox (38.0.5) version on Windows 7 and I can't reproduce the issue. Could you please give us some more details @NickMeves? Browser/OS versions, and any errors that you may see on your browser's Javascript console would be really helpful.

**Comment by edmundoa** [comment]
I just tried to reproduce the issue on Windows 8.1 with the same results.

**Comment by NickMeves** [comment]
Windows 7
Firefox ESR 31.5 (In the Corporate setting we will frequently be many versions behind current releases)

I'll dig into JS consoles to see if anything is flagging.  This occurs with searches that have tons of fields in the sidebar (30+)

**Comment by NickMeves** [comment]
Pulled it up in Firefox and Safari from my Mac side -  Looks great!  I see other things going wrong on the older Firefox side with CSS styling though in addition to the left sidebar not being able to figure out the window height dynamically.

**Comment by NickMeves** [comment]
No Matter how I resize the page, this element isn't updating on the Windows 7, Firefox 31.5 side:

<div data-reactid=".2.0.0.0.1" style="max-height:1000px;overflow-y:scroll;">

That max height is dynamic and shifting as I resize things on the Mac side with Firefox and Safari (which I assume is the intended functionality).

Maybe if resizing isn't doable for older browsers have the default max-height be lower than 1000px (500px maybe?) so the sidebar is at least viewable when it won't resize?

**Comment by kroepke** [comment]
We'll try to get a proper fix in for 1.1.1, if it's too difficult I agree
that otherwise a fallback to a fixed max-height might be the best option.

**Comment by edmundoa** [comment]
I could reproduce the issue using Firefox 31.7 esr. As @kroepke said, let's try to fix the height calculation on 1.1.1.
