### ISSUE TITLE
Add "I'm done" button to alerts and outputs page

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1415]
Adding the "I'm done" button to alerts and outputs page would add more consistency to the web-interface. At the moment you have it only on the "rules of a stream" page. We should either disable this one or add it to alerts and outputs as all 3 pages are reached through the streams page, depending on how useful that button is.

![bildschirmfoto 2015-06-03 um 16 30 58](https://cloud.githubusercontent.com/assets/6331205/7962501/f5616270-0a0d-11e5-8bff-02e0e31fb819.png)

**Comment by edmundoa** [comment]
I don't think the button is too useful, specially since creating streams is not going through several pages in the application any more. I also think we should address this later, also taking care of other UX issues in the page.

**Comment by bernd** [comment]
Closing, please re-open if still relevant.
