### ISSUE TITLE
Source is incorrect in Search and Stream tabs

### ISSUE THREAD

**Issue by aarondcounts** [Graylog2/graylog2-web-interface#1416]
When I am looking at syslog messages in either the Search or Stream tabs, it is showing incorrect Source names. It is showing names like connection, tcp, denied, UDP, etc. For the most part, it looks like this is mainly occurring when the logging device is a Cisco ASA firewall. I am <b><i>not</b></i> using the EMBLEM format for the messages. When I look in the sources tab as well it is showing the wrong names as well. 

Sources Tab
![image](https://cloud.githubusercontent.com/assets/8450255/7962911/19082068-09de-11e5-904f-ede4543feb30.png)

Search tab
![image](https://cloud.githubusercontent.com/assets/8450255/7962919/27c818d8-09de-11e5-83e2-5e0fd118dfbe.png)

**Comment by edmundoa** [comment]
Hi,

I think this is mostly a problem with the log message format those devices send to Graylog (firewalls often send non RFC compliant messages as Syslog), and not a bug on Graylog itself. Here we explain the problem a bit more in detail: http://docs.graylog.org/en/1.1/pages/sending_data.html#syslog

Could you please ask in our [mailing list](https://groups.google.com/forum/#!forum/graylog2) or [IRC channel](https://webchat.freenode.net/?channels=%23graylog2)? I think you might get more information there, or maybe find someone that already solved the problem.
