### ISSUE TITLE
set default permissions for LDAP users

### ISSUE THREAD

**Issue by kubanczyk** [Graylog2/graylog2-web-interface#1419]
A new feature request. In the same place where LDAP config has now "Default permission group: Reader" it should allow to assign also default permitted streams and permitted dashboards.

This is a pre-requisite to https://github.com/Graylog2/graylog2-web-interface/issues/676

**Comment by zolech** [comment]
+1

Setting permissions every time new user appears in graylog is very annoying. Especially when you have 50+ users. There should be option for mapping LDAP groups to specific stream/dashboard permissions.

**Comment by garywh** [comment]
+2 

Hi guys Is there any activity on this?

**Comment by edmundoa** [comment]
This will be done as part of #629. I'm closing this issue to avoid confusion, please track the progress on the linked issue.
