### ISSUE TITLE
"Create one now" link on streams page does not work

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-web-interface#1424]
It appears as a link, but does not open the modal.

![screenshot](https://cloud.githubusercontent.com/assets/52014/7984870/84659c5c-0acc-11e5-9945-ae84e26e8965.png)

**Comment by edmundoa** [comment]
![wsod](https://cloud.githubusercontent.com/assets/716185/7985272/e6417038-0acf-11e5-8875-529c0e84f921.gif)
