### ISSUE TITLE
Content doesn't fill widget by width

### ISSUE THREAD

**Issue by beezoncheg** [Graylog2/graylog2-web-interface#1430]
Content in widget is not filling it by width.
When I resize widget horizontally to the double size it fills up the full width.
Value is a long string without spaces.
![graylog](https://cloud.githubusercontent.com/assets/8158677/7993511/338f1234-0b0f-11e5-82d0-0888b15bad96.png)

**Comment by edmundoa** [comment]
Hi,

The problem happens when the widget title overflows. We need to take care of that, in the meantime you can resize your widgets or use shorter names.
