### ISSUE TITLE
Widgets are not getting back in place when resizing window

### ISSUE THREAD

**Issue by beezoncheg** [Graylog2/graylog2-web-interface#1431]
Dashboard 3x2 widgets. When I shrinking window right 2 widgets are moving down. After restoring window size they are not going back. They get back in place only after page refresh.

OSX 10.10.3
Chrome 43.0.2357.81 (64-bit)

**Comment by bernd** [comment]
Does this still happen with Graylog 1.1? Please re-open if this is still a problem. Thank you!
