### ISSUE TITLE
Toggling all fields in search list throws error and breaks pagination

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-web-interface#1434]
Steps to reproduce:
 - Do search which returns a result set with a bigger number of fields
 - Click on "All" fields
 - Select a different page in pager

Result:
 - Step 2 produces a JS error in the console: "Error: Non-extensible objects are not allowed as keys."
 - Field selection is not changed in the message list
 - Browser is reloading a search page without a search result

**Comment by edmundoa** [comment]
Just to clarify: it only seems to happen in Safari.
