### ISSUE TITLE
Web interface behind a load balancer needs sticky sessions

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-web-interface#1435]
Since the throughput metrics are being pushed to the client the logged in session needs to be sticky, otherwise a round robin load balancer will get 404s for the metric updates in the default configuration (we default to xhr_polling).

Websockets should be fine, but if there are proxies in between that will trigger other problems.

Make sure the documentation mentions this.

**Comment by reighnman** [comment]
+1

**Comment by kroepke** [comment]
The updated documentation should be automatically available in a few minutes.
