### ISSUE TITLE
Utilize HTML5 clipboard API

### ISSUE THREAD

**Issue by benwa** [Graylog2/graylog2-web-interface#1437]
Let's get rid of zeroclipboard for a native solution.
![capture](https://cloud.githubusercontent.com/assets/1351571/8012049/3a9f1074-0b8c-11e5-91f8-d587116d6ecd.PNG)
An example can be found [here](http://updates.html5rocks.com/2015/04/cut-and-copy-commands).

[CanIUse](http://caniuse.com/#feat=clipboard) shows that only Chrome and Opera have non-caveat support, so perhaps only enable it for those browsers?

**Comment by edmundoa** [comment]
Hi,

This is a really good idea, but I'd rather change it once the standard is more extended and we can actually remove zeroclipboard for good. In any case, it would be great if you could add it into our ideas portal, so the community can decide how important this is: https://graylog.ideas.aha.io/

**Comment by benwa** [comment]
With [more adoption](http://caniuse.com/#feat=clipboard) and [clipboard.js](http://zenorocha.github.io/clipboard.js/), I think it's worth looking into again.

Safari is the only major browser holding back, and it has a fallback (also I'd be curious to see the percentage of Graylog users that use Safari anyway).

**Comment by edmundoa** [comment]
We replaced zero clipboard with clipboard.js in master. It will be available after 1.3.
