### ISSUE TITLE
Graphs stay open on subsequent unrelated searches

### ISSUE THREAD

**Issue by NickMeves** [Graylog2/graylog2-web-interface#1441]
Version 1.1.1:

If I generate a chart for a field, it ends up on the page as expected.

When I perform a new query of completely unrelated data in a completely different time range, the results come back but that previous chart is still on the page even though it has nothing to do with my new query.

Is this intended as a "feature" to possibly merge charts from unrelated times and data?  My users are getting confused by it and reporting it as a bug.

**Comment by edmundoa** [comment]
Hi,

This behaviour is intended, as field graphs are mostly used to compare data of different searches. Before we were doing it the other way around (you had to actually save them), but many users found that annoying, as it's really easy to forget to do so.
