### ISSUE TITLE
Empty configuration variables of alarm callbacks are displayed

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1445]
Optional configuration variables that are empty are displayed in alarm callback configurations and break the layout because we use a `<dl>` with floating `<dd>` that cannot handle empty values. Do not display variables with no value.

**Comment by dennisoelkers** [comment]
Which version are you using for this? We are not using a description list in the configuration well in 1.1, just a plain unsorted list with list items, as far as I can see.

**Comment by dennisoelkers** [comment]
Showing configuration variables which are null/undefined/"" as being empty in ff2ebfe6ea24f021f70d4846e88131fddb7d305d nonetheless.
