### ISSUE TITLE
Auto created search syntax must use quotes for values with whitespaces in them

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1448]
A user reported that when you click the "create search" button for a quickvalues value it does not take whitespaces in account:

![capture](https://cloud.githubusercontent.com/assets/35022/8027307/3da28618-0d5b-11e5-9d4e-eb8d45b435a8.png)

This will most probably be the case for all parts of the web interface where you can add values to the current search query. The old non-react behavior was taking care of this by just checking if there is whitespaces in the value or not and we never heard of issues with that so that should be a suitable solution.

**Comment by kroepke** [comment]
The old code should still be in there to call, probably simply not being included right now.
