### ISSUE TITLE
Search syntax error page does not keep stream scope

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1454]
When you are searching in a stream and cause a syntax error in the search query and then search again you are executing a global search, not a search bound to the stream.

Steps to reproduce:

  1. Go to a stream and search for `foo[` - This will cause a syntax error.
  1. On the syntax error page execute a search that will yield results. For example `*`
  1. Notice that you have executed a global search and not a search bound to the stream you originally searched in.

@florianvolle Please add this to the QA list. :)

**Comment by florianvolle** [comment]
Check ;)

**Comment by edmundoa** [comment]
Closing, as this was fixed in #1560.
