### ISSUE TITLE
<> values in fields are unescaped and don't display in Quick Values

### ISSUE THREAD

**Issue by NickMeves** [Graylog2/graylog2-web-interface#1455]
Version 1.1.1 - Multiple Browsers & OSes

If a field has components wrapped in <> (think a field like from extracted from emails: From: "Foo Bar" <foo.bar@example.org>).  When the field is pulled up in quick values everything between <> is missing.

This occurs partially (above example "Foo Bar" is displayed) and fully (if a field were <example>, it would appear blank in quick values).

I haven't fully tested, but I'm sure this might be occurring with all HTML snippets?  Hopefully not a XSS vulnerability...?

**Comment by NickMeves** [comment]
Definitely XSS & security concerns.  Markup is fully rendered.  Quick Values on link data rendered the link exactly as specified in the field, including external resources.

**Comment by kroepke** [comment]
Thanks! Will fix in the next bug fix release.
