### ISSUE TITLE
Unable to unpause streams, dispite editing permissions

### ISSUE THREAD

**Issue by aethos** [Graylog2/graylog2-web-interface#1456]
I am a "Reader" user, as labeled in the list of users. I have view and editing permissions to a stream, but I am unable to unpause the stream. This seems like an issue because although I am not able to unpause the stream, I am able to delete it.

**Comment by reighnman** [comment]
If editors can delete a stream they should be able to pause/unpause, if not they shouldn't have delete permissions either.

**Comment by kroepke** [comment]
This seems like a bug, editing permissions are supposed to grant all of the mentioned actions or none of them if only view permissions are granted.

**Comment by florianvolle** [comment]
As a read-only user I am also not able to manage outputs and alerts. Seems to be the same problem.

![bildschirmfoto 2015-06-09 um 14 55 06](https://cloud.githubusercontent.com/assets/6331205/8058143/8e77b5f6-0eb7-11e5-8c63-3babc33cf70a.png)

![bildschirmfoto 2015-06-09 um 14 56 13](https://cloud.githubusercontent.com/assets/6331205/8058161/b9fde70e-0eb7-11e5-9b86-94d738a88566.png)
