### ISSUE TITLE
Request-URI Too Long Error when drilling down in sources page

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-web-interface#1463]
When drilling down on the sources page there might be a "Request-URI Too Long" error. I have seen this happen when selecting "others" from the pie chart.

The problem is that we are using a GET request for the "others" query. With lots of sources in "others", the request URI can get too long.

We have to switch to a POST query for this to fix it.

**Comment by edmundoa** [comment]
Refs #1053

**Comment by edmundoa** [comment]
I don't feel comfortable changing this while on RC. Moving out of the milestone.

**Comment by edmundoa** [comment]
Moved to https://github.com/Graylog2/graylog2-server/issues/3327
