### ISSUE TITLE
Different Sources and different Extractors

### ISSUE THREAD

**Issue by theslash** [Graylog2/graylog2-web-interface#1467]
How would i do this right:
i geht syslog messages from cisco devices via port 514 and need to parse them with a sepcific extractor and i get syslog from vmware on port 514 and these don't work with the extractor...
can i separate messagesource for an extractor?

**Comment by edmundoa** [comment]
Hi,

You can add a condition to your extractors or just send your VMWare logs to another input (in another port), to avoid running the Cisco extractors on them.

As we only use Github for tracking issues with the code, we kindly ask you to use the [mailing list](https://groups.google.com/forum/#!forum/graylog2) or [IRC channel](https://webchat.freenode.net/?channels=%23graylog2) for any further configuration questions.

**Comment by theslash** [comment]
ok sorry and thx!
