### ISSUE TITLE
Widget in Dashboard didnt show the graph

### ISSUE THREAD

**Issue by Knechtruprecht81** [Graylog2/graylog2-web-interface#1479]
Hi,
the Problem is when i generate a chart 

![generatetchart1 1 2](https://cloud.githubusercontent.com/assets/12628820/8125155/70535340-10e3-11e5-91cf-07e85940c372.PNG)

and add this chart to dashboard the graph is not there.

![generatechartindashboard](https://cloud.githubusercontent.com/assets/12628820/8125158/74e68030-10e3-11e5-9fd6-b39af1004709.PNG)

Graylog v1.1.2

**Comment by edmundoa** [comment]
Hi,

Do you see any errors in your browser's Javascript console?

**Comment by Knechtruprecht81** [comment]
No Errors:
![generatetchart1 1 2_firebug](https://cloud.githubusercontent.com/assets/12628820/8127010/f557a04a-10f3-11e5-92a0-ffab45359615.PNG)

**Comment by edmundoa** [comment]
I could reproduce the issue when the data coming from the server contains `NaN`. When `Infinity` and `-Infinity` are there, the resulting graph is also different than the one in the search result page, and sometimes a bit weird.

**Comment by Knechtruprecht81** [comment]
Ok. Thank you.
