### ISSUE TITLE
Graylog 1.1.2 UI is not rendering properly in Internet Explorer.

### ISSUE THREAD

**Issue by nw-git** [Graylog2/graylog2-web-interface#1482]
IE 11, Windows 7. All updates.
Just installed the most recent version of Graylog 1.1.2, and it looks pretty terrible on IE 11, unless the Document Mode is manually changed. Even after changing the mode, javascript errors persist, making it unusable. Tested on two different computers.
 
![capture](https://cloud.githubusercontent.com/assets/12862078/8132781/1d232e5c-10f2-11e5-927e-7834671a0b0b.JPG)

**Comment by edmundoa** [comment]
Hi,

It looks like your IE 11 is using the compatibility view to render Graylog. Please ensure that it is disabled for Graylog, as we only support IE9+. If you don't see Graylog in the compatibility view list, please verify that "Display intranet sites in Compatibility View" is unchecked.

**Comment by nw-git** [comment]
Thanks Edmundo! I had checked that it was not in the compatibility view list, but unchecking the "Display intranet sites in Compatibility View" did the trick. Many thanks.
