### ISSUE TITLE
Need More (or adjustable option) height on search page message

### ISSUE THREAD

**Issue by NickMeves** [Graylog2/graylog2-web-interface#1483]
From the checkin notes on graylog2.less for Issue #612

On search result table:
- Keep original line breaks on the search result table, but removing
  extra spaces that might be in there accidentally
- **Only display up to 4 lines of the log message**, showing a small
  gradient over the last line to indicate that the message continues

For my user base this is way to low of a threshold.  We intentionally put more in the "message" field to see immediately the highlights of that we searched (so we know why something matched).

Possibility of extending this to 8-10 lines or making the line max customizable in the web interface configuration?

**Comment by edmundoa** [comment]
Hi,

The main problem with this is that the message table gets really long and unusable when using more lines. We can add options for many things, but that would make everything really complicated to debug and to use.

In any case, could you please add this idea into our [ideas portal](https://www.graylog.org/product-ideas/)? In that way we can see how important this is for the community.

Thank you!
