### ISSUE TITLE
Allow edits of field graph query & timerange on search result page

### ISSUE THREAD

**Issue by NickMeves** [Graylog2/graylog2-web-interface#1485]
When pulling up graphs of various queries and time ranges, it would be great to be able to edit the "Query" (and time range as well) of a graph straight from that graph and have the search only alter the context of that graph while remaining on the same page that is investigating a different query.

"Yay, I've made graph of data A from the last 5 days and customized the value, type, resolution perfectly to my liking."
"Lets look at data B for the last 5 days.  Hmmm, I need to go back 14 days. Ok, done graph made. Lets compare/merge with A.  Darn, A is still only back 5 days! And I want to tweak its query slightly.  And I spent all that time tuning it.  Dismiss, re-search, remake"

Apparently I'm in a storytelling mood... it's late on Friday.  Must be time for the weekend.

Anyway, something to make that scenario a little easier for the data analyst :)

**Comment by kroepke** [comment]
Are you talking about dashboards?

If you are, then #650 might be what you are describing.

**Comment by NickMeves** [comment]
Sorry, I should've been more clear:

This example was looking at graphs pulled up on the fly in the search context on a numeric field.  Now that they stay up between unrelated searches by default my user base was curious at the possibility of being able to tweak a graph from an old query to make it better line up with the current query they are on.
