### ISSUE TITLE
Launching input: No error message when putting positive value in negative field.

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1486]
`graylog-web-interface-1.2.0-SNAPSHOT-20150612131427.tgz`

When launching a new input with the QA plugin I do not get an error message when entering a positive value to a negative field. 

![bildschirmfoto 2015-06-15 um 14 02 30](https://cloud.githubusercontent.com/assets/6331205/8159464/4b0a04c2-1367-11e5-9f59-8bbfd9c7312e.png)

![bildschirmfoto 2015-06-15 um 14 03 02](https://cloud.githubusercontent.com/assets/6331205/8159466/4f674746-1367-11e5-9a22-2be62c57387e.png)

**Comment by edmundoa** [comment]
I think this is the same as #1473, and got fixed a few minutes ago. Please check again with a newer snapshot :)

**Comment by florianvolle** [comment]
#1473 was about launching an output :)

**Comment by edmundoa** [comment]
My bad :D

**Comment by florianvolle** [comment]
Still broken with the latest snapshot.

**Comment by dennisoelkers** [comment]
Can you please retest this? It works for me on master.

**Comment by edmundoa** [comment]
Tried to reproduce in Chrome and Safari using the current 1.2 branch but it worked as expected. @florianvolle please reopen if it happens again.
