### ISSUE TITLE
Pie charts bigger than the widget container

### ISSUE THREAD

**Issue by razvanphp** [Graylog2/graylog2-web-interface#1487]
![screen shot 2015-06-15 at 18 45 30](https://cloud.githubusercontent.com/assets/4599319/8165210/cde0e556-138e-11e5-884c-61626482958e.png)

Pie chart is always cut by the scroll. 

Also I think the values should be displayed on the pie itself since you can turn `show data table: false` and then you don't know what your chart is showing.

**Comment by edmundoa** [comment]
Hi,

Could you please indicate the Graylog version you are running? It would also help to know the browser you are using and any errors that you may see in your browser's Javascript console.

**Comment by razvanphp** [comment]
This happens in both Chrome and latest Firefox. There are no errors in the console.

graylog-web-interface v1.1.1 (893e8e7)

It seems it's fine at the first load, but as soon as the pie is refresh with AJAX it looks like on the screenshot.

**Comment by edmundoa** [comment]
That issue should be fixed in 1.1.2, could you please give it a try?

**Comment by razvanphp** [comment]
Yes, looks good, thanks!

**Comment by edmundoa** [comment]
Good to hear that, welcome! :+1:

**Comment by razvanphp** [comment]
@edmundoa this issue is again present in v1.2.0-rc.2, it should be no scroll there..

![screen shot 2015-09-07 at 15 04 04](https://cloud.githubusercontent.com/assets/4599319/9717307/f395a532-5571-11e5-9976-62f715226c9a.png)

**Comment by edmundoa** [comment]
Not sure what changed there, but will take a look.
