### ISSUE TITLE
Editing stream rule value does not update consistently on web page

### ISSUE THREAD

**Issue by zidvbelju** [Graylog2/graylog2-web-interface#1490]
Hey Team,

When I edit a stream rule value, and click save, the value itself does not [consistently] update on the web page, despite a "Success! Stream rule has been successfully updated" message. The value IS updated in MongoDB (refreshing the page causes the stream rule to show the correct data). Some sort of javascript bug?

I've been able to reproduce it a few times, but it's inconsistent. Using the latest version of Chrome. If you need anything else, let me know.

Thanks,
Z

**Comment by edmundoa** [comment]
Hi,

This is a problem with MongoDB, which only ensures write atomicity on a single document. As stream rules and streams are different documents (and are stored in different collections), sometimes there are inconsistencies in the data we display after updating stream rules. Anyway, data is persisted and should be consistent after some time, e.g. after a page reload.

I am not sure if we can do much about this but I'll leave the ticket open for now to see if someone has any idea on how to fix this issue.

**Comment by edmundoa** [comment]
Investigated this a bit further and turns out it's not related to MongoDB at all, but there is a bug in our Javascript code updating the stream rule that may trigger sometimes.
