### ISSUE TITLE
More than 5 colors in the pie charts

### ISSUE THREAD

**Issue by razvanphp** [Graylog2/graylog2-web-interface#1491]
Is there a hard limit to 5 colors? My values are really close, so I would expect to see them all on the pie chart, maybe one that has a bigger standard variation should be displayed as 'other'

![screen shot 2015-06-17 at 11 53 03](https://cloud.githubusercontent.com/assets/4599319/8204272/a8dfc330-14e7-11e5-9a54-bc979fd953db.png)

**Comment by edmundoa** [comment]
Hi,

The limitation to 5 values in the pie chart is intended. The reason for this is that pie charts are not effective when it comes to represent many values. In a case like yours, when data is so similar, they will also not help much, as they are also not effective at representing small variations in data.
