### ISSUE TITLE
Please do not capitalize widget-title

### ISSUE THREAD

**Issue by pdepaepe** [Graylog2/graylog2-web-interface#1498]
Hello,

Firstly thanks a lot for your great work on graylog web interface, each update brings a lot of very cool improvements.

I don't know the reason behind this, but may you please remove the following text-transform instruction? Widget titles case can sometimes be important.

.dashboard .widget .widget-title {
    display: inline-block;
    font-size: 18px;
    text-align: left;
    text-transform: capitalize;
}

Thanks

**Comment by joschi** [comment]
Aaaaand it's gone. Thanks for reporting this!
