### ISSUE TITLE
Newlines in messages keep breaking

### ISSUE THREAD

**Issue by SjonHortensius** [Graylog2/graylog2-web-interface#1499]
Messages that include newlines are frequently reported as broken. Could you introduce a unittest so this remains consistently fixed?

In the current layout, ```dl.message-details dd span { white-space: pre-wrap; }``` would fix this. 

Duplicates #815 #1018

**Comment by kroepke** [comment]
Which version are you referring to?

**Comment by SjonHortensius** [comment]
This is  v1.1.0

**Comment by edmundoa** [comment]
Hi,

Multi-line messages should look much better on v1.1.2. I'm closing the issue, but please reopen if you still see any problems with that.
