### ISSUE TITLE
Show surrounding messages

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#150]
Have a dropdown on the search result pages: "Show X [hours/minutes/seconds] of surrounding messages".

**Comment by d0x** [comment]
+1

**Comment by tarekz** [comment]
When do you expect this issue be closed? Thanks

**Comment by eorochena** [comment]
I agree with @d0x this would be a really useful feature

**Comment by dbprism** [comment]
I would like to +1 d0x on this request as well. I have logs to review to troubleshoot issues with JSON. When I search for "INVALID JSON STRING" in the error message, I need to see the line before to examine the string to resolve the issue. grep -B 1 INVALID filename is perfect for this since all of the entries are on the same screen if there are multiple incidents.
I could use the datetime to show lines around the entry to see the action but if I have 6 or 7 to resolve, I have to note the datetime and do the search that many times.

**Comment by menduraa** [comment]
+1 here as well. I have set up streams with only ERRORs, and when the devs check the dahboard, they need to see the lines before the error. Would be very useful. Thanks.

**Comment by sataman** [comment]
+1

**Comment by caseyhoward** [comment]
+1

**Comment by andrewlague** [comment]
+1

**Comment by sheavner** [comment]
+1 

Lead here by link that said it would be in v0.20 in Jan 2014.  http://grokbase.com/t/gg/graylog2/13c3dp4j42/context-in-quick-filter-searches-like-grep-c-10-mysearch-mylog-log-in-grep

**Comment by arobertn** [comment]
Just to add a UI suggestion for this from https://groups.google.com/forum/#!topic/graylog2/Kvg7yfVn_po , the 'time' portion of the search specification form could be enhanced to have a third option: "relative to time".  (The existing to are "relative to now" and "absolute".)  This option would allow specifying an absolute time point and then relative windows backward and forward (either with sliders or dropdowns).  Then a button could be added to the message detail panel (or even the results table row) "Show surrounding messages" which simply prefills that "relative to time" part of the search form.

**Comment by rumatoest** [comment]
Why you can not implement this really useful simple feature since 2013? 
You have completely rewrite web UI in new version, but you are not able to add simple button with small JavaScript logic.

**Comment by edmundoa** [comment]
@rumatoest as usual, PRs are welcome :)

**Comment by andydawkins** [comment]
+1

**Comment by edmundoa** [comment]
Please add your votes in our portal for ideas, having +1s in here only adds noise to the issue: https://www.graylog.org/product-ideas/

**Comment by rumatoest** [comment]
> Please add your votes in our portal for ideas, having +1s in here only adds noise to the issue:
In this case you should add ability to login at https://www.graylog.org/product-ideas/ with gitHub, Google account, twitter etc.

P.S. Sorry for another noise message

**Comment by Genkilabs** [comment]
Bump for @rumatoest idea to login with some kind of open auth. github, google.... stackoverflow ^_^

**Comment by joschi** [comment]
I'm locking this issue to prevent more noise…

**Comment by joschi** [comment]
This has been implemented in Graylog 2.0.0: http://docs.graylog.org/en/2.1/pages/changelog.html#graylog-2-0-0
