### ISSUE TITLE
JavaScript error on System->Users page in 1.1.2

### ISSUE THREAD

**Issue by voodoodrul** [Graylog2/graylog2-web-interface#1501]
After upgrading from 1.0.2.5 to 1.1.2, the System->Users UI fails to load properly and no users are displayed on the page. A JavaScript error occurs: 

![image](https://cloud.githubusercontent.com/assets/8071570/8260722/c04dc70a-1682-11e5-9a6b-b206cb63ec3e.png)

**Comment by edmundoa** [comment]
Hi,

I have been trying to reproduce the described issue with no luck. I think there might be some bogus data in the list of users the web interface is getting, could you please share the result of `http://<graylog-web-interface-host>:9000/a/system/users` with us? You can simply use that URL in the browser you use to access Graylog and send the response you will see in the browser.

As the data I'm requesting will contain the list of users in your system, please send it to support@graylog.com (including the issue number), we will treat it with maximum confidentiality.

**Comment by voodoodrul** [comment]
This turned out to be a problem with data in the users table in Mongo. The "startpage" element was an empty array instead of an empty object. Modified the user records and all is well

**Comment by edmundoa** [comment]
Thank you for updating the issue, I completely forgot about it :+1:
