### ISSUE TITLE
Only repaint Quick Values text if data changed (hard to highlight to copy/paste)

### ISSUE THREAD

**Issue by NickMeves** [Graylog2/graylog2-web-interface#1502]
When Quick Values is up, it updates with new data quite frequently.

But when looking at older data, it won't be changing.  And many times I want to copy and paste a certain value or values I'm looking at.  As I try to highlight, the reload operation wipes out what I attempted to highlight.

I know to just disable reloading -- but the generic user might not realize that before getting very frustrated :)

**Comment by edmundoa** [comment]
Referenced the wrong issue, reopening.
