### ISSUE TITLE
Dual Timestamp entries

### ISSUE THREAD

**Issue by gmonk** [Graylog2/graylog2-web-interface#1503]
Why are the two timestamp fields in the web interface ?  Im using the mqtt plugin and send a gelf formated message with timestamp which seems to overwrite  the  Timestamp(Capital T)  field visible in the interface which  has the correct time zone  but does not get exported to csv.  Its seems that there is a hidden timestamp field (lower case t)  when selecting all fields which does get exported to csv but does not have the correct time zone I have configured.  Why cant I just export the visible timestamp ? its useless for me to log data which doesn't contain the correct time when exported to csv

used versions 1.1.0 and 1.1.2 with same result

**Comment by edmundoa** [comment]
Hi,

Graylog uses a single timestamp field in the message. The web interface formats and converts the timestamp in messages to show them in your browser using your local time zone (or the one you set in your configuration). Exported data is not formatted, that is, message timestamps will be left in UTC, as it's easier to use by other programs afterwards (different users will have different use cases, so this is in the end just as good as any other guess we may do).

Does this solve your questions? I'm not sure if I understood the issue you are experiencing correctly.

**Comment by gmonk** [comment]
Gotcha make sense.  Thank you for the quick response

**Comment by edmundoa** [comment]
Good to hear, you're welcome!
