### ISSUE TITLE
Add "Last 3 Months" as a search dropdown option

### ISSUE THREAD

**Issue by NickMeves** [Graylog2/graylog2-web-interface#1515]
90 days seems to be the standard in data retention regulation, so my users would like to search that far back.

I have the space to hold back much longer, so I do -- but that causes them to search all time taxing the system looking in old indices in date ranges they don't need, when they are really just want to look at the last 90 days.  (I've told them about "3 months ago" or range searches, but the inevitably click all time since it is fastest)

**Comment by joschi** [comment]
Thanks for reporting this! The problem with adding "3 months ago" to the dropdown list of relative search time ranges is, that the list will get really large and confusing, and people will likely want to add "6 months", "1 year", "1 minute", etc. to the list…

A related idea has been added to our ideas portal some time ago ([Restricting timeframes for searches](https://graylog.ideas.aha.io/ideas/GL2E-I-325)) and will likely be added in one of the next versions of Graylog.

**Comment by edmundoa** [comment]
Hi,

As @joschi commented, we would likely need to add tens of entries in the timerange dropdown to cover each use case. I think this would fit better in our [ideas portal](https://www.graylog.org/product-ideas/), so we can see how important this is for the community. Would you mind adding your idea there, please? :)
