### ISSUE TITLE
Start and System Overview pages do not work if Elasticsearch is down

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-web-interface#1518]
The start/search and system overview pages do not handle Elasticsearch outages well. This makes it impossible to see the system messages if Elasticsearch is down or even to navigate to the System page.

Start page error:
![ysasjabigaesacriaieaei8egs p xv8xsde4uygaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/461/8549796/0528497e-24cd-11e5-8209-7bcd8aacc207.png)

System Overview error:
![rmwyncxscwaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/461/8549508/629316d6-24cb-11e5-9a39-1fefdc580e12.png)

**Comment by edmundoa** [comment]
The exception raised in the start page is gone now, it shows a timeout error instead. I saw exceptions in the System Overview and Indices pages, that we need to fix.
