### ISSUE TITLE
TimeZone Change Mess GrayLog Server

### ISSUE THREAD

**Issue by cpaunescu** [Graylog2/graylog2-web-interface#1521]
Hello,
I been trying to get Graylog2 running for a few days now, and so far, the only issue im having is TimeZone.
I downloaded the OVA File for Graylog2 Version 1.1.4. Installed, no issues.

Setup IP to static.
edit /etc/network/interfaces.
After which I ran the following commands, as per documentation.

$ sudo ifdown eth0 && sudo ifup eth0
$ sudo graylog-ctl reconfigure

Rebooted server, works perfect, no issues.
Now, I change the time-zone on graylog2 and on the system, as follows:

 sudo dpkg-reconfigure tzdata 
I set the TimeZone to US, Eastern.

 sudo graylog-ctl set-timezone US
I changed the TimeZone in Graylog2 to US

$ sudo graylog-ctl reconfigure
I ran the reconfigure for Graylog2.

Rebooted the server. Tried to go to the Website GUI, and now it says No Graylog2 server found.

I go to the server, and type:
$ sudo graylog-ctl status

All services running OK, no issues.
If I change the TimeZone back to UTC and reboot, I can use the Graylog2 server again, no issues.
So, why am I having issues when changing the TimeZone to US?

I appreciate the support. Thanks...

**Comment by mariussturm** [comment]
Because US is not a timezone. Use something like US/Central or US/Eastern ...

**Comment by joschi** [comment]
@cpaunescu You can find a list of valid time zones at http://www.joda.org/joda-time/timezones.html

**Comment by edmundoa** [comment]
We haven't heard about this in a while, so I'm closing the issue. Please reopen it if you are still struggling with it, or refer to our [mailing list](https://groups.google.com/forum/#!forum/graylog2) or [IRC channel #graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog) for further questions.

**Comment by zx1986** [comment]
```
Caused by: java.lang.IllegalArgumentException: The datetime zone id '"Asia/Taipei"' is not recognised
```

"Asia/Taipei" not works :-(

https://docs.oracle.com/javase/7/docs/api/java/util/TimeZone.html
http://stackoverflow.com/questions/30800797/what-is-zone-id-for-iceland-used-in-timezone-class-in-java-8

---

sorry, I changed my docker.env to:

```
GRAYLOG_ROOT_TIMEZONE: Asia/Taipei
```

then got this:

```
graylog                  | 2016-10-25 08:04:20,129 ERROR: org.graylog2.bootstrap.CmdLineTool - Invalid configuration
graylog                  | com.github.joschi.jadconfig.ParameterException: Couldn't convert value for parameter "root_timezone"
graylog                  |      at com.github.joschi.jadconfig.JadConfig.processClassFields(JadConfig.java:141) ~[graylog.jar:?]
graylog                  |      at com.github.joschi.jadconfig.JadConfig.process(JadConfig.java:99) ~[graylog.jar:?]
graylog                  |      at org.graylog2.bootstrap.CmdLineTool.processConfiguration(CmdLineTool.java:351) [graylog.jar:?]
graylog                  |      at org.graylog2.bootstrap.CmdLineTool.readConfiguration(CmdLineTool.java:344) [graylog.jar:?]
graylog                  |      at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:177) [graylog.jar:?]
graylog                  |      at org.graylog2.bootstrap.Main.main(Main.java:44) [graylog.jar:?]
```

**Comment by joschi** [comment]
@zx1986 See http://www.joda.org/joda-time/timezones.html for a list of valid timezones for the [`root_timezone`](https://github.com/Graylog2/graylog2-server/blob/2.1.1/misc/graylog.conf#L72-L74) setting.

**Comment by zx1986** [comment]
@joschi thanks! I am using `Asia/Taipei` which is valid.

**Comment by joschi** [comment]
@zx1986 Which version of Graylog are you using?

**Comment by zx1986** [comment]
@joschi the latest version with docker-compose.
Never mind, I found that it could setup timezone for specify user from setting page.
