### ISSUE TITLE
Performance regression loading stream list

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-web-interface#1525]
Loading a stream list with many streams (~130) seems to be much slower on 1.1.4 that it was on 1.0. Before it took around 10 seconds and now around 45. Here is a screenshot of a request in the browser's developer tools: ![](https://i.imgur.com/sZVNFmG.png)

Investigate if there is something wrong in the code causing this problem.

**Comment by patricvisit** [comment]
Very strange, just grabbing <graylog ip>:12900/streams is really fast, 1.05s

![image](https://cloud.githubusercontent.com/assets/1671117/8654661/2074a880-298c-11e5-8d7f-3bd7be36e7ae.png)

**Comment by joschi** [comment]
Backported to 1.1 branch in Graylog2/graylog2-server@21cb2394968b92aebbafa0127d6305e5b54ae9d3.

**Comment by edmundoa** [comment]
Thank you @joschi! :+1:
