### ISSUE TITLE
Absolute or Keyword Time Search doesn't work

### ISSUE THREAD

**Issue by plt-sun** [Graylog2/graylog2-web-interface#1528]
if i search in web interface by realtive timerange (eg: search in last 30 minutes) all works fine. but if i search with selecting timerange in histogramm or searching with absolute time range (eg: last 30 minutes), i get no search result.

**Comment by plt-sun** [comment]
Searching "relative", last 30 minutes, search query:
![zwischenablage-1](https://cloud.githubusercontent.com/assets/12797420/8668328/43a07900-2a0a-11e5-88fb-d5002ff19c5b.jpg)
Searching "keyword", last 30 minutes, search query:
![zwischenablage-2](https://cloud.githubusercontent.com/assets/12797420/8668337/585e79b4-2a0a-11e5-866c-29886290c0db.jpg)

seems identical, but with last search i get no search result. running Graylog 1.1.4 from OVA Image

**Comment by edmundoa** [comment]
Hi,

Did you try to recalculate the index time ranges (System -> Indices -> Maintenance -> Recalculate index ranges) and check if the query still return no result?

**Comment by plt-sun** [comment]
ahh, ok. recalculating index range solving the problem. Now, all searches (keyword and absolute) provide results
