### ISSUE TITLE
Streams & Dashboards access to specific users

### ISSUE THREAD

**Issue by Kumaravel2904** [Graylog2/graylog2-web-interface#1534]
Hi

Can we assign users with custom administrative access in Graylog.
For Example : A user abc should be given administrative access to one Stream and should be able to create his /her own custom dashboards as per requirement without depending on the  administrator.

Please let me know whether it is possible?

**Comment by edmundoa** [comment]
Hi,

It is not possible to do that in the web interface, but you can achieve something like that by using the Graylog server REST API to manage the user permissions. You can find more information about the REST API by going to `http://<graylog-server-host>:12900/api-browser`, and here is a list of available permissions: https://github.com/Graylog2/graylog2-server/blob/1.1.4/graylog2-shared/src/main/java/org/graylog2/shared/security/RestPermissions.java#L35-L115

Please use our [mailing list](https://groups.google.com/forum/#!forum/graylog2) or [IRC channel #graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog) for further questions, as we keep Github to track bugs.
