### ISSUE TITLE
qcow2 Installation on Openstack 

### ISSUE THREAD

**Issue by ivangerard** [Graylog2/graylog2-web-interface#1536]
Anyone has experience in deploying Open Stack  ? 

I tried installing Graylog2 using qcow installation on my Openstack Server, but I had a problem when i try to access it, it says they need password and public key.

FYI. I already put .pem correctly but they still need password, I already tried password: ubuntu,admin.

Does anyone have a same issue with me ?

**Comment by mariussturm** [comment]
Wrong repo, please have a look here: https://github.com/Graylog2/graylog2-images/issues/74
