### ISSUE TITLE
Better handling of linebreaks in message and fullmesssage

### ISSUE THREAD

**Issue by gloeglm** [Graylog2/graylog2-web-interface#1538]
Currently messages and fullmessages with linebreaks are displayed very badly in both the search and message screens. Especially java exception stack traces are close to unreadable. Here is an example of how it looks now (in the message screen):

![graylog_messages](https://cloud.githubusercontent.com/assets/2007505/8850873/d4a17d08-314b-11e5-95f5-8770ebd7c085.PNG)

Here is how I think it should look (I changed it with Firebug):

![graylog_messages_want](https://cloud.githubusercontent.com/assets/2007505/8850914/1b07966a-314c-11e5-87bf-31e01469db25.PNG)

I already made some attempts at fixing this in an old pull request: https://github.com/Graylog2/graylog2-web-interface/pull/899 but I didn't have the time to follow up on the feedback.

**Comment by edmundoa** [comment]
Hi,

Which Graylog version are you using? This was fixed in 1.1.2: https://github.com/Graylog2/graylog2-web-interface/pull/1446

**Comment by gloeglm** [comment]
Sorry, also just found the issue: https://github.com/Graylog2/graylog2-web-interface/issues/612 - Thanks!
