### ISSUE TITLE
Adding widgets changes saved dashboard layout.

### ISSUE THREAD

**Issue by IgoBoerrigter** [Graylog2/graylog2-web-interface#1543]
Could adding new widgets results in the widget showing up at the bottom of the dashboard. Leaving the existing widgets in the same order.

**Comment by edmundoa** [comment]
Which Graylog version are you using? We did some improvements on that regard in 1.1, as you can see in #873.

**Comment by IgoBoerrigter** [comment]
im using 1.1 but im still experiencing these issues

**Comment by IgoBoerrigter** [comment]
It is possible that only widgets created in older version of graylog fail in this case.
So:
Adding new widgets to a dashboard with widgets created in older version of graylog.

I will check this and report back to you.

**Comment by edmundoa** [comment]
The behaviour for widgets sorting in dashboards changed in Graylog2/graylog2-server#2093, and should have fixed this issue. Please reopen or comment if it still occurs in 2.0.x.

Thank you!
