### ISSUE TITLE
Vm Appliance Storage Expansion

### ISSUE THREAD

**Issue by cpaunescu** [Graylog2/graylog2-web-interface#1545]
I have installed Graylog2 via the VM Appliance Package. Ive tried to install it manually, but no success. Anyway, the appliance comes with only 20GB Primary HD where Graylog2 is installed, but 20GB is not enough for me. I need to expand the Graylog2 storage to about 200GB.
What would be the best way, and how can I go about it? I see in the notes that if I want more storage, I must mount another drive to /var/opt/graylog/data.
I have no clue how to do that part. Also, I cannot edit the VM Storage for Graylog2 appliance, as its grayed out.

Can someone tell me or give me a link to where it shows what to do? I would really appreciate the help.
Thanks....

**Comment by joschi** [comment]
Moved to the correct repository: Graylog2/graylog2-images#76

@cpaunescu Please subscribe the new issue at Graylog2/graylog2-images#76 to get updates on the issue.
