### ISSUE TITLE
/etc/sysconfig/graylog-web JAVA Parameter in RPMs

### ISSUE THREAD

**Issue by jgkirschbaum** [Graylog2/graylog2-web-interface#1553]
Using the `graylog-web-1.1.6-1.noarch.rpm`, maybe earlier versions have this bug also.

Setting the parameter `JAVA` to something like `/opt/java/bin/java` in `/etc/sysconfig/graylog-web` has no effect. The Javaversion to use is detected in `/usr/share/graylog-web/bin/graylog-web-interface` in the function `get_java_cmd`. This function only checks for the environment-variable `JAVA_HOME`.

A workaround for this issue is to add the following line to `/etc/sysconfig/graylog-web`:
```
export JAVA_HOME=/opt/java
```

**Comment by bernd** [comment]
I moved the issue to the fpm-recipes repository. https://github.com/Graylog2/fpm-recipes/issues/44
