### ISSUE TITLE
Not able to sign in to / (in 1.1.6 version)

### ISSUE THREAD

**Issue by Xat59** [Graylog2/graylog2-web-interface#1557]
Hi guys,

I just tried to access to / in the 1.1.6 version, but when I sign in the browser crashes down.
I'm able to sign in when I use different URI , for instance /dashboards .

I tried on Chrome and IE, but I get same result. The OS on which I tried is Windows Server 2k8 R2 .

Regards.

**Comment by joschi** [comment]
What does `crash down` mean exactly? Which versions of Chrome and Internet Explorer are you using?

**Comment by Xat59** [comment]
I'm using :
- Chrome 44.0.2403.155 m
- IE 11.0.22

I mean for Chrome my browser shows me a window with 2 button saying "Wait" or "Close".

**Comment by edmundoa** [comment]
Hi,

Could you please try using incognito mode in Chrome and loading the page while the developer tools are open? Please share any errors you may see in the console, as they might help us debugging the issue.

**Comment by Xat59** [comment]
So I logged into /dashboards instead succesfully, and now I'm able to sign in directly to / ...

**Comment by edmundoa** [comment]
I'm closing the issue then, please reopen if it happens again.
