### ISSUE TITLE
Bad help link on create new stream rule

### ISSUE THREAD

**Issue by sheavner** [Graylog2/graylog2-web-interface#1559]
From the streams / stream-name / rules page, clicking add stream rule creates a popup.  Inside the popup there's a bad link to "Take a look at the matcher code on GitHub" which leads to a github page not found. 

![image](https://cloud.githubusercontent.com/assets/1063975/9337939/082d9666-4597-11e5-8d2b-6203e594c316.png)

https://github.com/Graylog2/graylog2-server/tree/@Version.VERSION.getBranchName/graylog2-server/src/main/java/org/graylog2/streams/matchers

UI is from recent graylog docker distribution:   graylog-web-interface v1.1.4 (59783f6) (Oracle Corporation 1.8.0_45 / Linux 3.13.0-48-generic)

**Comment by dennisoelkers** [comment]
Fixed in 1a2eb8bb1947bfc8089eb5ac71fe15c813de03ef already.
