### ISSUE TITLE
"Users" submenu should now say "Users & Groups"

### ISSUE THREAD

**Issue by zexxon** [Graylog2/graylog2-web-interface#1567]
The "Users" sub-menu label under the "System" menu should be "Users & Groups"

**Comment by joschi** [comment]
There are no user groups in Graylog, but each user has to have one or more roles which can be edited on the System/Roles page.

**Comment by zexxon** [comment]
Did you mean "Users & Groups"? Many UI's I have used/seen with user group support (LDAP specifically) will label the menu "Users & Groups". However, if the belief that we don't logical groups for users in Graylog, even with LDAP group support is true then we shouldn't call it "Users & Groups".

**Comment by joschi** [comment]
I think mixing the terminology ("roles", "groups") is only a source of confusion. Internally (and everywhere in the UI) we currently use the term "role", so we should stick with it, IMHO.
