### ISSUE TITLE
Stacked Charts shouldn't display negative values unless there are negative values

### ISSUE THREAD

**Issue by zexxon** [Graylog2/graylog2-web-interface#1568]
Stacked Charts shouldn't display negative values in the Y axis unless there are negative values.
![screen shot 2015-08-24 at 8 57 06 am](https://cloud.githubusercontent.com/assets/1154318/9453266/cc904742-4a7e-11e5-9acd-a5a6419aed31.png)

**Comment by edmundoa** [comment]
I was playing with this some time ago, and I decided to leave it like this (it's the c3 default) for visibility reasons. When the x axis represents the 0 value and any of the lines have values close to 0, it's hard to see the line and the axis. Will play a bit with it and try to come up with a better solution.
