### ISSUE TITLE
tcp keepalive problem with graylog-web

### ISSUE THREAD

**Issue by jhaar** [Graylog2/graylog2-web-interface#1575]
Hi there

I think this has the same root cause as the following for graylog-server. Namely that the java tcp bind isn't doing TCP keepalives - which means horrible things happen

https://github.com/Graylog2/graylog2-server/issues/1287

What I'm seeing is that we are publishing our graylog-web through a reverse-proxy that is behind a Cisco ASA firewall. When a client connects directly to graylog-web, you typically see 4-5 ESTABLISHED tcp sessions. When we go through the reverse proxy, we see that head up into the THOUSANDS. This appears to be related to the ASA doing NAT and as (I suspect) graylog-web doesn't use TCP Keepalive, the ASA isn't triggering  the tear-down of TCP sessions, and so they accumulate until graylog-web actually becomes non-responsive (because it hits some internal max limit)

**Comment by joschi** [comment]
@jhaar You can enable/disable TCP keep alive for the Graylog web interface in your `application.conf` file. See https://www.playframework.com/documentation/2.3.x/ProductionConfiguration#Advanced-HTTP-server-configuration for details.
