### ISSUE TITLE
Creating empty role does not work

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-web-interface#1577]
Creating an empty role (no assigned dashboards/streams) does not work.

![screenshot from 2015-08-27 20 00 31](https://cloud.githubusercontent.com/assets/461/9528732/758cfa56-4cf6-11e5-9a4e-d747d9cc9607.png)

The same error occurs when the "ALL" stream is selected but neither of "Allow reading" and "Allow editing".

This is with:

* graylog-1.2.0-rc.2-SNAPSHOT-20150827151249
* graylog-web-interface-1.2.0-rc.2-SNAPSHOT-20150826162253

**Comment by kroepke** [comment]
fixed by https://github.com/Graylog2/graylog2-web-interface/commit/958051e4dde40ef7f81fe123156d828aa4d6a9f6
