### ISSUE TITLE
Individual userpermission to streams and dashboards is broken

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1582]
Steps to reproduce:

- go to system/ users
- create new read only user
- give user permission to view and/ or edit streams/ dashboards

After updating user, the permission is not shown in the textfield, user can not view stream/ dashboard

Userpermission via `roles` is working.

**Comment by kroepke** [comment]
I cannot reproduce this issue, it works just fine for me.

**Comment by kroepke** [comment]
@florianvolle can you test this again with the current snapshots please?

**Comment by florianvolle** [comment]
Looks ok now
