### ISSUE TITLE
Graylog dashboard isn't responsive

### ISSUE THREAD

**Issue by PatrickHuetter** [Graylog2/graylog2-web-interface#1583]
We are using graylog dashboards to monitor some information on our tvs on a wall. This works fine, but there is a lot waste of space on the right side of the monitors. There is no possibility to place widgets on the right side of the dashboard.
![dsc_0111](https://cloud.githubusercontent.com/assets/1142911/9600051/f6f8a1d0-5098-11e5-9d29-8d4552e608e3.JPG)

**Comment by edmundoa** [comment]
Hi Patrick,

Widgets have a minimum width of 440 pixels, so the dashboard will leave some empty space on the right side if it can't fit any widget in there. Anyway, which Graylog version are you using? We made some improvements in 1.1 and 1.2 on dashboards that I think may help.

**Comment by PatrickHuetter** [comment]
Hi @edmundoa, thanks for your information. I've tested the new version and it is really better than our current graylog version.

**Comment by edmundoa** [comment]
Glad to help Patric, and good to hear that! :)
