### ISSUE TITLE
Group Object Class input box always blank

### ISSUE THREAD

**Issue by drewmmiranda** [Graylog2/graylog2-web-interface#1599]
In the new Group Mappings section of LDAP Settings, the Group Object Class input box is always empty, even after inputting a value and saving the page.

Group mappings do seem to work correctly, but the expected behavior is that this field shows its existing value.

v1.2.0-rc.2

**Comment by kroepke** [comment]
Could you please try with rc.4 which was released yesterday?

**Comment by kroepke** [comment]
Also this field was renamed to 'Group Search Pattern' to allow more specific search patterns in case LDAP contains many unrelated groups, that might be an issue, too.

**Comment by drewmmiranda** [comment]
That seems to fix it. My previous group mappings did get erased when upgrading from rc2 to rc4 but this seems like an edge case.

**Comment by drewmmiranda** [comment]
Closing since this input box behavior has changed with the 1.2rc4 release.
