### ISSUE TITLE
Problem with changing statistical function of field chart 

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-web-interface#1604]
I generated a chart for a field in the search UI, changed the value to "total" and added the chart to a dashboard. The widget on the dashboard looks correct (same as in the search UI) and the database entry for it looks like this. (`"valuetype": "total"`)

```json
		{
			"creator_user_id" : "admin",
			"cache_time" : 10,
			"description" : "Field graph",
			"id" : "e70fbc12-efe3-4f9c-a859-c99856166ec3",
			"type" : "field_chart",
			"config" : {
				"valuetype" : "total",
				"timerange" : {
					"type" : "relative",
					"range" : 3600
				},
				"renderer" : "area",
				"interpolation" : "linear",
				"field" : "nf_bytes",
				"query" : "*",
				"interval" : "minute"
			}
		}
```

Then on the dashboard I changed the "Statistical function" of the widget to "Mean" and then back to "Total". Now the widget looks different and the database entry has `count` instead of `total` for the `valuetype` config option.

```json
		{
			"creator_user_id" : "admin",
			"cache_time" : 10,
			"description" : "Field graph",
			"id" : "e70fbc12-efe3-4f9c-a859-c99856166ec3",
			"type" : "field_chart",
			"config" : {
				"valuetype" : "count",
				"timerange" : {
					"type" : "relative",
					"range" : 3600
				},
				"renderer" : "area",
				"interpolation" : "linear",
				"field" : "nf_bytes",
				"query" : "*",
				"interval" : "minute"
			}
		}
```

Is this a bug or just confusing naming of the statistical function? I expected to get the `"valuetype": "total"` back when I changed the statistical function back to "Total".

**Comment by edmundoa** [comment]
Apparently there is some mix up with the statistical values used in the statistical widgets and field charts, I can confirm this issue.
