### ISSUE TITLE
Mongodb down.

### ISSUE THREAD

**Issue by Pompelpilt** [Graylog2/graylog2-web-interface#1611]
Dear All.

I'm a Complete newbie here, so I may be putting this at the wrong place. If that's the case, please let me know.

I'm running Graylog as server in VMWare using the OVA available from graylog.org. I upgraded the installation to Graylog 1.2 last week and after a reboot, the 'sudo graylog-ctl status' command states that mongodm is Down. 

I have searched mongodb.org to no avail. I have not come across anything that can help me resolving this issue. Is this the right place for this type of problems?

Regards

**Comment by joschi** [comment]
We try to use GitHub issues exclusively for bug reports and feature requests.

Kindly post your questions to [our mailing list](https://groups.google.com/forum/#!forum/graylog2) or [our IRC channel #graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog).
