### ISSUE TITLE
Field charts use bucket size/resolution of main histogram

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1619]
This is confusing because the resolution selector is clearly bound to the histogram. It should have a resolution setting in the _Customize_ dropdown.

**Comment by edmundoa** [comment]
They should only use the resolution from the histogram on the first load, but they have a resolution selector in the customise dropdown:
<img width="1261" alt="screen shot 2015-10-06 at 16 43 47" src="https://cloud.githubusercontent.com/assets/716185/10311992/7820b740-6c49-11e5-999d-7f2f35ff518a.png">

I'm closing this issue, please reopen if I misunderstood something :)
