### ISSUE TITLE
Graylog Collector on Windows Server 2012 R2

### ISSUE THREAD

**Issue by gprade** [Graylog2/graylog2-web-interface#1624]
C:\graylog-collector> bin\graylog-collector-service.bat install GraylogCollector
C:\graylog-collector> bin\graylog-collector-service.bat start GraylogCollector

dont work on Windows Server 2012 R2

i tried with graylog-collector-0.4.1

**Comment by joschi** [comment]
Please create a bug report for this at https://github.com/Graylog2/collector/issues/new and include all information about the failed start, e. g. error messages on the command line, error messages in the Windows Event log, how you've installed the Graylog Collector etc.
