### ISSUE TITLE
JSON key containing spaces does not become a searchable tag

### ISSUE THREAD

**Issue by tgalyean** [Graylog2/graylog2-web-interface#1625]
When submitting a JSON object to Graylog2 via the Gelf UDP input your keys will not be searchable tags unless they are a single string. 

Example:
# This works
{
    "testKey": "value"
}

# This does not
{
    "test Key": "value"
}

The content will still show up in the message field but again will not be a tag. I suspect its due to the fact that the key is an array and not a string but I have not yet dug into the code for further explanation.

**Comment by tgalyean** [comment]
Working Sample:
![screenshot 2015-09-29 11 55 35](https://cloud.githubusercontent.com/assets/355280/10175039/b3797df2-66a1-11e5-9ecb-6263e824dcf1.png)

Example Bug:
![screenshot 2015-09-29 11 55 41](https://cloud.githubusercontent.com/assets/355280/10175056/c5033072-66a1-11e5-9dcf-f5e7c4ce405c.png)

**Comment by joschi** [comment]
Are you using any extractors on those messages? Could you please post a complete example of the GELF messages you're sending to Graylog?

**Comment by tgalyean** [comment]
Unfortunately I cannot post the content due to the sensitivity of the data. But no I am not using any extractors. Just a simple search matching a particular tag in the data.

Heres a sample of this behavior. Create a Gelf HTTP input and run the following against your graylog instance:

This works:
curl -X POST http://<hostname>:12202/gelf -d '{"hostname":"example.org","data":"some data here"}' -v
![screenshot 2015-09-30 08 15 46](https://cloud.githubusercontent.com/assets/355280/10197264/972128d0-674b-11e5-8af8-bfb3a430cb57.png)


This does not:
curl -X POST http://<hostname>:12202/gelf -d '{"host name":"example.org","data":"some data here"}' -v
![screenshot 2015-09-30 08 15 52](https://cloud.githubusercontent.com/assets/355280/10197256/8b38ee9a-674b-11e5-8920-18bcdb0a93c8.png)


If you use these two examples you will notice that in your Graylog UI you will see "hostname" as a searchable tag with example.org as the key. The second example where you have 'host name' instead of 'hostname' the key and value will be entirely omitted from the UI output.

**Comment by joschi** [comment]
Ah, I see. The current GELF specification (https://www.graylog.org/resources/gelf/) describes additional fields as:
> Allowed characters in field names are any word character (letter, number, underscore), dashes and dots.

So rejecting this message field is well within the specification.

This being said, I think we should allow keys with spaces (and underscores) but it's more a thing for the next version of the GELF specification (related issue: Graylog2/graylog2-server#668). For the current version of the GELF specification, I can only recommend to replace the spaces in your messages with either a dots (`host.name`) or hyphens (`host-name`).

**Comment by tgalyean** [comment]
Understood. That makes perfect sense. Should we leave this open or append the request to #668?

**Comment by joschi** [comment]
@tgalyean Since this issue is now linked to the other one, this should suffice.

**Comment by tgalyean** [comment]
Perfect thanks
