### ISSUE TITLE
Allow to set refresh interval of quickvalue displays

### ISSUE THREAD

**Issue by Ikke** [Graylog2/graylog2-web-interface#1627]
The current interval seems like ~2 seconds. When several people leave these pages open with bigger queries, this can be quite taxing on the system.

Could an option be added to change the default interval?

**Comment by edmundoa** [comment]
Hi,

Thank you for suggesting this!

To be honest, I have my doubts that having even more configuration variables is really helpful, as in the end there are thousands of parameters to tweak. Having said that, what would you think if we reverse the functionality as it is now? That means, the data would not be refreshed initially, and the user would have to click on a button to enable auto-refresh explicitly.

**Comment by Ikke** [comment]
Yes, that would be fine too for us.
