### ISSUE TITLE
NumberFieldComponent do not accept negative or empty values

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-web-interface#1628]
On the current master, and most likely on 1.2, there are issues with the `NumberFieldComponent` component:

- It is not possible to leave optional numeric fields out, the value defaults to 0
- It is not possible to type negative numbers

Both issues seem to be related to the changes we did in #1596, so we should find a better solution for that.

**Comment by joschi** [comment]
Fixed by merging #1641.
