### ISSUE TITLE
Graylog Sources Tab always showing Error "Could not load histogram Data"

### ISSUE THREAD

**Issue by essence-it** [Graylog2/graylog2-web-interface#1633]
Hi,

I have 2 Graylog Servers both running ES instances. However, after 1-2 days of running, my Elasticsearch cluster always goes "No Active Master" (Using KOPF) for about 10-15 minutes, then comes back up.

When it comes back up, i can NEVER search for Sources. I get this Error:

Could not load histogram data
Loading of histogram data failed with status: Bad Request

However, if i select time to " All Week, or All month", data shows up, but sometimes doesn't show the messages when you query it from the source. The only way to fix this is to restart ES on the Master then everything comes back up and works fine.

Could someone help me?

So far i've increased Ram to 16GB on each Machine and dedicated 7GB Heap to each one as i thought it would be RAM. However, after a few days each machine has about 500-900MB of RAM free. They are both on Linux Ubuntu 14.04 Machines.

Thanks (Errors Below)

ES KOPF LOG:
[2015-10-05 13:44:48] {"status":503,"name":"ess-lon-gray-002_slave","cluster_name":"graylogemea","version":{"number":"1.4.5","build_hash":"2aaf797f2a571dcb779a3b61180afe8390ab61f9","build_timestamp":"2015-04-27T08:06:06Z","build_snapshot":false,"lucene_version":"4.10.4"},"tagline":"You Know, for Search"}
[2015-10-05 13:44:48] No active master, switching to basic mode

**Comment by joschi** [comment]
@essence-it Kindly use [our mailing list](https://groups.google.com/forum/#!forum/graylog2) or [join #graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog) for support around Graylog. We try use GitHub issues exclusively for bug reports and feature requests.
