### ISSUE TITLE
Top Values of a particular field

### ISSUE THREAD

**Issue by just5guy** [Graylog2/graylog2-web-interface#1635]
I am using Graylog2 to log and report on my Home Energy Monitor. I would like a way to put the Top values of an extracted field for a given time period on the Dashboard. Say my last 5 Watt Readings were 1025, 956, 725, 1240, 540. I would like a way to report on the Top, and Bottom Values on the Dashboard for a given time period (Today, Yesterday, The Last 7 Days...)

**Comment by edmundoa** [comment]
Hi,

I think you could use quick values or field statistics to add those values to your dashboard. Take a look at [our documentation](http://docs.graylog.org/en/1.2/pages/queries.html#analysis) for more information.

We only use Github as a way of tracking bugs in our code, so I kindly ask you to use [our mailing list](https://groups.google.com/forum/#!forum/graylog2) or [our IRC channel #graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog) if you have further questions about Graylog.
