### ISSUE TITLE
Unable to delete saved searches that return no results

### ISSUE THREAD

**Issue by dustintennill** [Graylog2/graylog2-web-interface#1639]
Hello,

I am using: graylog-web-interface v1.2.1 (c301e97) (Oracle Corporation 1.7.0_79 / Linux 3.19.0-25-generic) and the matching graylog-server code. 

While using the saved searches feature, I can't seem to figure out how to delete a saved search that doesn't have any results. I have attached a screenshot. 

Am I missing something obvious in the GUI?

Thanks !!

![screen shot 2015-10-10 at 8 08 03 pm](https://cloud.githubusercontent.com/assets/9064880/10413911/e9c7c188-6f8a-11e5-82df-e025529a4b51.jpg)

**Comment by sonoflo** [comment]
I'm in same case as you, can't delete an empty saved search (and can't update this search too)

Any clues will be much appreciated !

**Comment by edmundoa** [comment]
Hi,

Thank you for reporting this!

You are not missing anything, there are some buttons missing when the search is not returning results. While we work on it, you could delete the document for the saved search in MongoDB directly, it is stored in the `saved_searches` collection.

**Comment by dustintennill** [comment]
Fantastic - I will do that for the interim.

**Comment by jzinkweg** [comment]
I've worked around this by sending in a log message matching the search filter (by hand).
This way I did not need access to mongodb.

I used a really ugly AWK command to convert the filter to json (GELF UDP in this case):

    # version, host and short_message are required fields
    FILTER="facility:some\-facility AND version:1.1 AND host:example.org AND short_message:test"
    echo $FILTER | awk 'BEGIN { RS=" AND " ; FS=":" ; print "{" } NR > 1 { print "," }  { gsub(/"|\n|\\/, "", $2); printf "\""$1"\":\""$2"\"" } END { print "\n}" }' | gzip | nc -u -w 1 graylog-server.example.org 12201

**Comment by kaiserboss** [comment]
Hi,

I have the same problem.

How do you access the mongoDB saved_searches?

When I start mongo and execute "show collections" there is no results.

Regards.

**Comment by joschi** [comment]
@kaiserboss Check that you are in the correct MongoDB database. The `mongo` CLI connects to the database `test` by default.

**Comment by kaiserboss** [comment]
@joschi Thank you very much I was not connected to the right db.

**Comment by suhasagarwal12** [comment]
Hi @edmundoa Any updates on when we are going to release this delete functionality for no searched results ?

**Comment by edmundoa** [comment]
Hi @suhasagarwal12,

I'll put it in the 2.0 milestone, hopefully we can fix this by then.

**Comment by evitorbarros** [comment]
+1

**Comment by suhasagarwal12** [comment]
Any updates on this issue please ?

**Comment by hc4** [comment]
Why the only opened bug leaved in graylo-web-interface repo, which is considired DEPRECATED?
Will any one find it here to fix?

**Comment by edmundoa** [comment]
@hc4 Yes, we will. The web interface still exists, but now it's quite different and lives in the Graylog server repository, so new issues should go in there. Old issues are still here, but that doesn't mean we will forget about them :)

**Comment by hc4** [comment]
Is this also fixes non-working update (even if search result contains data)?

**Comment by edmundoa** [comment]
@hc4 which non-working update? This issue is about deleting saved searches when no results are found, and that was fixed. Please take a look at https://github.com/Graylog2/graylog2-server/pull/2253 for more details on the actual changes that were made, or open a new ticket if there is any other issue you are experiencing.

**Comment by hc4** [comment]
I talk about second part of task https://github.com/Graylog2/graylog2-server/issues/2184 (it was closed as duplicate of this one).

**Comment by edmundoa** [comment]
No, that didn't change, and it's also not easy to fix without changing how we manage saved searches. At the moment, changes in the search query or time range require creating a new saved search, and deleting the old one. You can do it with the REST API though...

Please create a new ticket in the server repository If that is still an issue for you. In that way it won't get lost in a closed issue, and it's also easier to understand when only one issue is described in there.

**Comment by hc4** [comment]
Created https://github.com/Graylog2/graylog2-server/issues/2285
