### ISSUE TITLE
Graylog: set inter default value with GROK for a string field

### ISSUE THREAD

**Issue by kaiserboss** [Graylog2/graylog2-web-interface#1644]
Hello,

I would like to generate charts from string value: "AUDIT_SUCCESS" and another charts for "AUDIT_FAILURE"

The objective is to generate a combine graph with those two charts. But I cannot do that because they are string fields.

As a consequence, is there a way to set default value for the string AUDIT_SUCCESS to 1 and AUDIT_FAILURE to 0 with grok pattern?

Regards.

**Comment by edmundoa** [comment]
Hi @kaiserboss,

Kindly use [our mailing list](https://groups.google.com/forum/#!forum/graylog2) or [join #graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog) for support questions about Graylog. We try to keep GitHub issues exclusively for bug reports and feature requests.

**Comment by joschi** [comment]
For the sake of completeness: https://groups.google.com/d/msg/graylog2/Pyo1NMKHr4c/69_Tr2BACwAJ
