### ISSUE TITLE
sysconfig custom settings not being honored

### ISSUE THREAD

**Issue by bryangwilliam** [Graylog2/graylog2-web-interface#1645]
I have installed graylog-web-1.2.1-1.noarch RPM on CentOS 6.

The provided init.d script for graylog-web is not honoring custom settings in /etc/sysconfig/graylog-web. For example, when I set GRAYLOG_WEB_HTTP_PORT="3000" in the sysconfig file it will still start up on the default port 9000.

It appears to be due to the fact that the JAVA_OPTS variable is built before the settings are included, so it sticks with the defaults from the top of the init script rather than those set in the sysconfig file.

**Comment by joschi** [comment]
Good catch. Thanks for reporting!

This has been fixed in Graylog2/fpm-recipes@3e4e7ab09f938f90c2dee3e0dd572747ecf16425 and will be pushed to the package repository soon.
