### ISSUE TITLE
Could not generate chart using values from extractor

### ISSUE THREAD

**Issue by fluancefg** [Graylog2/graylog2-web-interface#1646]
Hi,

I've an extractor which extracts the values xxx from the string xxx req/s, then convert them to numeric using the converter.
When I display the values in the stream, they look good like numeric values, however when I try to use the generate chart function, I get the following error message:
Could not create field graph. Field graphs are only available for numeric fields.

What's wrong with those converted values ?

**Comment by edmundoa** [comment]
Hi,

Kindly use [our mailing list](https://groups.google.com/forum/#!forum/graylog2) or [join #graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog) for support questions about Graylog. We try to keep GitHub issues exclusively for bug reports and feature requests.
