### ISSUE TITLE
Migrate web interface to react

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-web-interface#1648]
In order to remove the play dependency all of the UI code will be migrated to react components.

This is the top level issue to track the remaining tasks.

- [ ]  #1647

**Comment by kroepke** [comment]
completely useless thanks to github issues.

**Comment by edmundoa** [comment]
![](https://33.media.tumblr.com/9623d4ab00c74f027e6cd1e23e1d5126/tumblr_inline_nshd2hgJNy1raprkq_500.gif)

**Comment by joschi** [comment]
![computers…](http://31.media.tumblr.com/cfa551b07124dcb048f257b33547a7be/tumblr_nv17xc7sbk1s373hwo1_500.gif)
