### ISSUE TITLE
replay search from dashboard works only for Admin user

### ISSUE THREAD

**Issue by gm3dmo** [Graylog2/graylog2-web-interface#1649]
Using graylog 1.2.1 when users click on replay search in a dashboard, they are taken to the page for the stream. If I do this as an admin user then the search is replayed.

**Comment by edmundoa** [comment]
Hi,

This is not a bug, but a problem with user permissions: regular users have no permission to access the global search page by default, only a series of streams and dashboards. When they click on the replay link, Graylog check their permissions, and they get redirected to their start page.

At the moment there is no option in the web interface to enable those permissions, but you can look in [this thread](https://groups.google.com/forum/#!searchin/graylog2/permissions$20search/graylog2/lG2nz4T9TFA/Zn-gfOXljosJ) of our mailing list to see some solutions.

I will open a new issue to remind us that we need to enable a way of setting extra permissions to users in the web interface.
