### ISSUE TITLE
First start splash page

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-web-interface#1652]
To support aiding users in being more successful when using Graylog for the first time we need to have a welcome page.

The page must only been shown once during initial setup of the system, but still be accessible via some menu or page later on.

If technically possible integrate some content from the graylog.org website into the initial splash page to further optimize the content a new user sees. This lets us help more users being more successful without having to release too many versions.
The online content must be optional and not visually impact the UI if it is not available due to firewall issues, slow connections or downtime of the site itself.

see Graylog2/graylog2-server#1497, Graylog2/graylog2-server#1496

**Comment by edmundoa** [comment]
Fixed in https://github.com/Graylog2/graylog2-web-interface/pull/1700
