### ISSUE TITLE
Special Character double escaping bug

### ISSUE THREAD

**Issue by renapu** [Graylog2/graylog2-web-interface#1654]
Hi,

we have to search messages that have a => or <= in the message section, here are my searches:

application_name:exim AND =>   leads to: "query": "application_name:exim AND =>",
application_name:exim AND "=>" leads to: "query": "application_name:exim AND \"=>\"",
application_name:exim AND '=>' leads to: "query": "application_name:exim AND '=>'",
application_name:exim AND \=\> leads to: "query": "application_name:exim AND \\=\\>",

i've tried some more and even with the message: field but i will never get the right messages. Is this a Bug or do i search wrong?
Example Msg: 2015-10-22 10:17:23 asdf-asdf-RT <= xyz@xyz.at H=xyz.net [xxx.xxx.xxx.xxx] P=esmtp S=xyz

Thanks

**Comment by joschi** [comment]
@renapu Kindly post general support questions to [our mailing list](https://groups.google.com/forum/#!forum/graylog2) or [join #graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog).
