### ISSUE TITLE
Search doesn't work on my graylog web interface

### ISSUE THREAD

**Issue by kamalakarv** [Graylog2/graylog2-web-interface#1660]
I am using graylog web interface 1.2.0 and can see there are some error in client side console 

GET https://xx.xxx.xxx.xx/a/metrics/info?t=1445854782786   Aborted 	7.26s

Any help appreciated 

Regards
KV

**Comment by edmundoa** [comment]
Hi,

The error you see in the console is related to metrics, not search. Are you running some proxy or load balancer in front of the web interface? That's the most likely source of troubles with metrics. Take a look here for more information: http://docs.graylog.org/en/1.2/pages/load_balancers.html#web-interface

We only use Github as a way of tracking bugs in our code, so I kindly ask you to use [our mailing list](https://groups.google.com/forum/#!forum/graylog2) or [our IRC channel #graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog) to get further support on this issue. Thank you!
