### ISSUE TITLE
allow user with read rights to set dashboard as start page

### ISSUE THREAD

**Issue by Armadill0** [Graylog2/graylog2-web-interface#1681]
I recently discovered, that you can't set dashboards as the user's start page if the user only has read rights for the dashboard. The menu simply isn't displayed.

As this doesn't belong to editing the dashboard itself, I think this should also be possible for users who only have read rights for the dashboard.

Read rights:
![gl-no-setdashboard](https://cloud.githubusercontent.com/assets/6536990/11067195/b5bf61b2-87cb-11e5-9668-4fc727a742d5.jpg)
Edit rights:
![gl-setdashboard](https://cloud.githubusercontent.com/assets/6536990/11067196/b5c04186-87cb-11e5-9050-1c4a83ae5754.jpg)

**Comment by edmundoa** [comment]
Fixed in 27c5c18.
