### ISSUE TITLE
Add custom actions to search results and messages

### ISSUE THREAD

**Issue by cstuder** [Graylog2/graylog2-web-interface#1683]
I would like to have the possibility to define custom actions in the search result pane on the right (Button 'More actions') and on the messages view (Buttongroup to the right, ending with 'Test against stream')

In particular I would love to be able to directly create an issue in an external bug tracking application (In our case Jira) automatically from a search result or a particular action. Right now I spend a lot of time copying permalinks around.

As far as I can see, there's currently no plugin type which can modify the webinterface this way.

**Comment by edmundoa** [comment]
Hi,

I think this request basically wants to solve the same problems as #1447, just in a different way. I will therefore close this issue and kindly ask you to add any comments in the linked one.

**Comment by cstuder** [comment]
I've created a feature request here: https://graylog.ideas.aha.io/ideas/GL2E-I-471
