### ISSUE TITLE
Change IP address graylog2

### ISSUE THREAD

**Issue by raymondkops** [Graylog2/graylog2-web-interface#1701]
Hello I am not used to unix editors and permissions. I have read the documentation how th change the ip address for the graylog server. I need to change the interfaces file from dhcp to static. I cannot make the changes since the file is read only. If I change the permissions of the file (i found it on google) the file gets deleted and I am not able to create a new file. Could some tell me how the save the interfaces file,please ? I am logging in with the ubuntu user account as described in the documentation.

Thank you very much in advance !
 kind regards

**Comment by joschi** [comment]
@raymondkops Kindly post your problem to [the mailing list[(https://groups.google.com/forum/#!forum/graylog2) or [join #graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog) to discuss your problem. The GitHub issue tracker is reserved for bug reports and feature requests.
