### ISSUE TITLE
[Graylog2] Timestamp different with timestamp

### ISSUE THREAD

**Issue by HitsuYaga** [Graylog2/graylog2-web-interface#1703]
Dear all,
I have problem with field timestamp when I got a log message as picture below: 
![image](https://cloud.githubusercontent.com/assets/16111095/11521193/aae9337c-98dc-11e5-891a-0d213ce31615.png)

filed timestamp now is UTC format differ with Timestamp filed is GMT+7 (our local time). So when I use alert mail, it have problem about trigger date.
![image](https://cloud.githubusercontent.com/assets/16111095/11521267/4acbc4d6-98dd-11e5-86e9-1ef16de4420a.png)

Please help me to fix it!!! Thanks

**Comment by joschi** [comment]
@HitsuYaga Graylog is always storing the timestamp of log messages with the timezone UTC. The Graylog web interface then uses the configured timezone of the logged in user (GMT+7 in your case) to display the timestamp in their timezone.

As far as I see from your screenshots and your description, everything is working as intended (message timestamps in UTC, local times and dates in your timezone).
