### ISSUE TITLE
Not able to compare field values of 2 messages

### ISSUE THREAD

**Issue by ghost** [Graylog2/graylog2-web-interface#1714]
Hi Team,

I am not able to find any documentation on how to compare field values of 2 or more messages. Could you please help me how this can be achieved?

I want to display messages whose field values match.

Thanks,
Prakash M

**Comment by edmundoa** [comment]
Hi,

We use Github for bug tracking, kindly ask in our [mailing list](https://groups.google.com/forum/#!forum/graylog2) or [#graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog) for further questions.
