### ISSUE TITLE
Dashboard Quick Values Truncated in Widget

### ISSUE THREAD

**Issue by zachsis** [Graylog2/graylog2-web-interface#1715]
Hi, 
When we use the Quick values as a dashboard widget, it displays only 50 items in the value the rest of the unique events are not shown. When the search query is changed to ignoring few patterns of the current values, we get to see new events that were truncated from the dashboard. 
Does the Widget have limitations to display a maximum of 50 entries or is there a setting to increase this threshold?

Thanks, 
Zach

We are running graylog-web-interface v1.2.1

**Comment by edmundoa** [comment]
Hi,

There is a hard limit on the number of elements returned by the quick values widget, as it is a pretty expensive operation (specially when there are many logs or values for that field). At the moment there is no setting to increase the threshold, the limit is in the code, as you can see in: https://github.com/Graylog2/graylog2-server/blob/1.2/graylog2-server/src/main/java/org/graylog2/dashboards/widgets/QuickvaluesWidget.java#L91

We use Github for bug tracking, kindly ask in our [mailing list](https://groups.google.com/forum/#!forum/graylog2) or [#graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog) for further questions about this.

**Comment by edmundoa** [comment]
As I saw more people are asking for this, I added a feature request on the server, please feel free to add any related comments in there: https://github.com/Graylog2/graylog2-server/issues/1684
