### ISSUE TITLE
Export current configuration to new server

### ISSUE THREAD

**Issue by ghost** [Graylog2/graylog2-web-interface#1720]
Hi 
Is there a way to export configuration from the webui and import them  back ? 
Thanks

**Comment by joschi** [comment]
You can export inputs (including extractors and grok patterns), outputs, streams, and dashboards using the content pack feature of Graylog (see System -> Content packs).

**Comment by dsever** [comment]
Hi, but is there anyway to export notifications, and alerts?

Dubravko

**Comment by joschi** [comment]
@dsever We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
