### ISSUE TITLE
Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by Aleyasen** [Graylog2/graylog2-web-interface#1722]
In branch 1.3 I ran build_release.sh and got the following error: 
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/repos/graylog2-web-interface/javascript/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-15-generic
gyp ERR! command "/usr/bin/nodejs" "/opt/repos/graylog2-web-interface/javascript/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/repos/graylog2-web-interface/javascript/node_modules/c3/node_modules/d3/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v5.4.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
npm ERR! Linux 3.19.0-15-generic
npm ERR! argv "/usr/bin/nodejs" "/opt/repos/graylog2-web-interface/javascript/node_modules/.bin/npm" "install" "--no-spin"
npm ERR! node v5.4.1
npm ERR! npm  v2.14.14
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/repos/graylog2-web-interface/javascript/npm-debug.log

I use the following versions:
# node --version

v5.4.1
# nodejs --version

v5.4.1
# npm --version

3.5.3

tail -n1000 javascript/npm-debug.log : https://gist.github.com/anonymous/fb65595d1c238ee3f2d2

**Comment by joschi** [comment]
Try using an older node.js version (e. g. node.js 0.12.x) for building this project. You can take a look at the [`.travis.yml`](https://github.com/Graylog2/graylog2-web-interface/blob/1.3.3/.travis.yml) file for a description of the build environment.

Other than that, I'm afraid we can't provide any support for setting up your local build environment.
