### ISSUE TITLE
Dedup values of one extracted filed

### ISSUE THREAD

**Issue by vranjith009** [Graylog2/graylog2-web-interface#1724]
I require to dedup all values of one extracted field called "Employee ID".

Is there any way to do this on graylog. Any can help on this please.

**Comment by joschi** [comment]
We try to use GitHub issues exclusively for bug reports and feature requests. Please discuss general support requests on [the mailing list](https://groups.google.com/forum/#!forum/graylog2) or [join #graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog).
