### ISSUE TITLE
Graylog search query for particular string

### ISSUE THREAD

**Issue by Karthikvasudev** [Graylog2/graylog2-web-interface#1730]
Hi there,

I am new to graylog , can any one help me write the query to search the particular string.. and the string is "ERROR c.t.eiddo.client.EiddoClient". If you could able to give me the heads up it will great to start with it. Thanks

**Comment by edmundoa** [comment]
Hi,

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
