### ISSUE TITLE
Missing data after upgrade

### ISSUE THREAD

**Issue by idanlerer** [Graylog2/graylog2-web-interface#1731]
Hello,
I just upgraded from Graylog v1.3.4 from1.1.3.
All my settings saved and I can see all my collection / dashboards ETC.
But I can't see all the data collected by the Graylong before the upgrade.
When I try to search old data before the upgrade I'm not getting any results.
On the disk, I do see the Graylog disk /dev/mapper/graylog--indices-graylog--indices have the same used space as it was before the upgrade.
Where is all my old data ? what I'm missing ?

**Comment by joschi** [comment]
@idanlerer We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog) and describe how exactly you did the upgrade and which configuration settings you've changed (or not changed for that matter). 

Thank you!
