### ISSUE TITLE
I reset my password in config file. NOw its working locally but not when accessing from other servers

### ISSUE THREAD

**Issue by tharasavio** [Graylog2/graylog2-web-interface#1733]
# Graylog Web Interface has moved

As of Graylog 2.0 the web interface has been merged into the [Graylog2/graylog2-server](https://github.com/Graylog2/graylog2-server/issues) repository. Please file any issues there.

The issues in this repository will not be updated but are preserved for reference reasons.

**Comment by joschi** [comment]
@tharasavio We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by tharasavio** [comment]
Hi , one quick question. Does all servers send logs using the same port say
5140 or do i need put each port for each serevs

On Mon, Jul 11, 2016 at 10:19 AM, Jochen Schalanda <notifications@github.com

> wrote:
> 
> Closed #1733
> https://github.com/Graylog2/graylog2-web-interface/issues/1733.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/Graylog2/graylog2-web-interface/issues/1733#event-718778975,
> or mute the thread
> https://github.com/notifications/unsubscribe/AL-LIxKIPzDlVktOhxL--2jqTci8JA86ks5qUlEEgaJpZM4JJaRK
> .

## 

thara

**Comment by edmundoa** [comment]
Hi @tharasavio,

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
