### ISSUE TITLE
Restart of Collector Sidecar causes Gaylog Server to Re-Process All messages

### ISSUE THREAD

**Issue by hryzec** [Graylog2/graylog2-web-interface#1734]
After change of collector configuration input using options "Read since start" & "Save read position" Gaylog server seems to receive all the log messages at once causing Graylog to fill in disk journal and hang the processing until messages are processed. This however should not happen as it is expected from collector and nxLog to not process messages older than collector restart and older than collector read position.

**Comment by edmundoa** [comment]
Hi,

This is not the right place to write collector sidecar issues. In fact, this repository is here only for legacy reasons. I have moved your issue [here](https://github.com/Graylog2/collector-sidecar/issues/46), please use that link to track its progress.

Thank you!
