### ISSUE TITLE
Timestamp mismatch

### ISSUE THREAD

**Issue by kboht** [Graylog2/graylog2-web-interface#1736]
Hello There,

Concerning log ingestion time stamps, we notice that the log entry timestamp and the event time stamp stamp don't quite match.  At this point it really only seems to be off by a few milliseconds.  I'm assuming that the log time stamp is the time the log was ingested into graylog (we used nxlog with collector-sidecar).  Just wanted to check in to see if there is something in our configuration we could have done differently to tighten up the difference?
![graylogtimestamp](https://cloud.githubusercontent.com/assets/19921073/18374176/4b9e99b8-7610-11e6-8a93-85809c079b22.png)

**Comment by joschi** [comment]
@kboht We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
