### ISSUE TITLE
Implement "tail -f" like live screen for searches.

### ISSUE THREAD

**Issue by r-duran** [Graylog2/graylog2-web-interface#377]
It is a killer feature for live debugging of services.

**Comment by edmundoa** [comment]
This is basically the same issue as #377, so I'm closing it now.

**Comment by hernandesbsousa** [comment]
@edmundoa #377 is the current issue, so which issue is this a duplicate from?

**Comment by edmundoa** [comment]
Sorry I messed up with the copy-paste, I meant issue #133.

**Comment by hernandesbsousa** [comment]
Thanks! I think they are a bit different though... An auto refresh every 5s for example is different from realtime, `tail -f` style stream.

**Comment by edmundoa** [comment]
I think both issues want to solve the same problem (seeing messages in "real time"). The way I see it, given an auto reload with configurable reload interval, `tail -f` only represents the particular case where the reload interval is 0.

**Comment by hernandesbsousa** [comment]
The way you just put it makes total sense :smile: thanks!

**Comment by proptiger-com** [comment]
Hi,

Is this feature live now??

**Comment by joschi** [comment]
@proptiger-com No. Please subscribe to #133 if you want to receive updates about the state of the feature.
