### ISSUE TITLE
ZOMG stream dashboards are completely missing

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#407]
A lot of people use that and we need to have it in v0.20.0 - Maybe a little app that uses the APIs?

**Comment by astral303** [comment]
Is there documentation for this? Looking at Widget.js seems like there is no widget type for a stream of recent messages.

**Comment by joschi** [comment]
@astral303 I guess they were referring to https://github.com/Graylog2/graylog2-stream-dashboard

**Comment by PatrickHuetter** [comment]
This should be integrated into graylog dashboard and it should be possible to filter special messages like in the graylog "Search" view. +1

**Comment by gab** [comment]
Throwing my humble vote in for putting back something that's integrated in the regular dashboards. Graphs are nice and all, but seeing the last 10 errors at a glance next to them is crucial information.

**Comment by edmundoa** [comment]
It is really hard to track this ideas into issues comment. Please add it to our ideas portal, where we can see how important this is for the community: https://www.graylog.org/product-ideas/
