### ISSUE TITLE
Map LDAP groups to admin or reader permissions

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#437]
Allow to define which LDAP group maps to Graylog2 admin accounts and what default group to map to.

Investigate if this is something to build relatively quickly. If it it isn't there is a fallback: Just allow to define that all LDAP users are reader by default.

**Comment by kubanczyk** [comment]
A minimal workaround. Please put a suggestion on a Configure LDAP screen. Now it already contains a red suggestion when Server Type is set to Active Directory: "For example (&(objectClass=user)(sAMAccountName={0})). The string {0} will be replaced by the entered username."

I propose to also add this in the same place:   "To allow only a specific group, please use (&(objectClass=user)(sAMAccountName={0})(memberof=CN=Graylog Users,OU=My Org,DC=example,DC=com))"

(I don't know if this is achievable or necessary on Server Type = LDAP or do we depend solely on Search Base DN there.)

**Comment by bernd** [comment]
We are working on this. Please track https://github.com/Graylog2/graylog2-server/issues/1321 for progress. Thank you!
