### ISSUE TITLE
GroupBy Display

### ISSUE THREAD

**Issue by erlichmen** [Graylog2/graylog2-web-interface#444]
A lot of time individual log lines make more sense in the context.

For example request to a webserver can trigger a lot of small logs that makes sense looking at them group by the request id.

One place were it is implemented very well is at Google App Engine, each log line is a root that contains all the logging requests the happened in the context of that root (in AppEngine case each root is a lifetime of a request).

GroupBy view will be very useful to understand end to end logging, I can give each log a parameter and later group by that parameter.

**Comment by edmundoa** [comment]
Closing this issue, as I understand it's the same as #150.
