### ISSUE TITLE
Pie charts!

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#453]

**Comment by XaeroDegreaz** [comment]
I notice that this has been removed from the milestones. Is this going to be placed back on the roadmap at some point? It would be extremely useful for grouping large datasets.

**Comment by ralfonso-directnic** [comment]
Perfect use case is seeing my http response codes by type, its ok for list format but if 404's spike its simpler to see the pie slice get larger on the dashboard

**Comment by timstott** [comment]
:+1: use case http response code display

**Comment by edmundoa** [comment]
Pie charts on quick values are coming on 1.1 and are already available on the RC.
