### ISSUE TITLE
Implement more widget types

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#473]

**Comment by cholcombe973** [comment]
+1 god yes

**Comment by beezoncheg** [comment]
Search results widget with selectable fields. At least for streams.

**Comment by kroepke** [comment]
Please don't vote for individual features here, instead use our Ideas portal at: https://graylog.ideas.aha.io/

It is basically impossible to keep track of requests in comments. I'll close this issue.
