### ISSUE TITLE
Add median as a statistic

### ISSUE THREAD

**Issue by nirvdrum** [Graylog2/graylog2-web-interface#497]
The set of basic stats is really helpful, but it's currently missing the median value.  If you could add this, that'd be really helpful.

**Comment by jsmucr** [comment]
ES's percentiles aggregation can be used here.

**Comment by onyxmaster** [comment]
This is super important for any logged timings. I understand that using some kind of time-series database is a "better" way, but we prefer graylog for being a good "boxed" solution.

**Comment by raghu999** [comment]
+1

**Comment by florianpopp** [comment]
This issue was moved to Graylog2/graylog2-server#3245
