### ISSUE TITLE
Chart legend should show field name when combining charts

### ISSUE THREAD

**Issue by nirvdrum** [Graylog2/graylog2-web-interface#507]
The chart legend shows the search query, while the chart title shows the message field name.  However, when combining multiple charts for the same search query, it becomes really hard to tell what each line is.  The chart legend will show the same query for each value and the chart title changes to "Combined chart", so there's no indication of which message fields are used.

**Comment by AyubAmino** [comment]
Dears,

Any solution for the above inquiry? Appreciate if you can shared solution if any.

thanks
