### ISSUE TITLE
Show full_message field in the Message Fields sidebar

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-web-interface#516]
All fields except full_message can be chosen from the fields sidebar - you have to select and individual message in order to expose the full_message field.

This is suboptimal for message types that aren't parsed correctly.

**Comment by sleske** [comment]
As of Graylog 1.1.6, "full_message" can be selected (see #1262).
However, the field is only listed if you click "List all fields" at the bottom of the field list.
That problem is currently also tracke in #1262.

So I suppose this ticket can be closed, as the original problem is fixed.

**Comment by joschi** [comment]
@sleske True. Thanks for updating this issue!
