### ISSUE TITLE
stop command for graylog2-web-interface

### ISSUE THREAD

**Issue by soudmaijer** [Graylog2/graylog2-web-interface#547]
Hi,

I am writing a chef cookbook for the new graylog2-web-interface (and rest of the graylog2 server package), I am almost done. 

I noticed that there is a bash script to start the server, but no command that can gracefully shutdown the server. Would it be possible to provide such a command, maybe add param to the bash script?

My chef cookbook can be found @ https://github.com/soudmaijer/graylog2

**Comment by Mohd0786** [comment]
Hi All,
 
getting this type error kindly suggests.
No Graylog servers available. Cannot log in

**Comment by joschi** [comment]
@Mohd0786 We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
