### ISSUE TITLE
Set default fields for search results, stream results

### ISSUE THREAD

**Issue by wattwood** [Graylog2/graylog2-web-interface#595]
The functionality from the prior versions of Graylog2 allowed for the display fields in search results to be saved as defaults.  Looking to have this re-added to RC1.

**Comment by RomeroMsk** [comment]
:+1:

**Comment by nexusVI** [comment]
+1

**Comment by alekseyp** [comment]
+1

**Comment by sentient** [comment]
++1

1. allow to define a default search result view (columns, order, width) including the custom user defined field selector

2. allow to define a search result view per steam (columns, order, width) including the custom user defined field selector

3. allow to define a search result view per dashboard  (columns, order, width) including the custom user defined field selector


*1 essential
2 would be nice
3 you are going all out

**Comment by davidnedved** [comment]
+++1

When doing an empty search (return all results) or a search for a keyword i.e. "logoff" it would be nice to specify the default fields that are visible on the returned results - It would be great if this could be applied on a per user level (user preferences?) and also at a global level.

**Comment by alexsnowb** [comment]
+1

**Comment by rubao** [comment]
+1

**Comment by edmundoa** [comment]
Please use our ideas portal [https://www.graylog.org/product-ideas/](https://www.graylog.org/product-ideas/) to vote for ideas, having +1s in Github is really noisy and ineffective.
