### ISSUE TITLE
Merged charts on dashboards

### ISSUE THREAD

**Issue by vzaritovsky** [Graylog2/graylog2-web-interface#604]
1. Please, add ability to create merged charts on dashboards
2. Also will be great to add own titles on merged charts ( i mean titles of the each graph ).
For example i want to add web application chart with hits, aggregated by urls.
Thank you.

**Comment by maniel** [comment]
:+1:
if i cannot pin them and add them to dashboard, what are they for? it's very important feature!:)

**Comment by aeoris** [comment]
@joschi @edmundoa any updates on this? Is it being considered for a future release?

**Comment by joschi** [comment]
Merged/stacked charts will be possible in Graylog 1.2.0.

Refs #1513.
