### ISSUE TITLE
Replace new-lines with line breaks when displaying messages (2)

### ISSUE THREAD

**Issue by dur3x** [Graylog2/graylog2-web-interface#612]
Hello I come back with this problem (see https://github.com/Graylog2/graylog2-web-interface/issues/601) because this one is partially fixed in 0.20-rc.2 version.

Now when I put a '\n' in the full mesage, the new line character is correctly displayed in the tab view but not in "full view" message.

![1](https://f.cloud.github.com/assets/5813331/2137143/7a10523a-9320-11e3-9272-3e8ce9938cbc.jpg)
![2](https://f.cloud.github.com/assets/5813331/2137144/7e9ebf94-9320-11e3-96cd-9cfe786ce719.jpg)

To try that I used this command:

curl -XPOST http://127.0.0.1:12202/gelf -p0 -d '{"short_message":"Test", "full_message":"line1\nline2", "personalField":"line1\nline2" ,"host":"example.org", "facility":"test"}'

Moreover is it possible to also support '\n' for another field than the "ful_message" like for personal field (see my picture), it will be great ! :-)

Thanks for your work.

**Comment by pcrook** [comment]
It's not clear to me that this issue was ever fixed.  I am still seeing the behavior in graylog-web Version: 1.0.1-1 (Ubuntu).  A Java exception in the left pane is one giant text blob while in the right pane it's humanly readable.  Has this been fixed and it regressed, or is it still pending?  Thanks.

**Comment by edmundoa** [comment]
Hi @pcrook,

We reworked the whole search result page for 1.1, so this should behave much better now. Please take a look at the beta release.

**Comment by elfensteak** [comment]
Hi @edmundoa,
yesterday I've installed 1.1.0-rc.3 and still see no line breaks.
A single \n and also \t is translated into a line break and tabulator, but without pre tags the line break won't be shown.
Maybe you could add `<pre></pre>` - Tags for example in graylog2-web-interface/javascript/src/components/search/MessageTableEntry.jsx at line 93:

`<tr class="message-row" data-reactid="...">
<td colspan="2" data-reactid="..."><pre>... `

Thank you!

**Comment by pcrook** [comment]
@elfensteak - Have you confirmed that this change works?
@edmundoa - It appears that this problem persists in the newest release.  Can this issue be reopened?

**Comment by pcrook** [comment]
@edmundoa - Thank you.
Here's a picture of my graylog-web 1.0.1-1 interface while a Java exception is displayed.  On the left, it's undecipherable.  When selected, it's humanly-readable, as seen on the right.  (Hopefully this screenshot from a 4K monitor will scale properly).
![image](https://cloud.githubusercontent.com/assets/12041343/7994523/4534c3ec-0acb-11e5-952c-68e56231e534.png)

**Comment by edmundoa** [comment]
@pcrook that is an old version, at least not 1.1 (the final version was launched just today) and where we changed the whole search result UI. Apparently it doesn't fix the multi-line messages, but still :)

**Comment by pcrook** [comment]
@edmundoa - Sorry.  I don't have a 1.1 installation to grab from.  I was just wanted to convey the user experience while trying to navigate through a series of multi-line log events.  I have no idea what this looks like now.
@elfensteak - Perhaps you could paste a similar picture of the 1.1 interface.  Thanks.

**Comment by elfensteak** [comment]
Here you can see the new UI (1.1 rc3). I like it very much.
You can see the Firefox Code Inspector at the screenshots bottom.
Graylog formats \n and \t correct, but this isn't interpreted by the browser as long as the message output isn't enclosed by `<pre></pre>` tags.
I'couldn't test this solution until now.

![search_results](https://cloud.githubusercontent.com/assets/12746125/8000781/27c95d4c-0b5f-11e5-9841-22cde1ac78fa.PNG)
