### ISSUE TITLE
Use momentjs for universalsearch date parsing

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#628]
https://github.com/Graylog2/graylog2-web-interface/commit/0d117fcdbd4023f058fe35429836eb79b4c89cb3#commitcomment-5419378

**Comment by edmundoa** [comment]
We fixed this in https://github.com/Graylog2/graylog2-web-interface/commit/3ae00e35a349a65511167c2da677e6022ee0606a
