### ISSUE TITLE
Do something with every second polling

### ISSUE THREAD

**Issue by Kagami** [Graylog2/graylog2-web-interface#673]
At first I would like to thank you for the great software. I'm really enjoy using it.

But some thing really scary me:
For some reason I opened the web-console while using the Graylog web interface and it's really surprised me what I saw there: https://f.cloud.github.com/assets/533383/2279772/9a6523b2-9f78-11e3-89a1-4896b07d7e8f.png

It naturally sends AJAX request every second. Why don't you use WebSockets ([available in every modern browser, even IE](http://caniuse.com/websockets)) or long polling at worst?

The same behaviour appears if I log in (it starts polling `/a/system/throughput` instead). And on the streams page even worse: AJAX request for every stream every second. What if I have hundred streams? And the same for the widgets. I already have 8 widgets so it's 9 seconds per second for just single web page.

I would love to see this fixed. Thanks.

I'm using the latest graylog2-server (0.20.1) and latest graylog2-web (0.20.1). Tested with Google Chrome 33.0.1750.117.

**Comment by kroepke** [comment]
This issue has been partly addressed by #1214 #1182 and #779 (see comment there)

The widgets are still polling but we will address that in a future version.

**Comment by bernd** [comment]
Closing this because we are working on fixing this.
