### ISSUE TITLE
Update jquery to most recent version

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-web-interface#696]
Our jquery version is quite old, there are loads of bug fixes since version 1.7.1, we should update it to the latest 1.x version (2.x doesn't support IE8 anymore).
https://github.com/jquery/jquery-migrate can make this easier.

**Comment by edmundoa** [comment]
We updated to jQuery 2.1.1 here: https://github.com/Graylog2/graylog2-web-interface/commit/df69359581f211165588381fdf96efce30c82089
We also included the [jQuery Migrate](https://github.com/jquery/jquery-migrate/) plugin to decrease the amount of required changes during the upgrade.
