### ISSUE TITLE
reset admin password

### ISSUE THREAD

**Issue by ghost** [Graylog2/graylog2-web-interface#698]
How do I reset the admin password?

**Comment by tharasavio** [comment]
i reset my password in config file. NOw its working locally but not when accessing from other servers @lennartkoopmann

**Comment by kroepke** [comment]
It needs to be reset in all graylog servers, this user account is currently not shared via the database @tharasavio

**Comment by coolwayin** [comment]
changed in the graylag.conf and still its not working??
