### ISSUE TITLE
ServerNodes never forget graylog2 server nodes

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-web-interface#744]
This can lead to odd 404 errors in the rest api:
2014-04-04 13:22:23,942 ERROR: org.graylog2.rest.resources.system.ClusterResource - Node <undefined> not found.

the source is the web interfaces server node list, hanging on to nodes forever until restart.
figure out a way to regularly purge it or soemthng

**Comment by garybot2** [comment]
From Github via lennartkoopmann:
(like in the summertime when we first met)

**Comment by bernd** [comment]
Will be fixed in Graylog 2.0.
