### ISSUE TITLE
Restricting timeframes for searches

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-web-interface#754]
I would love to have the ability to restrict the upper bounds for the builtin timeframes that are exposed for searches - in my particular usecase I would like to disallow anything over 30 days (potentially months or years in our case) since that could kill our ES cluster.

**Comment by lennartkoopmann** [comment]
I'd suggest to have a *soft* and a *hard* limitation here: You can either configure to by default restrict to a timeframe but the user can override it by selecting **also search in archives** *or* set a hard limit that cannot be changed.

**Comment by henrikjohansen** [comment]
:+1:

**Comment by kroepke** [comment]
currently debating whether this change is small enough for 1.0.1 or should go into 1.1.0

**Comment by timukas** [comment]
may be add some "search all messages" true/false option to user preferences?

**Comment by runningman84** [comment]
This should go into 1.0.1 cause otherwise they will blame us that even in version 1.0 a single user can crash the whole es cluster... Right now we can say calm down we are still using a 0.9x release, stuff like this can happen here.

**Comment by bernd** [comment]
Closing this because it's already on our roadmap for the next releases.
