### ISSUE TITLE
Quick search for related messages (time based/field based; "grep -A -B" like)

### ISSUE THREAD

**Issue by jmisur** [Graylog2/graylog2-web-interface#755]
**Problem:**
Whenever I search for something in graylog dashboard, I provide search query with concrete words, such as 'exception' etc. This will output only messages which contain this word. When I find the one I was looking for, I often need to see related messages to be able to understand the context. For example, see previous 10 logs, or next 20 logs to see what happened around in my system. Similar to what I do when I use grep with -A -B options.

**How I imagine it could work:**
In search results list I click on a row (right-click/button) and popup will open with following options:
- previous XX records
- next YY records
- previous XX seconds/minutes
- next YY seconds/minutes
- show records only with the same field value as this record (e.g. field: requestID, thread-name, source-file etc)

So I can quickly combine different options and then the main query will be altered in a way I configured (basically time based + field value restriction).

This would help me tremendously to quick filter through unrelated messages to get only the relevant data.

**Comment by edmundoa** [comment]
Closing this issue, as it duplicates #150.
