### ISSUE TITLE
Bundle stream throughput ajax requests

### ISSUE THREAD

**Issue by Mowee** [Graylog2/graylog2-web-interface#779]
At this moment I have about 50 Streams pre configured for everybody. Every stream fires his own json request to get the current throughput. I find this highly ineffectiv because with so many streams the page slows down.

Suggestion: One json request to get all the throughput information that are needed.

**Comment by kroepke** [comment]
This has been addressed by various commits. We are now using a single websocket connection (or fall back to ajax polling) to gather metrics for various updating numbers around the ui.

The only remaining ajax call should be getting the notifications for the menubar, but that's nothing is done per-stream or so.

**Comment by kroepke** [comment]
Specifically https://github.com/Graylog2/graylog2-web-interface/commit/380182c2bf4dff90c906db7b9faa89a6bc820499
