### ISSUE TITLE
Quick Values Graph

### ISSUE THREAD

**Issue by rikatz** [Graylog2/graylog2-web-interface#789]
Not a real issue, but a feature request:

It would be great if we could do a graph based on the percentage extracted from quick values, to have on the dashboard.

An example: How many 200, 300, 404 Return Codes from Apache we have. This (using quick values) generates percentages, that could be used on a bar graph to have an overview of the environment on dashboards.

Thanks!

**Comment by edmundoa** [comment]
On 1.1 we added the possibility to represent the quick values in a pie chart, so I think this can be closed. Please reopen if I'm wrong.
