### ISSUE TITLE
Include the last X Messages of the Stream

### ISSUE THREAD

**Issue by koonoh** [Graylog2/graylog2-web-interface#790]
Before anything, congratulations for the new version of Graylog2 we loved it, Keep the good work!

I might be wrong but, when I configure the last x number of messages that I want to receive from a specific stream alert, I just receive the exact specified amount, this works if I have thousands of messages and just want to trim the last 20, on the other hand if I want to receive an email alert when I have at least 1 message but want to extend the range to let's say the last 25 messages , if the stream captured 20 I don't receive any.

It would be great to be able to specify a maximum amount of last messages and receive any number between that scope :)

Regards.

**Comment by bernd** [comment]
Please check if this is still an issue with Graylog 1.1 and re-open if so. Thank you!
