### ISSUE TITLE
Handle logs from different timezone

### ISSUE THREAD

**Issue by chrisgogreen** [Graylog2/graylog2-web-interface#814]
Setting Up a graylog server and I'm dealing with logs that are being stored using a different timezone, so the Last 15 Minutes relative time filter does account for the time shifted logs.

**Comment by edmundoa** [comment]
Hi @chrisgogreen, any news on this issue?

**Comment by edmundoa** [comment]
Closing, as there was no new information on this in a long time. Please reopen if needed.
