### ISSUE TITLE
Stream Email Alert Content

### ISSUE THREAD

**Issue by pete001** [Graylog2/graylog2-web-interface#836]
In the old version, there used to be a permalink embedded into the email stream alerts, which would take you through to relevant alert messages. 

This seems to have vanished in the new version. It would be fantastic to have each stream alert embedded in the email, with an associated permalink. 

This would save a few clicks and really help to increase productivity.

**Comment by edmundoa** [comment]
As @SjonHortensius said, this should be fixed already. I'm closing the issue now, please reopen if needed.
