### ISSUE TITLE
Stream Dashboard not working

### ISSUE THREAD

**Issue by dennusb** [Graylog2/graylog2-web-interface#840]
Hi,

We are running 0.20.2 and i'm trying to get the Stream Dashboard app up & running. It does not work. CORS is enabled, i can access the ports from my machine but when i want to connect via the Stream Dashboard it either give me no message at all (but no permitted streams) or says it can't connect to the server.

What can i do to fix this?

**Comment by bernd** [comment]
Please open an issue in the https://github.com/Graylog2/graylog2-stream-dashboard repository. Thank you!
