### ISSUE TITLE
pidfile configuration option

### ISSUE THREAD

**Issue by chr4** [Graylog2/graylog2-web-interface#851]
It should be possible to specify a path/filename for `RUNNING_PID`. Furthermore, it may be a good default to place it in a volatile directory like `/tmp` or `/run`.
Currently, the web interface doesn't properly start up after an unexpected exit or server reboot, with the following error message:

```
This application is already running (Or delete /usr/local/graylog2-web-interface-0.20.3/RUNNING_PID file).
```

**Comment by edmundoa** [comment]
Hi,
We use the default behaviour of Play Framework to handle the PID file. You can change it's path as described here: https://www.playframework.com/documentation/2.1.1/ProductionConfiguration
