### ISSUE TITLE
Alert dot is shown under the graph but there's no message which matches alert condition.

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-web-interface#853]
Hi,

I'm sending some logs from logstash to graylog (over gelf UDP).
Logstash parses out bytes and sets this field to numeric.
Graylog is able to generate charts with this field and show some statistics, which means bytes field is numeric.

I have setup "Field value condition" alert: "Alert is triggered when the field bytes has a higher max value than 5.0E7 in the last minute. Grace period: 0 minutes."
So this alert should fire when bytes field has a value over 50000000.

Now i'm making absolute search from "2014-07-29 17:45:48.000 +03:00" to "2014-07-29 17:45:49.000 +03:00". 
Yes, 1 (one) second range.

Search results show 201 messages and gray alert dot under graph (graph resultion is set to Minutes). Alert popup says "Stream "xxxxx" triggered an alert: Field bytes had a max of 8.79329051E8 in the last 1 minutes with trigger condition higher than 50000000. (Current grace time: 0 minutes)"
Converting 8.79329051E8 to nice numbers gives us 879329051. Looking through all messages, there's none with bytes equals 879329051, despite that there's alert dot under graph.

When searching for "bytes:879329051" with wider timerange, graylog finds right message, but message's timestamp is "2014-07-29 17:45:28.562" which 20 seconds before first search.

p.s. I use graylog2-server-0.21.0-SNAPSHOT-20140729093221 and graylog2-web-interface-0.21.0-SNAPSHOT-20140729010251.

This look like bug to me. 
What do you think of that?

**Comment by edmundoa** [comment]
Hi,

Is this still an issue for you?

**Comment by edmundoa** [comment]
Closing the issue, as we didn't get any feedback. Please reopen if this is still a problem.
