### ISSUE TITLE
Dasbhoard button alignment is a bit wrong

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-web-interface#859]
Hi,

Delete and Action buttons on dashboard page are not properly aligned.
![dashboard_buttons_nok](https://cloud.githubusercontent.com/assets/1915618/3796365/18fe8ed6-1bc8-11e4-841a-3d3d9e36881b.png)

Streams and input pages place buttons properly.
![stream_buttons_ok](https://cloud.githubusercontent.com/assets/1915618/3796383/55f75e30-1bc8-11e4-94a0-0cbcdaeb9ebf.png)

I use graylog2-web-interface-0.21.0-SNAPSHOT-20140801121422 and Firefox 31.0 (Windows 7 64bit).

**Comment by edmundoa** [comment]
The action button was replaced in 1c4118bf84f05593d474a5d2ab2dde76ccd32db1 by a standard one and it is now aligned.
