### ISSUE TITLE
Not all field names are displayed on right-side panel.

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-web-interface#860]
Hi,

I'm sending some logs to graylog2 over GELF Udp (logs are normalized with logstash and errors).
When i'm searching for an specific ip address and i get over 200000 (yes, number is correct) messages.
On the right panel (list of message fields) i do not see "user" field (I'm 146% sure, that logstash parses events correctly). 
Note no us* fields after ur* fields (default behaviour):
![field_current_page](https://cloud.githubusercontent.com/assets/1915618/3798098/342a7120-1be1-11e4-8b27-275554ccc2da.png)

Now i click "all", to show all message fields and "user" field gets visible. "Quick values" also show some results where user field is present.
Now there's us* fields after ur* fields:
![field_all](https://cloud.githubusercontent.com/assets/1915618/3798101/407dd890-1be1-11e4-8f05-5c04259e55fd.png)

When i perform search like "clientip:xxx.xxx.xxx.xxx AND _exists_:user" (timerange is always the same in all searches) - i get "user" field visible on right panel and can do usual things like "quick values".

My question is, does "Message fields of current page" have some limits? E.g. by default it shows fields only from last 10000 events (or something)?

My understanding, is that fields are shown from all found events. But currently it does not show all fields available.

Any comments on that?

I use latest snaphosts - graylog2-server-0.21.0-SNAPSHOT-20140801134042 & graylog2-web-interface-0.21.0-SNAPSHOT-20140801121422.

regards,

**Comment by edmundoa** [comment]
Hi,

Is this still an issue?

**Comment by edmundoa** [comment]
Closing the issue, as there's no new information about it. Please reopen if needed!
