### ISSUE TITLE
Some metrics numbers are shown in exponent form.

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-web-interface#867]
Hi,

Gelf input "read_bytes_total " metrics show numbers in E form.

![gelf_input_metrics](https://cloud.githubusercontent.com/assets/1915618/3853735/6b50d396-1ecb-11e4-98da-16a3d62c096d.png)

There're might be more similar places, but seems that due to my low metrics numbers i cannot find them all.

regards,

**Comment by edmundoa** [comment]
This was fixed here: https://github.com/Graylog2/graylog2-web-interface/commit/9d03c9fff589f7eaf96661f496e4bbf55095f4cb

Related to #852
