### ISSUE TITLE
Widget order in dashboards is sometimes not (or badly) saved.

### ISSUE THREAD

**Issue by rsaikali** [Graylog2/graylog2-web-interface#873]
Hi,

I've got a 18 widget dashboard, and when I reorder the widgets (drag/drop) and refresh the page, the choosen position is lost.

Regards.

R.SAIKALI

**Comment by reighnman** [comment]
+1

I've had it sometimes where I save then refresh the page and they revert back to a previous position.  Until I delete the widget object causing it (through guessing) and readding it, the position will finally stay where I want it.

**Comment by razvanphp** [comment]
Bump? I got into this again today, very annoying, maybe it's an easy fix..

**Comment by edmundoa** [comment]
We did some improvements on 1.1 on this regard, although is hard to tell if it's really fixed. I'm closing the bug for now, please reopen if you still see problems with this on 1.1.
