### ISSUE TITLE
Clickable urls

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-web-interface#879]
Hi,

Graylog 0.12 detected URLs from messages and made them clickable. This feature is very useful for some logs. Instead of copying url from rightside panel you could just click on it and it would be opened in new tab/window.

Currently in graylog2 (beta3 latest snapshot) it is not possible to select part of text from rightside panel. 
You have to select whole message, paste it to notepad and then select required part.

That's pretty annoying.

**Comment by edmundoa** [comment]
On 1.1 it is possible to select parts of message fields, so I think this can be closed. Please reopen if needed.
