### ISSUE TITLE
[0.21.0-beta2] Monotone interpolation in graphs is really strange....

### ISSUE THREAD

**Issue by rsaikali** [Graylog2/graylog2-web-interface#883]
Go home Graylog, you're drunk...  :-)

![screenshot - 20082014 - 13 49 03](https://cloud.githubusercontent.com/assets/1914609/3980309/6f75e468-2860-11e4-999c-6cfc9760d41f.png)

**Comment by edmundoa** [comment]
Closing, as this is quite old and I don't think latest versions are affected. Please reopen if this is still relevant.
