### ISSUE TITLE
Force dashboard reload

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-web-interface#889]
Hi,

I have 10 widgets with cache time set to 30 minutes. I'm trying to be nice to graylog and ES and not overload it with queries.

But sometime i want data to be refreshed. Changing cache time for all widgets is not very convenient.

May be having a button "refresh all widgets" would make this much easier?

regards,

**Comment by bernd** [comment]
The dashboards code has been improved since then. Please re-open if this is still an issue with 1.1. Thank you!
