### ISSUE TITLE
Dashboard data differs from quick value data.

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-web-interface#890]
Hi,

I have dashboard for quick values from one stream. Here's Widget config:
    field: facility
    range: 7200
    query: *
    range_type: relative
    stream_id: 53e4b758e4b0dbd24d1ba585

This dashboard shows only 2 rows of data.
![dashboard_01](https://cloud.githubusercontent.com/assets/1915618/4008244/542ec56a-29d4-11e4-8e7d-7059787f7f1e.png)

If i replay widget's search and check quick values for facility i see 3 rows.
![dashboard_02](https://cloud.githubusercontent.com/assets/1915618/4008258/85900664-29d4-11e4-967e-f11f097762af.png)

When i check for all three facilities i noticed that P1 an P2 facilities are present for whole period (2 hours). 
![dashboard_04](https://cloud.githubusercontent.com/assets/1915618/4008426/e81018e0-29d6-11e4-9bae-9071d8240ab3.png)

But P3 facility (which is missing in dashboard) has some empty spots during 2 hour period (this is normal behavior for P3 facility)

![dashboard_03](https://cloud.githubusercontent.com/assets/1915618/4008304/56063688-29d5-11e4-902f-8ec04fd36cdb.png)

Any ideas, why dashboard widget is not showing all three facilities?

P.s. I'm running graylog2-server-0.21.0-beta3-SNAPSHOT-20140821155104, graylog2-radio-0.21.0-beta3-SNAPSHOT-20140821155104 and graylog2-web-interface-0.21.0-beta3-SNAPSHOT-2014082117453.

**Comment by guillermosacchi** [comment]
How i check the version of my graylog2 web interface? . I have the same problem, a widget suddenly turn empty. Some expert can help me ? Tanks

**Comment by edmundoa** [comment]
@guillermosacchi In recent versions it is displayed at the bottom of each page in the web interface. Previously I am not really sure were it was displayed, so it's probably easier to check the server version (it shows up in its logs when starting), and then infer the web interface version you are using, as they usually match.

Either way, this issue is really old and was fixed long time ago. Please ensure you are using a recent Graylog version (currently 2.0), and create a new issue if this is still a problem for you..

**Comment by guillermosacchi** [comment]
THANKS for your response, suddenly the wigget start working OK. I didnt do anything. On the bottom of the page the version is graylog-web-interface v1.3.4(0d67a80)(Oracle Corp. 1.8.0_77 / Linux kernel 3.13.0-32-generic) .

**Comment by edmundoa** [comment]
@guillermosacchi sounds a bit weird, but maybe there was some temporary problems. Good to see it is working again!

**Comment by guillermosacchi** [comment]
Hi, the problem returns. Quick Values not rendering. I clean temp of IE / Chrome , I check with other PC, i have the same error. The Pie chart is empty for quick values extracted. Its ver strange suddenly stop working later works fine ....

**Comment by edmundoa** [comment]
@guillermosacchi As mentioned before, this issue is really old and most likely not the same you are experiencing. Please try updating to 2.0 and see if that helps with your issue. If it does not, use one of our [support channels](https://www.graylog.org/community-support/).
Thank you!

**Comment by guillermosacchi** [comment]
Have you got a procedure to how to ugrade whithout lose the logs / the information , Thanks edmundoa for your response.

**Comment by joschi** [comment]
@guillermosacchi Please refer to http://docs.graylog.org/en/2.0/pages/installation/graylog_ctl.html#upgrade-graylog and http://docs.graylog.org/en/2.0/pages/upgrade.html
