### ISSUE TITLE
[0.21.0-beta4] Fails to escape double quotes when picking a message field value as the search string

### ISSUE THREAD

**Issue by 2ion** [Graylog2/graylog2-web-interface#900]
For example, if we pick field baz from the sidebar:
```
Foo "Bar" Foo
```
gets inserted as
```
baz:"Foo "Bar" Foo"
```
into the search bar which will produce wrong results. It should be
```
baz:"Foo \"Bar\" Foo"
```

**Comment by edmundoa** [comment]
This was fixed in 50724d270cf4f9b59fb17e2f5f91e174618c6599
