### ISSUE TITLE
streams search field & paging

### ISSUE THREAD

**Issue by rschitz** [Graylog2/graylog2-web-interface#902]
Hi folks,
We're using a LOT of streams (300+) and it's always a pain to search (!) in so it would be great to have a paging limit to 10 or 15 streams and a search field

Thanks

**Comment by henrikjohansen** [comment]
+1 ... a search-as-you-type search bar would be awesome for streams :)

**Comment by bernd** [comment]
I am closing this because something like this is on the roadmap and we are already working on this.
