### ISSUE TITLE
Message not displayed correctly on right side bar (no scroll)

### ISSUE THREAD

**Issue by martyitfc** [Graylog2/graylog2-web-interface#906]
Hi,

Graylog2 0.21.0 rc1 (installed via RPM)

Web UI (visual issue)
- Noticed when clicking on the message, the side bar on right doesn't display in window (incorrect wrap around), no scroll bar.
- When clicked on last field (full_message) the 'search value' options pops up with scroll bar, but hard to control, keeps jumping. Message is not wrapping.

Image shown, with no wrap on 'full_message' no scroll bar.

Rgs,
Marty

![graylog021rc1](https://cloud.githubusercontent.com/assets/8813972/4313614/2c5bf3a2-3ecc-11e4-8325-dc128fc5689b.png)

**Comment by edmundoa** [comment]
A little update on this issue: I was looking into it again and the double new line happens only in the `full_message` field, when it contains a multi-line message with Windows line breaks.

**Comment by kroepke** [comment]
The page is completely redesigned in 1.1 so I'm closing this issue.
