### ISSUE TITLE
Web interface notifications would not go away. 

### ISSUE THREAD

**Issue by sauliuspr** [Graylog2/graylog2-web-interface#911]
Administrator users role gets system notifications like:
"There was no master graylog2-server node detected in the cluster. 7 hours ago". 
"You are running an outdated Graylog2 version. 10 hours ago"

These message will not go away. Since only option for users to have search ability is to  assign them administrator rights everyones sees those messages and are wondering is everything is ok with graylog.

**Comment by edmundoa** [comment]
Good to hear that the notification went away for good! Regarding the update notification, the message appears constantly mainly because notifications are not tied to a user at the moment, so we can't hide the notification for a single user. I created #1147 to think about how to improve that.
