### ISSUE TITLE
Starting input plugins that have no configuration fields fails

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#913]
One cannot launch `MessageInput` plugins that return an empty `ConfigurationRequest` in `getRequestedConfiguration()` like this:

    @Override
    public ConfigurationRequest getRequestedConfiguration() {
        return new ConfigurationRequest();
    }

The web interface will fail with a HTTP 500, reporting an illegal state of the form. I guess that the `requested_configuration` is not set and we try to access it.

I had to add a `TextField` field with senseless values to make it work.

**Comment by bernd** [comment]
This should work in 1.1. Please re-open if this is still a problem. Thanks!
