### ISSUE TITLE
Make saved searches more private.

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-web-interface#923]
Hi,

Currently saved searches are visible to everyone.
In some cases i do not want to show my saved searches to other graylog users.

A checkbox (make saved search visible to everyone) could be implemented when saving searches.
By default saved search could be visible to creator only.

**Comment by edmundoa** [comment]
I think this issue is the same explained in #546, and that is probably a better solution for the problem, so I'm closing the issue. Please reopen if it's necessary.
