### ISSUE TITLE
System->Users page is missing search bar.

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-web-interface#927]
Hi,

Installed graylog2-server-0.92.0-SNAPSHOT-20141010165534 and graylog2-web-interface-0.92.0-SNAPSHOT-20141010154940.
System->Users page is not showing search field, time selector and saved searches.
![users_no_search](https://cloud.githubusercontent.com/assets/1915618/4602454/a8077474-513a-11e4-96f3-391f5b98b17d.png)

All other System pages show search bar correctly.

**Comment by edmundoa** [comment]
I'm closing this issue, as it is included in #1074.
