### ISSUE TITLE
Stream alerts - message count condition

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-web-interface#939]
Hi,

Would be nice to extend message count condition alerts to allow select specific field(s) and it's value(s). E.g. send an alert if within 5 minutes you have http_status:500 seen over 10 times.

Currently for every alert you have to create separate stream and setup there it's own message counter. This is a bit uncomfortable.

Disabling/pausing alerts also would be nice feature.

regards,

**Comment by razvanphp** [comment]
+1

**Comment by edmundoa** [comment]
If I understood this right, I think it's what we addressed on https://github.com/Graylog2/graylog2-web-interface/pull/1305, so I'm closing this. Please reopen if necessary.
