### ISSUE TITLE
Stacked graphs

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-web-interface#948]
Hi,

It's not an issue, it's more like a feature request.

Would be nice to see stacked graphs in main histogram. E.g. show different colors for http status codes or ip addresses or any other fields.

Just an example how it could look like:
![3565207](https://cloud.githubusercontent.com/assets/1915618/4805400/581ecc42-5e7c-11e4-9042-d491c2150f5a.jpg)

regards,

**Comment by edmundoa** [comment]
Hi,

I think this is basically the same feature described in #613, so I'm closing the issue. Please reopen if you think I'm wrong :)
