### ISSUE TITLE
Wildcard search works only for some fields.

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-web-interface#951]
Hi,

I'm running latest 0.92 SNAPSHOT.

Noticed strange issues with wildcard searches:

code:TCP_DENIED AND client_ip:172.24.168.42 -  works fine. 
code:TCP_DENIED AND client_ip:172.24.168.* - works fine.
code:TCP_DENIED AND client_ip:172.24.168.?? - works fine.

code:TCP_* AND client_ip:172.24.168.42 - no results.
code:TCP_DENIE? AND client_ip:172.24.168.42 - no results.

Any ideas why i have no results on some wildcard searches?

**Comment by edmundoa** [comment]
Closing, as this seems to be the same issue as #1025
