### ISSUE TITLE
Strange behavior of "Quick values"?

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-web-interface#961]
Hi,

Here's the situation.
I'm searching for specific ip address "clientip:xxx.xxx.xx.x". Period is 2 days. Search results show 46,750 messages. Now i'm running "quick values" for "cookie" field. And graylog server dies.
Seems that "quick values" runs against all messages of 2 day period, not just for found results.
For 2 days i have totally 309,775,162 messages.

Event if run "quick values" for small amount of found results (50 messages) it takes 10 seconds to display quick value results.

Is this a bug or it's a feature?

regards,

**Comment by bernd** [comment]
Please check if this is still a problem with Graylog 1.1 and re-open this issue if needed. Thank you!
