### ISSUE TITLE
Users disappear after upgrade 0.20.3 -> 0.91.3

### ISSUE THREAD

**Issue by tleveque23** [Graylog2/graylog2-web-interface#963]
We did the upgrade of our installation from 0.20.3 to 0.91.3 and also upgrade Elasticsearch to 1.4.
Everything seams to work fine. We can log-in using the admin account and see all the logs. All the config is still present. But no users are visible in the user section. Ans we are unable to log-in using our regular users. And also unable to create new users!
If we change the mongodb name, it is working fine, but we lost all of our settings!!!!

**Comment by edmundoa** [comment]
As we didn't receive any feedback in a while I'm closing the issue now. Please reopen if this is still a problem.
