### ISSUE TITLE
Saved searche fields are not shown

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-web-interface#967]
Hi,

I'm running Graylog v0.92.0-beta.1.
I have several short term (2 hour) saved searches with some specific fields selected.
When i select one saved search i get an empty results (this is normal, that there's no results at the morning time), now i'm making time ranger bigger - setting it to 1 day and i see results, but saved columns are reset to source and message. Previously saved columns not displayed, i have to select them manually.

Thoughts?

**Comment by bernd** [comment]
The search page has been rewritten for 1.1.0. Please re-open the issue if this is still a problem in 1.1.0. Thank you!
