### ISSUE TITLE
Paused input is activated after server restart.

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-web-interface#973]
Hi,

Running graylog2-server-0.93.0-SNAPSHOT-20141118171516 + graylog2-web-interface-0.93.0-SNAPSHOT-20141118175513.

Noticed one strange thing.
If input is stopped (Graylog2 Radio Input (AMQP) in my case) and graylog server is restarted, then input set to active (running) state.

I'm expecting, that if i pause some input, then restart of graylog server shouldn't make it running.

Is this done by design or it's a bug?

**Comment by edmundoa** [comment]
Closing this issue in favour of https://github.com/Graylog2/graylog2-server/issues/967.
