### ISSUE TITLE
Hitting search from stream's alert page makes global search, not search from stream.

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-web-interface#980]
Hi,

Running graylog2-server-0.93.0-SNAPSHOT-20141124162027 + graylog2-web-interface-0.93.0-SNAPSHOT-20141124213918.

When i hit search button from stream's alert page, then graylog2 run search on all messages, not on that stream where i sit.

Imho, it would be more convenient to search within the same stream where alerts are examined.

**Comment by dennisoelkers** [comment]
This is implicitly fixed as the stream alerts page does not have a search bar anymore.
