### ISSUE TITLE
Sorting events in order of arrival

### ISSUE THREAD

**Issue by alpha-centauri** [Graylog2/graylog2-web-interface#988]
Dealing with sources producing several hundreds of messages per second, groups of events with equal timestamps are inevitable. Some systems even produce logs containing several event lines emitted at the same point in time with a chronological relation.
It would be nice if events could be sorted in order of processing/arrival. Therefor, the first eight (hex)digits of the message ID could be used to sort events in case of equal timestamps since this part of the ID seems to be incremented with incoming events.

**Comment by joschi** [comment]
@alpha-centauri I'm closing this issue in favor of Graylog2/graylog2-server#2741.
