### ISSUE TITLE
Modify edit stream rule modal 

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-web-interface#992]
Edit stream rule modals are rendered into a list with the bootstrap `alert` class. That has some side effects that we only solve partially, like you can see in the screenshot. We should use React to solve the problem and not rendering one modal per existing stream rule.

![screen shot 2014-12-02 at 16 23 37](https://cloud.githubusercontent.com/assets/716185/5265017/b8b31b7e-7a3f-11e4-8879-c77b64096625.png)

**Comment by dennisoelkers** [comment]
Fixed due to rewrite in https://github.com/Graylog2/graylog2-web-interface/pull/1264
