### ISSUE TITLE
Oh no, something went wrong!

### ISSUE THREAD

**Issue by CaesarC** [Graylog2/graylog2-web-interface#999]
i just finish install it yesterday.But it goes down today.My wed site receive 1  thousand events per hour
things goes like that:
![1](https://cloud.githubusercontent.com/assets/7133914/5371496/b4aad894-8072-11e4-8b1c-31de7f967046.png)
![2](https://cloud.githubusercontent.com/assets/7133914/5371498/badd43c8-8072-11e4-9de6-ca7eaf0796ed.png)
![3](https://cloud.githubusercontent.com/assets/7133914/5371500/bebf10c0-8072-11e4-926e-70d9fc62ba33.png)

**Comment by edmundoa** [comment]
Hello,

Sorry that we didn't respond to this issue before. Is this still a problem for you?

**Comment by edmundoa** [comment]
After re-reading the first errors, I saw they are related to the disk cache, which is completely rewritten for 1.0. Therefore, I'm closing this issue now. Please give Graylog 1.0 beta a try: https://www.graylog2.org/news/post/0014-graylog-v1-0-0-beta1
